/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1AiChatMutationRequest, PostV1AiChatMutationResponse, PostV1AiChat400, PostV1AiChat401, PostV1AiChat404, PostV1AiChat500 } from "../../../../../../packages/types/kubb/PostV1AiChat.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1AiChatMutationKey = () => [{ url: '/v1/ai/chat' }] as const

export type PostV1AiChatMutationKey = ReturnType<typeof postV1AiChatMutationKey>

/**
 * @description Get AI-powered code hints and suggestions
 * {@link /v1/ai/chat}
 */
export async function postV1AiChat(data: PostV1AiChatMutationRequest, config: Partial<RequestConfig<PostV1AiChatMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1AiChatMutationResponse, ResponseErrorConfig<PostV1AiChat400 | PostV1AiChat401 | PostV1AiChat404 | PostV1AiChat500>, PostV1AiChatMutationRequest>({ method : "POST", url : `/v1/ai/chat`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Get AI-powered code hints and suggestions
 * {@link /v1/ai/chat}
 */
export function usePostV1AiChat<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1AiChatMutationResponse, ResponseErrorConfig<PostV1AiChat400 | PostV1AiChat401 | PostV1AiChat404 | PostV1AiChat500>, {data: PostV1AiChatMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1AiChatMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1AiChatMutationKey()

  return useMutation<PostV1AiChatMutationResponse, ResponseErrorConfig<PostV1AiChat400 | PostV1AiChat401 | PostV1AiChat404 | PostV1AiChat500>, {data: PostV1AiChatMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1AiChat(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}