/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, GetV1ChallengesChallengeidReferenceSolutionsPathParams, GetV1ChallengesChallengeidReferenceSolutions401, GetV1ChallengesChallengeidReferenceSolutions403, GetV1ChallengesChallengeidReferenceSolutions404 } from "../../../../../../../packages/types/kubb/GetV1ChallengesChallengeidReferenceSolutions.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey = (challengeId: GetV1ChallengesChallengeidReferenceSolutionsPathParams["challengeId"]) => [{ url: '/v1/challenges/:challengeId/reference-solutions/', params: {challengeId:challengeId} }] as const

export type GetV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey = ReturnType<typeof getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey>

/**
 * @description List all reference solutions for a challenge
 * @summary List reference solutions
 * {@link /v1/challenges/:challengeId/reference-solutions/}
 */
export async function getV1ChallengesChallengeidReferenceSolutionsSuspense(challengeId: GetV1ChallengesChallengeidReferenceSolutionsPathParams["challengeId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidReferenceSolutions401 | GetV1ChallengesChallengeidReferenceSolutions403 | GetV1ChallengesChallengeidReferenceSolutions404>, unknown>({ method : "GET", url : `/v1/challenges/${challengeId}/reference-solutions/`, ... requestConfig })  
  return res.data
}

export function getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryOptions(challengeId: GetV1ChallengesChallengeidReferenceSolutionsPathParams["challengeId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey(challengeId)
  return queryOptions<GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidReferenceSolutions401 | GetV1ChallengesChallengeidReferenceSolutions403 | GetV1ChallengesChallengeidReferenceSolutions404>, GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, typeof queryKey>({
   enabled: !!(challengeId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesChallengeidReferenceSolutionsSuspense(challengeId, config)
   },
  })
}

/**
 * @description List all reference solutions for a challenge
 * @summary List reference solutions
 * {@link /v1/challenges/:challengeId/reference-solutions/}
 */
export function useGetV1ChallengesChallengeidReferenceSolutionsSuspense<TData = GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey>(challengeId: GetV1ChallengesChallengeidReferenceSolutionsPathParams["challengeId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1ChallengesChallengeidReferenceSolutionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidReferenceSolutions401 | GetV1ChallengesChallengeidReferenceSolutions403 | GetV1ChallengesChallengeidReferenceSolutions404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryKey(challengeId)

  const query = useSuspenseQuery({
   ...getV1ChallengesChallengeidReferenceSolutionsSuspenseQueryOptions(challengeId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesChallengeidReferenceSolutions401 | GetV1ChallengesChallengeidReferenceSolutions403 | GetV1ChallengesChallengeidReferenceSolutions404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}