/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1KnowledgeBasesKbidDocumentsDocidMutationResponse, DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams, DeleteV1KnowledgeBasesKbidDocumentsDocid401, DeleteV1KnowledgeBasesKbidDocumentsDocid403, DeleteV1KnowledgeBasesKbidDocumentsDocid404 } from "../../../../../../packages/types/kubb/DeleteV1KnowledgeBasesKbidDocumentsDocid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1KnowledgeBasesKbidDocumentsDocidMutationKey = () => [{ url: '/v1/knowledge-bases/:kbId/documents/:docId' }] as const

export type DeleteV1KnowledgeBasesKbidDocumentsDocidMutationKey = ReturnType<typeof deleteV1KnowledgeBasesKbidDocumentsDocidMutationKey>

/**
 * @description Soft delete a document and its chunks from the knowledge base
 * @summary Delete knowledge base document
 * {@link /v1/knowledge-bases/:kbId/documents/:docId}
 */
export async function deleteV1KnowledgeBasesKbidDocumentsDocid(kbId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["kbId"], docId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["docId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1KnowledgeBasesKbidDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1KnowledgeBasesKbidDocumentsDocid401 | DeleteV1KnowledgeBasesKbidDocumentsDocid403 | DeleteV1KnowledgeBasesKbidDocumentsDocid404>, unknown>({ method : "DELETE", url : `/v1/knowledge-bases/${kbId}/documents/${docId}`, ... requestConfig })  
  return res.data
}

/**
 * @description Soft delete a document and its chunks from the knowledge base
 * @summary Delete knowledge base document
 * {@link /v1/knowledge-bases/:kbId/documents/:docId}
 */
export function useDeleteV1KnowledgeBasesKbidDocumentsDocid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1KnowledgeBasesKbidDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1KnowledgeBasesKbidDocumentsDocid401 | DeleteV1KnowledgeBasesKbidDocumentsDocid403 | DeleteV1KnowledgeBasesKbidDocumentsDocid404>, {kbId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["kbId"], docId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["docId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1KnowledgeBasesKbidDocumentsDocidMutationKey()

  return useMutation<DeleteV1KnowledgeBasesKbidDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1KnowledgeBasesKbidDocumentsDocid401 | DeleteV1KnowledgeBasesKbidDocumentsDocid403 | DeleteV1KnowledgeBasesKbidDocumentsDocid404>, {kbId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["kbId"], docId: DeleteV1KnowledgeBasesKbidDocumentsDocidPathParams["docId"]}, TContext>({
    mutationFn: async({ kbId, docId }) => {
      return deleteV1KnowledgeBasesKbidDocumentsDocid(kbId, docId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}