/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1KnowledgeBasesKbidQueryResponse, GetV1KnowledgeBasesKbidPathParams, GetV1KnowledgeBasesKbid401, GetV1KnowledgeBasesKbid403, GetV1KnowledgeBasesKbid404 } from "../../../../../../packages/types/kubb/GetV1KnowledgeBasesKbid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1KnowledgeBasesKbidSuspenseQueryKey = (kbId: GetV1KnowledgeBasesKbidPathParams["kbId"]) => [{ url: '/v1/knowledge-bases/:kbId', params: {kbId:kbId} }] as const

export type GetV1KnowledgeBasesKbidSuspenseQueryKey = ReturnType<typeof getV1KnowledgeBasesKbidSuspenseQueryKey>

/**
 * @description Get a knowledge base with its documents
 * @summary Get knowledge base by ID
 * {@link /v1/knowledge-bases/:kbId}
 */
export async function getV1KnowledgeBasesKbidSuspense(kbId: GetV1KnowledgeBasesKbidPathParams["kbId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1KnowledgeBasesKbidQueryResponse, ResponseErrorConfig<GetV1KnowledgeBasesKbid401 | GetV1KnowledgeBasesKbid403 | GetV1KnowledgeBasesKbid404>, unknown>({ method : "GET", url : `/v1/knowledge-bases/${kbId}`, ... requestConfig })  
  return res.data
}

export function getV1KnowledgeBasesKbidSuspenseQueryOptions(kbId: GetV1KnowledgeBasesKbidPathParams["kbId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1KnowledgeBasesKbidSuspenseQueryKey(kbId)
  return queryOptions<GetV1KnowledgeBasesKbidQueryResponse, ResponseErrorConfig<GetV1KnowledgeBasesKbid401 | GetV1KnowledgeBasesKbid403 | GetV1KnowledgeBasesKbid404>, GetV1KnowledgeBasesKbidQueryResponse, typeof queryKey>({
   enabled: !!(kbId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1KnowledgeBasesKbidSuspense(kbId, config)
   },
  })
}

/**
 * @description Get a knowledge base with its documents
 * @summary Get knowledge base by ID
 * {@link /v1/knowledge-bases/:kbId}
 */
export function useGetV1KnowledgeBasesKbidSuspense<TData = GetV1KnowledgeBasesKbidQueryResponse, TQueryKey extends QueryKey = GetV1KnowledgeBasesKbidSuspenseQueryKey>(kbId: GetV1KnowledgeBasesKbidPathParams["kbId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1KnowledgeBasesKbidQueryResponse, ResponseErrorConfig<GetV1KnowledgeBasesKbid401 | GetV1KnowledgeBasesKbid403 | GetV1KnowledgeBasesKbid404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1KnowledgeBasesKbidSuspenseQueryKey(kbId)

  const query = useSuspenseQuery({
   ...getV1KnowledgeBasesKbidSuspenseQueryOptions(kbId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1KnowledgeBasesKbid401 | GetV1KnowledgeBasesKbid403 | GetV1KnowledgeBasesKbid404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}