/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PutV1KnowledgeBasesKbidMutationRequest, PutV1KnowledgeBasesKbidMutationResponse, PutV1KnowledgeBasesKbidPathParams, PutV1KnowledgeBasesKbid401, PutV1KnowledgeBasesKbid403, PutV1KnowledgeBasesKbid404 } from "../../../../../../packages/types/kubb/PutV1KnowledgeBasesKbid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const putV1KnowledgeBasesKbidMutationKey = () => [{ url: '/v1/knowledge-bases/:kbId' }] as const

export type PutV1KnowledgeBasesKbidMutationKey = ReturnType<typeof putV1KnowledgeBasesKbidMutationKey>

/**
 * @description Update a knowledge base title or description
 * @summary Update knowledge base
 * {@link /v1/knowledge-bases/:kbId}
 */
export async function putV1KnowledgeBasesKbid(kbId: PutV1KnowledgeBasesKbidPathParams["kbId"], data?: PutV1KnowledgeBasesKbidMutationRequest, config: Partial<RequestConfig<PutV1KnowledgeBasesKbidMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutV1KnowledgeBasesKbidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbid401 | PutV1KnowledgeBasesKbid403 | PutV1KnowledgeBasesKbid404>, PutV1KnowledgeBasesKbidMutationRequest>({ method : "PUT", url : `/v1/knowledge-bases/${kbId}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Update a knowledge base title or description
 * @summary Update knowledge base
 * {@link /v1/knowledge-bases/:kbId}
 */
export function usePutV1KnowledgeBasesKbid<TContext>(options: 
{
  mutation?: UseMutationOptions<PutV1KnowledgeBasesKbidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbid401 | PutV1KnowledgeBasesKbid403 | PutV1KnowledgeBasesKbid404>, {kbId: PutV1KnowledgeBasesKbidPathParams["kbId"], data?: PutV1KnowledgeBasesKbidMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutV1KnowledgeBasesKbidMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putV1KnowledgeBasesKbidMutationKey()

  return useMutation<PutV1KnowledgeBasesKbidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbid401 | PutV1KnowledgeBasesKbid403 | PutV1KnowledgeBasesKbid404>, {kbId: PutV1KnowledgeBasesKbidPathParams["kbId"], data?: PutV1KnowledgeBasesKbidMutationRequest}, TContext>({
    mutationFn: async({ kbId, data }) => {
      return putV1KnowledgeBasesKbid(kbId, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}