/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest, PutV1KnowledgeBasesKbidEntriesEntryidMutationResponse, PutV1KnowledgeBasesKbidEntriesEntryidPathParams, PutV1KnowledgeBasesKbidEntriesEntryid401, PutV1KnowledgeBasesKbidEntriesEntryid403, PutV1KnowledgeBasesKbidEntriesEntryid404 } from "../../../../../../packages/types/kubb/PutV1KnowledgeBasesKbidEntriesEntryid.ts";
import { useMutation } from "@tanstack/react-query";

export const putV1KnowledgeBasesKbidEntriesEntryidMutationKey = () => [{ url: '/v1/knowledge-bases/:kbId/entries/:entryId' }] as const

export type PutV1KnowledgeBasesKbidEntriesEntryidMutationKey = ReturnType<typeof putV1KnowledgeBasesKbidEntriesEntryidMutationKey>

/**
 * @description Update a manual entry and regenerate its embedding
 * @summary Update manual knowledge base entry
 * {@link /v1/knowledge-bases/:kbId/entries/:entryId}
 */
export async function putV1KnowledgeBasesKbidEntriesEntryid(kbId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["kbId"], entryId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["entryId"], data: PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest, config: Partial<RequestConfig<PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutV1KnowledgeBasesKbidEntriesEntryidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbidEntriesEntryid401 | PutV1KnowledgeBasesKbidEntriesEntryid403 | PutV1KnowledgeBasesKbidEntriesEntryid404>, PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest>({ method : "PUT", url : `/v1/knowledge-bases/${kbId}/entries/${entryId}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Update a manual entry and regenerate its embedding
 * @summary Update manual knowledge base entry
 * {@link /v1/knowledge-bases/:kbId/entries/:entryId}
 */
export function usePutV1KnowledgeBasesKbidEntriesEntryid<TContext>(options: 
{
  mutation?: UseMutationOptions<PutV1KnowledgeBasesKbidEntriesEntryidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbidEntriesEntryid401 | PutV1KnowledgeBasesKbidEntriesEntryid403 | PutV1KnowledgeBasesKbidEntriesEntryid404>, {kbId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["kbId"], entryId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["entryId"], data: PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putV1KnowledgeBasesKbidEntriesEntryidMutationKey()

  return useMutation<PutV1KnowledgeBasesKbidEntriesEntryidMutationResponse, ResponseErrorConfig<PutV1KnowledgeBasesKbidEntriesEntryid401 | PutV1KnowledgeBasesKbidEntriesEntryid403 | PutV1KnowledgeBasesKbidEntriesEntryid404>, {kbId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["kbId"], entryId: PutV1KnowledgeBasesKbidEntriesEntryidPathParams["entryId"], data: PutV1KnowledgeBasesKbidEntriesEntryidMutationRequest}, TContext>({
    mutationFn: async({ kbId, entryId, data }) => {
      return putV1KnowledgeBasesKbidEntriesEntryid(kbId, entryId, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}