/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1KnowledgeBasesKbidEntriesMutationRequest, PostV1KnowledgeBasesKbidEntriesMutationResponse, PostV1KnowledgeBasesKbidEntriesPathParams, PostV1KnowledgeBasesKbidEntries401, PostV1KnowledgeBasesKbidEntries403, PostV1KnowledgeBasesKbidEntries404 } from "../../../../../../packages/types/kubb/PostV1KnowledgeBasesKbidEntries.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1KnowledgeBasesKbidEntriesMutationKey = () => [{ url: '/v1/knowledge-bases/:kbId/entries/' }] as const

export type PostV1KnowledgeBasesKbidEntriesMutationKey = ReturnType<typeof postV1KnowledgeBasesKbidEntriesMutationKey>

/**
 * @description Create a manual chunk entry in the knowledge base (no document)
 * @summary Create manual knowledge base entry
 * {@link /v1/knowledge-bases/:kbId/entries/}
 */
export async function postV1KnowledgeBasesKbidEntries(kbId: PostV1KnowledgeBasesKbidEntriesPathParams["kbId"], data: PostV1KnowledgeBasesKbidEntriesMutationRequest, config: Partial<RequestConfig<PostV1KnowledgeBasesKbidEntriesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1KnowledgeBasesKbidEntriesMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidEntries401 | PostV1KnowledgeBasesKbidEntries403 | PostV1KnowledgeBasesKbidEntries404>, PostV1KnowledgeBasesKbidEntriesMutationRequest>({ method : "POST", url : `/v1/knowledge-bases/${kbId}/entries/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Create a manual chunk entry in the knowledge base (no document)
 * @summary Create manual knowledge base entry
 * {@link /v1/knowledge-bases/:kbId/entries/}
 */
export function usePostV1KnowledgeBasesKbidEntries<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1KnowledgeBasesKbidEntriesMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidEntries401 | PostV1KnowledgeBasesKbidEntries403 | PostV1KnowledgeBasesKbidEntries404>, {kbId: PostV1KnowledgeBasesKbidEntriesPathParams["kbId"], data: PostV1KnowledgeBasesKbidEntriesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1KnowledgeBasesKbidEntriesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1KnowledgeBasesKbidEntriesMutationKey()

  return useMutation<PostV1KnowledgeBasesKbidEntriesMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidEntries401 | PostV1KnowledgeBasesKbidEntries403 | PostV1KnowledgeBasesKbidEntries404>, {kbId: PostV1KnowledgeBasesKbidEntriesPathParams["kbId"], data: PostV1KnowledgeBasesKbidEntriesMutationRequest}, TContext>({
    mutationFn: async({ kbId, data }) => {
      return postV1KnowledgeBasesKbidEntries(kbId, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}