/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1KnowledgeBasesKbidDocumentsMutationResponse, PostV1KnowledgeBasesKbidDocumentsPathParams, PostV1KnowledgeBasesKbidDocuments400, PostV1KnowledgeBasesKbidDocuments401, PostV1KnowledgeBasesKbidDocuments403, PostV1KnowledgeBasesKbidDocuments404, PostV1KnowledgeBasesKbidDocuments413 } from "../../../../../../packages/types/kubb/PostV1KnowledgeBasesKbidDocuments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1KnowledgeBasesKbidDocumentsMutationKey = () => [{ url: '/v1/knowledge-bases/:kbId/documents/' }] as const

export type PostV1KnowledgeBasesKbidDocumentsMutationKey = ReturnType<typeof postV1KnowledgeBasesKbidDocumentsMutationKey>

/**
 * @description Upload a document (PDF, TXT, MD) to be parsed and added to the knowledge base
 * @summary Upload document to knowledge base
 * {@link /v1/knowledge-bases/:kbId/documents/}
 */
export async function postV1KnowledgeBasesKbidDocuments(kbId: PostV1KnowledgeBasesKbidDocumentsPathParams["kbId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1KnowledgeBasesKbidDocumentsMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidDocuments400 | PostV1KnowledgeBasesKbidDocuments401 | PostV1KnowledgeBasesKbidDocuments403 | PostV1KnowledgeBasesKbidDocuments404 | PostV1KnowledgeBasesKbidDocuments413>, unknown>({ method : "POST", url : `/v1/knowledge-bases/${kbId}/documents/`, ... requestConfig })  
  return res.data
}

/**
 * @description Upload a document (PDF, TXT, MD) to be parsed and added to the knowledge base
 * @summary Upload document to knowledge base
 * {@link /v1/knowledge-bases/:kbId/documents/}
 */
export function usePostV1KnowledgeBasesKbidDocuments<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1KnowledgeBasesKbidDocumentsMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidDocuments400 | PostV1KnowledgeBasesKbidDocuments401 | PostV1KnowledgeBasesKbidDocuments403 | PostV1KnowledgeBasesKbidDocuments404 | PostV1KnowledgeBasesKbidDocuments413>, {kbId: PostV1KnowledgeBasesKbidDocumentsPathParams["kbId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1KnowledgeBasesKbidDocumentsMutationKey()

  return useMutation<PostV1KnowledgeBasesKbidDocumentsMutationResponse, ResponseErrorConfig<PostV1KnowledgeBasesKbidDocuments400 | PostV1KnowledgeBasesKbidDocuments401 | PostV1KnowledgeBasesKbidDocuments403 | PostV1KnowledgeBasesKbidDocuments404 | PostV1KnowledgeBasesKbidDocuments413>, {kbId: PostV1KnowledgeBasesKbidDocumentsPathParams["kbId"]}, TContext>({
    mutationFn: async({ kbId }) => {
      return postV1KnowledgeBasesKbidDocuments(kbId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}