/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1ChallengesChallengeidWorkSessionsQueryResponse, GetV1ChallengesChallengeidWorkSessionsPathParams, GetV1ChallengesChallengeidWorkSessionsQueryParams, GetV1ChallengesChallengeidWorkSessions401, GetV1ChallengesChallengeidWorkSessions403, GetV1ChallengesChallengeidWorkSessions404 } from "../../../../../../packages/types/kubb/GetV1ChallengesChallengeidWorkSessions.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ChallengesChallengeidWorkSessionsQueryKey = (challengeId: GetV1ChallengesChallengeidWorkSessionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidWorkSessionsQueryParams) => [{ url: '/v1/challenges/:challengeId/work-sessions/', params: {challengeId:challengeId} }, ...(params ? [params] : [])] as const

export type GetV1ChallengesChallengeidWorkSessionsQueryKey = ReturnType<typeof getV1ChallengesChallengeidWorkSessionsQueryKey>

/**
 * @description Paginated list of student work sessions for a challenge. Teachers: own challenges only. Coordinators/admins: any.
 * @summary List work sessions for challenge (staff)
 * {@link /v1/challenges/:challengeId/work-sessions/}
 */
export async function getV1ChallengesChallengeidWorkSessions(challengeId: GetV1ChallengesChallengeidWorkSessionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidWorkSessionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesChallengeidWorkSessionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidWorkSessions401 | GetV1ChallengesChallengeidWorkSessions403 | GetV1ChallengesChallengeidWorkSessions404>, unknown>({ method : "GET", url : `/v1/challenges/${challengeId}/work-sessions/`, params, ... requestConfig })  
  return res.data
}

export function getV1ChallengesChallengeidWorkSessionsQueryOptions(challengeId: GetV1ChallengesChallengeidWorkSessionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidWorkSessionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesChallengeidWorkSessionsQueryKey(challengeId, params)
  return queryOptions<GetV1ChallengesChallengeidWorkSessionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidWorkSessions401 | GetV1ChallengesChallengeidWorkSessions403 | GetV1ChallengesChallengeidWorkSessions404>, GetV1ChallengesChallengeidWorkSessionsQueryResponse, typeof queryKey>({
   enabled: !!(challengeId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesChallengeidWorkSessions(challengeId, params, config)
   },
  })
}

/**
 * @description Paginated list of student work sessions for a challenge. Teachers: own challenges only. Coordinators/admins: any.
 * @summary List work sessions for challenge (staff)
 * {@link /v1/challenges/:challengeId/work-sessions/}
 */
export function useGetV1ChallengesChallengeidWorkSessions<TData = GetV1ChallengesChallengeidWorkSessionsQueryResponse, TQueryData = GetV1ChallengesChallengeidWorkSessionsQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesChallengeidWorkSessionsQueryKey>(challengeId: GetV1ChallengesChallengeidWorkSessionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidWorkSessionsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetV1ChallengesChallengeidWorkSessionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidWorkSessions401 | GetV1ChallengesChallengeidWorkSessions403 | GetV1ChallengesChallengeidWorkSessions404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesChallengeidWorkSessionsQueryKey(challengeId, params)

  const query = useQuery({
   ...getV1ChallengesChallengeidWorkSessionsQueryOptions(challengeId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesChallengeidWorkSessions401 | GetV1ChallengesChallengeidWorkSessions403 | GetV1ChallengesChallengeidWorkSessions404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}