export type { DeleteV1ChallengesIdMutationKey } from "./useDeleteV1ChallengesId.ts";
export type { GetV1ChallengesQueryKey } from "./useGetV1Challenges.ts";
export type { GetV1ChallengesIdQueryKey } from "./useGetV1ChallengesId.ts";
export type { GetV1ChallengesIdSuspenseQueryKey } from "./useGetV1ChallengesIdSuspense.ts";
export type { GetV1ChallengesSuspenseQueryKey } from "./useGetV1ChallengesSuspense.ts";
export type { PostV1ChallengesMutationKey } from "./usePostV1Challenges.ts";
export type { PutV1ChallengesIdMutationKey } from "./usePutV1ChallengesId.ts";
export { deleteV1ChallengesIdMutationKey, deleteV1ChallengesId, useDeleteV1ChallengesId } from "./useDeleteV1ChallengesId.ts";
export { getV1ChallengesQueryKey, getV1Challenges, getV1ChallengesQueryOptions, useGetV1Challenges } from "./useGetV1Challenges.ts";
export { getV1ChallengesIdQueryKey, getV1ChallengesId, getV1ChallengesIdQueryOptions, useGetV1ChallengesId } from "./useGetV1ChallengesId.ts";
export { getV1ChallengesIdSuspenseQueryKey, getV1ChallengesIdSuspense, getV1ChallengesIdSuspenseQueryOptions, useGetV1ChallengesIdSuspense } from "./useGetV1ChallengesIdSuspense.ts";
export { getV1ChallengesSuspenseQueryKey, getV1ChallengesSuspense, getV1ChallengesSuspenseQueryOptions, useGetV1ChallengesSuspense } from "./useGetV1ChallengesSuspense.ts";
export { postV1ChallengesMutationKey, postV1Challenges, usePostV1Challenges } from "./usePostV1Challenges.ts";
export { putV1ChallengesIdMutationKey, putV1ChallengesId, usePutV1ChallengesId } from "./usePutV1ChallengesId.ts";