/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PatchV1ChallengesIdMutationRequest, PatchV1ChallengesIdMutationResponse, PatchV1ChallengesIdPathParams, PatchV1ChallengesId400, PatchV1ChallengesId401, PatchV1ChallengesId403, PatchV1ChallengesId404 } from "../../../../../../packages/types/kubb/PatchV1ChallengesId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const patchV1ChallengesIdMutationKey = () => [{ url: '/v1/challenges/:id' }] as const

export type PatchV1ChallengesIdMutationKey = ReturnType<typeof patchV1ChallengesIdMutationKey>

/**
 * @description Update challenge content (title, description, difficulty, tags, possibleSolutions) and/or assign to a classroom. Teacher: only own challenges. Coordinator/admin: any challenge in their org. Classroom reassignment additionally requires coordinator+ or being the classroom lead teacher.
 * @summary Update challenge
 * {@link /v1/challenges/:id}
 */
export async function patchV1ChallengesId(id: PatchV1ChallengesIdPathParams["id"], data?: PatchV1ChallengesIdMutationRequest, config: Partial<RequestConfig<PatchV1ChallengesIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PatchV1ChallengesIdMutationResponse, ResponseErrorConfig<PatchV1ChallengesId400 | PatchV1ChallengesId401 | PatchV1ChallengesId403 | PatchV1ChallengesId404>, PatchV1ChallengesIdMutationRequest>({ method : "PATCH", url : `/v1/challenges/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Update challenge content (title, description, difficulty, tags, possibleSolutions) and/or assign to a classroom. Teacher: only own challenges. Coordinator/admin: any challenge in their org. Classroom reassignment additionally requires coordinator+ or being the classroom lead teacher.
 * @summary Update challenge
 * {@link /v1/challenges/:id}
 */
export function usePatchV1ChallengesId<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchV1ChallengesIdMutationResponse, ResponseErrorConfig<PatchV1ChallengesId400 | PatchV1ChallengesId401 | PatchV1ChallengesId403 | PatchV1ChallengesId404>, {id: PatchV1ChallengesIdPathParams["id"], data?: PatchV1ChallengesIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchV1ChallengesIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? patchV1ChallengesIdMutationKey()

  return useMutation<PatchV1ChallengesIdMutationResponse, ResponseErrorConfig<PatchV1ChallengesId400 | PatchV1ChallengesId401 | PatchV1ChallengesId403 | PatchV1ChallengesId404>, {id: PatchV1ChallengesIdPathParams["id"], data?: PatchV1ChallengesIdMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return patchV1ChallengesId(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}