/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, GetV1ChallengesChallengeidKnowledgeBasesPathParams, GetV1ChallengesChallengeidKnowledgeBases401, GetV1ChallengesChallengeidKnowledgeBases403, GetV1ChallengesChallengeidKnowledgeBases404 } from "../../../../../../packages/types/kubb/GetV1ChallengesChallengeidKnowledgeBases.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey = (challengeId: GetV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"]) => [{ url: '/v1/challenges/:challengeId/knowledge-bases/', params: {challengeId:challengeId} }] as const

export type GetV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey = ReturnType<typeof getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey>

/**
 * @description List all knowledge bases associated with a challenge, including document counts.
 * @summary List knowledge bases linked to challenge
 * {@link /v1/challenges/:challengeId/knowledge-bases/}
 */
export async function getV1ChallengesChallengeidKnowledgeBasesSuspense(challengeId: GetV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBases401 | GetV1ChallengesChallengeidKnowledgeBases403 | GetV1ChallengesChallengeidKnowledgeBases404>, unknown>({ method : "GET", url : `/v1/challenges/${challengeId}/knowledge-bases/`, ... requestConfig })  
  return res.data
}

export function getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryOptions(challengeId: GetV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey(challengeId)
  return queryOptions<GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBases401 | GetV1ChallengesChallengeidKnowledgeBases403 | GetV1ChallengesChallengeidKnowledgeBases404>, GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, typeof queryKey>({
   enabled: !!(challengeId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesChallengeidKnowledgeBasesSuspense(challengeId, config)
   },
  })
}

/**
 * @description List all knowledge bases associated with a challenge, including document counts.
 * @summary List knowledge bases linked to challenge
 * {@link /v1/challenges/:challengeId/knowledge-bases/}
 */
export function useGetV1ChallengesChallengeidKnowledgeBasesSuspense<TData = GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey>(challengeId: GetV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1ChallengesChallengeidKnowledgeBasesQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBases401 | GetV1ChallengesChallengeidKnowledgeBases403 | GetV1ChallengesChallengeidKnowledgeBases404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryKey(challengeId)

  const query = useSuspenseQuery({
   ...getV1ChallengesChallengeidKnowledgeBasesSuspenseQueryOptions(challengeId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBases401 | GetV1ChallengesChallengeidKnowledgeBases403 | GetV1ChallengesChallengeidKnowledgeBases404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}