/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams, GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams, GetV1ChallengesChallengeidKnowledgeBasesSearch401, GetV1ChallengesChallengeidKnowledgeBasesSearch403, GetV1ChallengesChallengeidKnowledgeBasesSearch404, GetV1ChallengesChallengeidKnowledgeBasesSearch503 } from "../../../../../../packages/types/kubb/GetV1ChallengesChallengeidKnowledgeBasesSearch.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ChallengesChallengeidKnowledgeBasesSearchQueryKey = (challengeId: GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams["challengeId"], params: GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams) => [{ url: '/v1/challenges/:challengeId/knowledge-bases/search', params: {challengeId:challengeId} }, ...(params ? [params] : [])] as const

export type GetV1ChallengesChallengeidKnowledgeBasesSearchQueryKey = ReturnType<typeof getV1ChallengesChallengeidKnowledgeBasesSearchQueryKey>

/**
 * @description Search across all knowledge bases linked to a challenge using semantic similarity.
 * @summary Semantic search across challenge knowledge bases
 * {@link /v1/challenges/:challengeId/knowledge-bases/search}
 */
export async function getV1ChallengesChallengeidKnowledgeBasesSearch(challengeId: GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams["challengeId"], params: GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBasesSearch401 | GetV1ChallengesChallengeidKnowledgeBasesSearch403 | GetV1ChallengesChallengeidKnowledgeBasesSearch404 | GetV1ChallengesChallengeidKnowledgeBasesSearch503>, unknown>({ method : "GET", url : `/v1/challenges/${challengeId}/knowledge-bases/search`, params, ... requestConfig })  
  return res.data
}

export function getV1ChallengesChallengeidKnowledgeBasesSearchQueryOptions(challengeId: GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams["challengeId"], params: GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesChallengeidKnowledgeBasesSearchQueryKey(challengeId, params)
  return queryOptions<GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBasesSearch401 | GetV1ChallengesChallengeidKnowledgeBasesSearch403 | GetV1ChallengesChallengeidKnowledgeBasesSearch404 | GetV1ChallengesChallengeidKnowledgeBasesSearch503>, GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, typeof queryKey>({
   enabled: !!(challengeId&& params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesChallengeidKnowledgeBasesSearch(challengeId, params, config)
   },
  })
}

/**
 * @description Search across all knowledge bases linked to a challenge using semantic similarity.
 * @summary Semantic search across challenge knowledge bases
 * {@link /v1/challenges/:challengeId/knowledge-bases/search}
 */
export function useGetV1ChallengesChallengeidKnowledgeBasesSearch<TData = GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, TQueryData = GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesChallengeidKnowledgeBasesSearchQueryKey>(challengeId: GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams["challengeId"], params: GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBasesSearch401 | GetV1ChallengesChallengeidKnowledgeBasesSearch403 | GetV1ChallengesChallengeidKnowledgeBasesSearch404 | GetV1ChallengesChallengeidKnowledgeBasesSearch503>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesChallengeidKnowledgeBasesSearchQueryKey(challengeId, params)

  const query = useQuery({
   ...getV1ChallengesChallengeidKnowledgeBasesSearchQueryOptions(challengeId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesChallengeidKnowledgeBasesSearch401 | GetV1ChallengesChallengeidKnowledgeBasesSearch403 | GetV1ChallengesChallengeidKnowledgeBasesSearch404 | GetV1ChallengesChallengeidKnowledgeBasesSearch503>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}