/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1ChallengesChallengeidKnowledgeBasesMutationRequest, PostV1ChallengesChallengeidKnowledgeBasesMutationResponse, PostV1ChallengesChallengeidKnowledgeBasesPathParams, PostV1ChallengesChallengeidKnowledgeBases400, PostV1ChallengesChallengeidKnowledgeBases401, PostV1ChallengesChallengeidKnowledgeBases403, PostV1ChallengesChallengeidKnowledgeBases404, PostV1ChallengesChallengeidKnowledgeBases409 } from "../../../../../../packages/types/kubb/PostV1ChallengesChallengeidKnowledgeBases.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1ChallengesChallengeidKnowledgeBasesMutationKey = () => [{ url: '/v1/challenges/:challengeId/knowledge-bases/' }] as const

export type PostV1ChallengesChallengeidKnowledgeBasesMutationKey = ReturnType<typeof postV1ChallengesChallengeidKnowledgeBasesMutationKey>

/**
 * @description Associate a knowledge base with a challenge. Both must belong to the same classroom.
 * @summary Link knowledge base to challenge
 * {@link /v1/challenges/:challengeId/knowledge-bases/}
 */
export async function postV1ChallengesChallengeidKnowledgeBases(challengeId: PostV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], data: PostV1ChallengesChallengeidKnowledgeBasesMutationRequest, config: Partial<RequestConfig<PostV1ChallengesChallengeidKnowledgeBasesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1ChallengesChallengeidKnowledgeBasesMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidKnowledgeBases400 | PostV1ChallengesChallengeidKnowledgeBases401 | PostV1ChallengesChallengeidKnowledgeBases403 | PostV1ChallengesChallengeidKnowledgeBases404 | PostV1ChallengesChallengeidKnowledgeBases409>, PostV1ChallengesChallengeidKnowledgeBasesMutationRequest>({ method : "POST", url : `/v1/challenges/${challengeId}/knowledge-bases/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Associate a knowledge base with a challenge. Both must belong to the same classroom.
 * @summary Link knowledge base to challenge
 * {@link /v1/challenges/:challengeId/knowledge-bases/}
 */
export function usePostV1ChallengesChallengeidKnowledgeBases<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ChallengesChallengeidKnowledgeBasesMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidKnowledgeBases400 | PostV1ChallengesChallengeidKnowledgeBases401 | PostV1ChallengesChallengeidKnowledgeBases403 | PostV1ChallengesChallengeidKnowledgeBases404 | PostV1ChallengesChallengeidKnowledgeBases409>, {challengeId: PostV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], data: PostV1ChallengesChallengeidKnowledgeBasesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1ChallengesChallengeidKnowledgeBasesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ChallengesChallengeidKnowledgeBasesMutationKey()

  return useMutation<PostV1ChallengesChallengeidKnowledgeBasesMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidKnowledgeBases400 | PostV1ChallengesChallengeidKnowledgeBases401 | PostV1ChallengesChallengeidKnowledgeBases403 | PostV1ChallengesChallengeidKnowledgeBases404 | PostV1ChallengesChallengeidKnowledgeBases409>, {challengeId: PostV1ChallengesChallengeidKnowledgeBasesPathParams["challengeId"], data: PostV1ChallengesChallengeidKnowledgeBasesMutationRequest}, TContext>({
    mutationFn: async({ challengeId, data }) => {
      return postV1ChallengesChallengeidKnowledgeBases(challengeId, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}