/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1InternalSubmissionsExerciseidRecentQueryResponse, GetV1InternalSubmissionsExerciseidRecentPathParams, GetV1InternalSubmissionsExerciseidRecentQueryParams } from "../../../../../../packages/types/kubb/GetV1InternalSubmissionsExerciseidRecent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1InternalSubmissionsExerciseidRecentQueryKey = (exerciseId: GetV1InternalSubmissionsExerciseidRecentPathParams["exerciseId"], params?: GetV1InternalSubmissionsExerciseidRecentQueryParams) => [{ url: '/v1/internal/submissions/:exerciseId/recent', params: {exerciseId:exerciseId} }, ...(params ? [params] : [])] as const

export type GetV1InternalSubmissionsExerciseidRecentQueryKey = ReturnType<typeof getV1InternalSubmissionsExerciseidRecentQueryKey>

/**
 * @description Get recent submissions for exercise (Internal - AI Service only)
 * {@link /v1/internal/submissions/:exerciseId/recent}
 */
export async function getV1InternalSubmissionsExerciseidRecent(exerciseId: GetV1InternalSubmissionsExerciseidRecentPathParams["exerciseId"], params?: GetV1InternalSubmissionsExerciseidRecentQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1InternalSubmissionsExerciseidRecentQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/internal/submissions/${exerciseId}/recent`, params, ... requestConfig })  
  return res.data
}

export function getV1InternalSubmissionsExerciseidRecentQueryOptions(exerciseId: GetV1InternalSubmissionsExerciseidRecentPathParams["exerciseId"], params?: GetV1InternalSubmissionsExerciseidRecentQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1InternalSubmissionsExerciseidRecentQueryKey(exerciseId, params)
  return queryOptions<GetV1InternalSubmissionsExerciseidRecentQueryResponse, ResponseErrorConfig<Error>, GetV1InternalSubmissionsExerciseidRecentQueryResponse, typeof queryKey>({
   enabled: !!(exerciseId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1InternalSubmissionsExerciseidRecent(exerciseId, params, config)
   },
  })
}

/**
 * @description Get recent submissions for exercise (Internal - AI Service only)
 * {@link /v1/internal/submissions/:exerciseId/recent}
 */
export function useGetV1InternalSubmissionsExerciseidRecent<TData = GetV1InternalSubmissionsExerciseidRecentQueryResponse, TQueryData = GetV1InternalSubmissionsExerciseidRecentQueryResponse, TQueryKey extends QueryKey = GetV1InternalSubmissionsExerciseidRecentQueryKey>(exerciseId: GetV1InternalSubmissionsExerciseidRecentPathParams["exerciseId"], params?: GetV1InternalSubmissionsExerciseidRecentQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetV1InternalSubmissionsExerciseidRecentQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1InternalSubmissionsExerciseidRecentQueryKey(exerciseId, params)

  const query = useQuery({
   ...getV1InternalSubmissionsExerciseidRecentQueryOptions(exerciseId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}