/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1InternalExercisesIdQueryResponse, GetV1InternalExercisesIdPathParams, GetV1InternalExercisesId404 } from "../../../../../../packages/types/kubb/GetV1InternalExercisesId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1InternalExercisesIdSuspenseQueryKey = (id: GetV1InternalExercisesIdPathParams["id"]) => [{ url: '/v1/internal/exercises/:id', params: {id:id} }] as const

export type GetV1InternalExercisesIdSuspenseQueryKey = ReturnType<typeof getV1InternalExercisesIdSuspenseQueryKey>

/**
 * @description Get exercise by ID (Internal - AI Service only)
 * {@link /v1/internal/exercises/:id}
 */
export async function getV1InternalExercisesIdSuspense(id: GetV1InternalExercisesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1InternalExercisesIdQueryResponse, ResponseErrorConfig<GetV1InternalExercisesId404>, unknown>({ method : "GET", url : `/v1/internal/exercises/${id}`, ... requestConfig })  
  return res.data
}

export function getV1InternalExercisesIdSuspenseQueryOptions(id: GetV1InternalExercisesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1InternalExercisesIdSuspenseQueryKey(id)
  return queryOptions<GetV1InternalExercisesIdQueryResponse, ResponseErrorConfig<GetV1InternalExercisesId404>, GetV1InternalExercisesIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1InternalExercisesIdSuspense(id, config)
   },
  })
}

/**
 * @description Get exercise by ID (Internal - AI Service only)
 * {@link /v1/internal/exercises/:id}
 */
export function useGetV1InternalExercisesIdSuspense<TData = GetV1InternalExercisesIdQueryResponse, TQueryKey extends QueryKey = GetV1InternalExercisesIdSuspenseQueryKey>(id: GetV1InternalExercisesIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1InternalExercisesIdQueryResponse, ResponseErrorConfig<GetV1InternalExercisesId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1InternalExercisesIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getV1InternalExercisesIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1InternalExercisesId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}