/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1ClassroomsIdMutationResponse, DeleteV1ClassroomsIdPathParams, DeleteV1ClassroomsId401, DeleteV1ClassroomsId403, DeleteV1ClassroomsId404 } from "../../../../../../packages/types/kubb/DeleteV1ClassroomsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1ClassroomsIdMutationKey = () => [{ url: '/v1/classrooms/:id/' }] as const

export type DeleteV1ClassroomsIdMutationKey = ReturnType<typeof deleteV1ClassroomsIdMutationKey>

/**
 * @description Soft delete a classroom. Requires coordinator or admin role.
 * @summary Delete classroom (soft delete)
 * {@link /v1/classrooms/:id/}
 */
export async function deleteV1ClassroomsId(id: DeleteV1ClassroomsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1ClassroomsIdMutationResponse, ResponseErrorConfig<DeleteV1ClassroomsId401 | DeleteV1ClassroomsId403 | DeleteV1ClassroomsId404>, unknown>({ method : "DELETE", url : `/v1/classrooms/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * @description Soft delete a classroom. Requires coordinator or admin role.
 * @summary Delete classroom (soft delete)
 * {@link /v1/classrooms/:id/}
 */
export function useDeleteV1ClassroomsId<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1ClassroomsIdMutationResponse, ResponseErrorConfig<DeleteV1ClassroomsId401 | DeleteV1ClassroomsId403 | DeleteV1ClassroomsId404>, {id: DeleteV1ClassroomsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1ClassroomsIdMutationKey()

  return useMutation<DeleteV1ClassroomsIdMutationResponse, ResponseErrorConfig<DeleteV1ClassroomsId401 | DeleteV1ClassroomsId403 | DeleteV1ClassroomsId404>, {id: DeleteV1ClassroomsIdPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return deleteV1ClassroomsId(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}