/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1ClassroomsQueryResponse, GetV1ClassroomsQueryParams, GetV1Classrooms400, GetV1Classrooms401 } from "../../../../../../packages/types/kubb/GetV1Classrooms.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ClassroomsSuspenseQueryKey = (params?: GetV1ClassroomsQueryParams) => [{ url: '/v1/classrooms/' }, ...(params ? [params] : [])] as const

export type GetV1ClassroomsSuspenseQueryKey = ReturnType<typeof getV1ClassroomsSuspenseQueryKey>

/**
 * @description List classrooms. scope=mine: user's enrolled or lead teacher; scope=org: from active org; scope=all: all non-deleted.
 * @summary List classrooms
 * {@link /v1/classrooms/}
 */
export async function getV1ClassroomsSuspense(params?: GetV1ClassroomsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ClassroomsQueryResponse, ResponseErrorConfig<GetV1Classrooms400 | GetV1Classrooms401>, unknown>({ method : "GET", url : `/v1/classrooms/`, params, ... requestConfig })  
  return res.data
}

export function getV1ClassroomsSuspenseQueryOptions(params?: GetV1ClassroomsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ClassroomsSuspenseQueryKey(params)
  return queryOptions<GetV1ClassroomsQueryResponse, ResponseErrorConfig<GetV1Classrooms400 | GetV1Classrooms401>, GetV1ClassroomsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ClassroomsSuspense(params, config)
   },
  })
}

/**
 * @description List classrooms. scope=mine: user's enrolled or lead teacher; scope=org: from active org; scope=all: all non-deleted.
 * @summary List classrooms
 * {@link /v1/classrooms/}
 */
export function useGetV1ClassroomsSuspense<TData = GetV1ClassroomsQueryResponse, TQueryKey extends QueryKey = GetV1ClassroomsSuspenseQueryKey>(params?: GetV1ClassroomsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1ClassroomsQueryResponse, ResponseErrorConfig<GetV1Classrooms400 | GetV1Classrooms401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ClassroomsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1ClassroomsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1Classrooms400 | GetV1Classrooms401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}