/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1ClassroomsIdUnenrollMutationRequest, PostV1ClassroomsIdUnenrollMutationResponse, PostV1ClassroomsIdUnenrollPathParams, PostV1ClassroomsIdUnenroll400, PostV1ClassroomsIdUnenroll401, PostV1ClassroomsIdUnenroll403, PostV1ClassroomsIdUnenroll404 } from "../../../../../../packages/types/kubb/PostV1ClassroomsIdUnenroll.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1ClassroomsIdUnenrollMutationKey = () => [{ url: '/v1/classrooms/:id/unenroll' }] as const

export type PostV1ClassroomsIdUnenrollMutationKey = ReturnType<typeof postV1ClassroomsIdUnenrollMutationKey>

/**
 * @description Remove a user from a classroom. If userId is omitted, unenrolls the current user. Teachers+ can unenroll others.
 * @summary Unenroll from classroom
 * {@link /v1/classrooms/:id/unenroll}
 */
export async function postV1ClassroomsIdUnenroll(id: PostV1ClassroomsIdUnenrollPathParams["id"], data?: PostV1ClassroomsIdUnenrollMutationRequest, config: Partial<RequestConfig<PostV1ClassroomsIdUnenrollMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1ClassroomsIdUnenrollMutationResponse, ResponseErrorConfig<PostV1ClassroomsIdUnenroll400 | PostV1ClassroomsIdUnenroll401 | PostV1ClassroomsIdUnenroll403 | PostV1ClassroomsIdUnenroll404>, PostV1ClassroomsIdUnenrollMutationRequest>({ method : "POST", url : `/v1/classrooms/${id}/unenroll`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Remove a user from a classroom. If userId is omitted, unenrolls the current user. Teachers+ can unenroll others.
 * @summary Unenroll from classroom
 * {@link /v1/classrooms/:id/unenroll}
 */
export function usePostV1ClassroomsIdUnenroll<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ClassroomsIdUnenrollMutationResponse, ResponseErrorConfig<PostV1ClassroomsIdUnenroll400 | PostV1ClassroomsIdUnenroll401 | PostV1ClassroomsIdUnenroll403 | PostV1ClassroomsIdUnenroll404>, {id: PostV1ClassroomsIdUnenrollPathParams["id"], data?: PostV1ClassroomsIdUnenrollMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1ClassroomsIdUnenrollMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ClassroomsIdUnenrollMutationKey()

  return useMutation<PostV1ClassroomsIdUnenrollMutationResponse, ResponseErrorConfig<PostV1ClassroomsIdUnenroll400 | PostV1ClassroomsIdUnenroll401 | PostV1ClassroomsIdUnenroll403 | PostV1ClassroomsIdUnenroll404>, {id: PostV1ClassroomsIdUnenrollPathParams["id"], data?: PostV1ClassroomsIdUnenrollMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1ClassroomsIdUnenroll(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}