/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1ClassroomsMutationRequest, PostV1ClassroomsMutationResponse, PostV1Classrooms400, PostV1Classrooms401, PostV1Classrooms403 } from "../../../../../../packages/types/kubb/PostV1Classrooms.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1ClassroomsMutationKey = () => [{ url: '/v1/classrooms/' }] as const

export type PostV1ClassroomsMutationKey = ReturnType<typeof postV1ClassroomsMutationKey>

/**
 * @description Create a new classroom. Requires teacher+ role and membership in the organization.
 * @summary Create classroom
 * {@link /v1/classrooms/}
 */
export async function postV1Classrooms(data: PostV1ClassroomsMutationRequest, config: Partial<RequestConfig<PostV1ClassroomsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1ClassroomsMutationResponse, ResponseErrorConfig<PostV1Classrooms400 | PostV1Classrooms401 | PostV1Classrooms403>, PostV1ClassroomsMutationRequest>({ method : "POST", url : `/v1/classrooms/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Create a new classroom. Requires teacher+ role and membership in the organization.
 * @summary Create classroom
 * {@link /v1/classrooms/}
 */
export function usePostV1Classrooms<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ClassroomsMutationResponse, ResponseErrorConfig<PostV1Classrooms400 | PostV1Classrooms401 | PostV1Classrooms403>, {data: PostV1ClassroomsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1ClassroomsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ClassroomsMutationKey()

  return useMutation<PostV1ClassroomsMutationResponse, ResponseErrorConfig<PostV1Classrooms400 | PostV1Classrooms401 | PostV1Classrooms403>, {data: PostV1ClassroomsMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1Classrooms(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}