/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1ChallengesChallengeidKnowledgeBasesKbidPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    challengeId: string;
    /**
     * @minLength 1
     * @type string
    */
    kbId: string;
};

export const deleteV1ChallengesChallengeidKnowledgeBasesKbid204SuccessEnum = {
    "true": true
} as const;

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid204SuccessEnum = (typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid204SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid204SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid204 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidKnowledgeBasesKbid204SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
};

export const deleteV1ChallengesChallengeidKnowledgeBasesKbid401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid401SuccessEnum = (typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid401SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid401 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidKnowledgeBasesKbid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesChallengeidKnowledgeBasesKbid403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid403SuccessEnum = (typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid403SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid403 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidKnowledgeBasesKbid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesChallengeidKnowledgeBasesKbid404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid404SuccessEnum = (typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid404SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidKnowledgeBasesKbid404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidKnowledgeBasesKbid404 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidKnowledgeBasesKbid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbidMutationResponse = DeleteV1ChallengesChallengeidKnowledgeBasesKbid204;

export type DeleteV1ChallengesChallengeidKnowledgeBasesKbidMutation = {
    Response: DeleteV1ChallengesChallengeidKnowledgeBasesKbid204;
    PathParams: DeleteV1ChallengesChallengeidKnowledgeBasesKbidPathParams;
    Errors: DeleteV1ChallengesChallengeidKnowledgeBasesKbid401 | DeleteV1ChallengesChallengeidKnowledgeBasesKbid403 | DeleteV1ChallengesChallengeidKnowledgeBasesKbid404;
};