/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1ChallengesIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const deleteV1ChallengesId204SuccessEnum = {
    "true": true
} as const;

export type DeleteV1ChallengesId204SuccessEnum = (typeof deleteV1ChallengesId204SuccessEnum)[keyof typeof deleteV1ChallengesId204SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesId204 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesId204SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
};

export const deleteV1ChallengesId401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesId401SuccessEnum = (typeof deleteV1ChallengesId401SuccessEnum)[keyof typeof deleteV1ChallengesId401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesId401 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesId403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesId403SuccessEnum = (typeof deleteV1ChallengesId403SuccessEnum)[keyof typeof deleteV1ChallengesId403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesId403 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesId404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesId404SuccessEnum = (typeof deleteV1ChallengesId404SuccessEnum)[keyof typeof deleteV1ChallengesId404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesId404 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1ChallengesIdMutationResponse = DeleteV1ChallengesId204;

export type DeleteV1ChallengesIdMutation = {
    Response: DeleteV1ChallengesId204;
    PathParams: DeleteV1ChallengesIdPathParams;
    Errors: DeleteV1ChallengesId401 | DeleteV1ChallengesId403 | DeleteV1ChallengesId404;
};