/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const deleteV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum = (typeof deleteV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum)[keyof typeof deleteV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum];

export type DeleteV1ChallengesChallengeidReferenceSolutionsKindPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    challengeId: string;
    /**
     * @type string
    */
    kind: DeleteV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum;
};

export const deleteV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum = {
    "true": true
} as const;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum = (typeof deleteV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum];

export const dataKindEnum3 = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type DataKindEnum3 = (typeof dataKindEnum3)[keyof typeof dataKindEnum3];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidReferenceSolutionsKind200 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        kind: DataKindEnum3;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const deleteV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum = (typeof deleteV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidReferenceSolutionsKind401 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum = (typeof deleteV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidReferenceSolutionsKind403 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum = (typeof deleteV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum)[keyof typeof deleteV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesChallengeidReferenceSolutionsKind404 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1ChallengesChallengeidReferenceSolutionsKindMutationResponse = DeleteV1ChallengesChallengeidReferenceSolutionsKind200;

export type DeleteV1ChallengesChallengeidReferenceSolutionsKindMutation = {
    Response: DeleteV1ChallengesChallengeidReferenceSolutionsKind200;
    PathParams: DeleteV1ChallengesChallengeidReferenceSolutionsKindPathParams;
    Errors: DeleteV1ChallengesChallengeidReferenceSolutionsKind401 | DeleteV1ChallengesChallengeidReferenceSolutionsKind403 | DeleteV1ChallengesChallengeidReferenceSolutionsKind404;
};