/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1ClassroomsIdPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const deleteV1ClassroomsId200SuccessEnum = {
    "true": true
} as const;

export type DeleteV1ClassroomsId200SuccessEnum = (typeof deleteV1ClassroomsId200SuccessEnum)[keyof typeof deleteV1ClassroomsId200SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ClassroomsId200 = {
    /**
     * @type boolean
    */
    success: DeleteV1ClassroomsId200SuccessEnum;
    /**
     * @type string
    */
    message: string;
};

export const deleteV1ClassroomsId401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ClassroomsId401SuccessEnum = (typeof deleteV1ClassroomsId401SuccessEnum)[keyof typeof deleteV1ClassroomsId401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ClassroomsId401 = {
    /**
     * @type boolean
    */
    success: DeleteV1ClassroomsId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ClassroomsId403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ClassroomsId403SuccessEnum = (typeof deleteV1ClassroomsId403SuccessEnum)[keyof typeof deleteV1ClassroomsId403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ClassroomsId403 = {
    /**
     * @type boolean
    */
    success: DeleteV1ClassroomsId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ClassroomsId404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ClassroomsId404SuccessEnum = (typeof deleteV1ClassroomsId404SuccessEnum)[keyof typeof deleteV1ClassroomsId404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ClassroomsId404 = {
    /**
     * @type boolean
    */
    success: DeleteV1ClassroomsId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1ClassroomsIdMutationResponse = DeleteV1ClassroomsId200;

export type DeleteV1ClassroomsIdMutation = {
    Response: DeleteV1ClassroomsId200;
    PathParams: DeleteV1ClassroomsIdPathParams;
    Errors: DeleteV1ClassroomsId401 | DeleteV1ClassroomsId403 | DeleteV1ClassroomsId404;
};