/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1KnowledgeBasesKbidPathParams = {
    /**
     * @type string, uuid
    */
    kbId: string;
};

export const deleteV1KnowledgeBasesKbid204SuccessEnum = {
    "true": true
} as const;

export type DeleteV1KnowledgeBasesKbid204SuccessEnum = (typeof deleteV1KnowledgeBasesKbid204SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbid204SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbid204 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbid204SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
};

export const deleteV1KnowledgeBasesKbid401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbid401SuccessEnum = (typeof deleteV1KnowledgeBasesKbid401SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbid401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbid401 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1KnowledgeBasesKbid403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbid403SuccessEnum = (typeof deleteV1KnowledgeBasesKbid403SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbid403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbid403 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1KnowledgeBasesKbid404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbid404SuccessEnum = (typeof deleteV1KnowledgeBasesKbid404SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbid404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbid404 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1KnowledgeBasesKbidMutationResponse = DeleteV1KnowledgeBasesKbid204;

export type DeleteV1KnowledgeBasesKbidMutation = {
    Response: DeleteV1KnowledgeBasesKbid204;
    PathParams: DeleteV1KnowledgeBasesKbidPathParams;
    Errors: DeleteV1KnowledgeBasesKbid401 | DeleteV1KnowledgeBasesKbid403 | DeleteV1KnowledgeBasesKbid404;
};