/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1KnowledgeBasesKbidEntriesEntryidPathParams = {
    /**
     * @type string, uuid
    */
    kbId: string;
    /**
     * @type string, uuid
    */
    entryId: string;
};

export const deleteV1KnowledgeBasesKbidEntriesEntryid204SuccessEnum = {
    "true": true
} as const;

export type DeleteV1KnowledgeBasesKbidEntriesEntryid204SuccessEnum = (typeof deleteV1KnowledgeBasesKbidEntriesEntryid204SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbidEntriesEntryid204SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbidEntriesEntryid204 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbidEntriesEntryid204SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
};

export const deleteV1KnowledgeBasesKbidEntriesEntryid401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbidEntriesEntryid401SuccessEnum = (typeof deleteV1KnowledgeBasesKbidEntriesEntryid401SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbidEntriesEntryid401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbidEntriesEntryid401 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbidEntriesEntryid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1KnowledgeBasesKbidEntriesEntryid403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbidEntriesEntryid403SuccessEnum = (typeof deleteV1KnowledgeBasesKbidEntriesEntryid403SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbidEntriesEntryid403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbidEntriesEntryid403 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbidEntriesEntryid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1KnowledgeBasesKbidEntriesEntryid404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1KnowledgeBasesKbidEntriesEntryid404SuccessEnum = (typeof deleteV1KnowledgeBasesKbidEntriesEntryid404SuccessEnum)[keyof typeof deleteV1KnowledgeBasesKbidEntriesEntryid404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1KnowledgeBasesKbidEntriesEntryid404 = {
    /**
     * @type boolean
    */
    success: DeleteV1KnowledgeBasesKbidEntriesEntryid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1KnowledgeBasesKbidEntriesEntryidMutationResponse = DeleteV1KnowledgeBasesKbidEntriesEntryid204;

export type DeleteV1KnowledgeBasesKbidEntriesEntryidMutation = {
    Response: DeleteV1KnowledgeBasesKbidEntriesEntryid204;
    PathParams: DeleteV1KnowledgeBasesKbidEntriesEntryidPathParams;
    Errors: DeleteV1KnowledgeBasesKbidEntriesEntryid401 | DeleteV1KnowledgeBasesKbidEntriesEntryid403 | DeleteV1KnowledgeBasesKbidEntriesEntryid404;
};