/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @type string, uuid
    */
    docId: string;
};

export const deleteV1ChallengesIdKnowledgeBaseDocumentsDocid204SuccessEnum = {
    "true": true
} as const;

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid204SuccessEnum = (typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid204SuccessEnum)[keyof typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid204SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid204 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid204SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
};

export const deleteV1ChallengesIdKnowledgeBaseDocumentsDocid401SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401SuccessEnum = (typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid401SuccessEnum)[keyof typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid401SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesIdKnowledgeBaseDocumentsDocid403SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403SuccessEnum = (typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid403SuccessEnum)[keyof typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid403SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const deleteV1ChallengesIdKnowledgeBaseDocumentsDocid404SuccessEnum = {
    "false": false
} as const;

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404SuccessEnum = (typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid404SuccessEnum)[keyof typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocid404SuccessEnum];

/**
 * @description Default Response
*/
export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404 = {
    /**
     * @type boolean
    */
    success: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationResponse = DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid204;

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutation = {
    Response: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid204;
    PathParams: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams;
    Errors: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404;
};