/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesChallengeidSubmissionsPathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
};

export type GetV1ChallengesChallengeidSubmissionsQueryParams = {
    /**
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 50
     * @default 20
     * @type number | undefined
    */
    perPage?: number;
};

export const getV1ChallengesChallengeidSubmissions200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesChallengeidSubmissions200SuccessEnum = (typeof getV1ChallengesChallengeidSubmissions200SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissions200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissions200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissions200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        submissionId: string;
        /**
         * @type string
        */
        workSessionId: string;
        /**
         * @type string
        */
        studentUserId: string | null;
        /**
         * @type string
        */
        studentName: string | null;
        /**
         * @type string
        */
        submittedAt: string;
        /**
         * @type string
        */
        grade: string | null;
        /**
         * @type string
        */
        autoReview: string | null;
        /**
         * @type string
        */
        autoReviewAt: string | null;
        /**
         * @type string
        */
        gradedAt: string | null;
    }[];
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesChallengeidSubmissions401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissions401SuccessEnum = (typeof getV1ChallengesChallengeidSubmissions401SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissions401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissions401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissions401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidSubmissions403SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissions403SuccessEnum = (typeof getV1ChallengesChallengeidSubmissions403SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissions403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissions403 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissions403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidSubmissions404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissions404SuccessEnum = (typeof getV1ChallengesChallengeidSubmissions404SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissions404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissions404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissions404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesChallengeidSubmissionsQueryResponse = GetV1ChallengesChallengeidSubmissions200;

export type GetV1ChallengesChallengeidSubmissionsQuery = {
    Response: GetV1ChallengesChallengeidSubmissions200;
    PathParams: GetV1ChallengesChallengeidSubmissionsPathParams;
    QueryParams: GetV1ChallengesChallengeidSubmissionsQueryParams;
    Errors: GetV1ChallengesChallengeidSubmissions401 | GetV1ChallengesChallengeidSubmissions403 | GetV1ChallengesChallengeidSubmissions404;
};