/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1OrganizationsIdMembersPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const getV1OrganizationsIdMembers200SuccessEnum = {
    "true": true
} as const;

export type GetV1OrganizationsIdMembers200SuccessEnum = (typeof getV1OrganizationsIdMembers200SuccessEnum)[keyof typeof getV1OrganizationsIdMembers200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdMembers200 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdMembers200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        userId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        email: string;
        /**
         * @type string
        */
        role: string;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1OrganizationsIdMembers401SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdMembers401SuccessEnum = (typeof getV1OrganizationsIdMembers401SuccessEnum)[keyof typeof getV1OrganizationsIdMembers401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdMembers401 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdMembers401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1OrganizationsIdMembers403SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdMembers403SuccessEnum = (typeof getV1OrganizationsIdMembers403SuccessEnum)[keyof typeof getV1OrganizationsIdMembers403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdMembers403 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdMembers403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1OrganizationsIdMembers404SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdMembers404SuccessEnum = (typeof getV1OrganizationsIdMembers404SuccessEnum)[keyof typeof getV1OrganizationsIdMembers404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdMembers404 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdMembers404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1OrganizationsIdMembersQueryResponse = GetV1OrganizationsIdMembers200;

export type GetV1OrganizationsIdMembersQuery = {
    Response: GetV1OrganizationsIdMembers200;
    PathParams: GetV1OrganizationsIdMembersPathParams;
    Errors: GetV1OrganizationsIdMembers401 | GetV1OrganizationsIdMembers403 | GetV1OrganizationsIdMembers404;
};