/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getV1UsersMe200SuccessEnum = {
    "true": true
} as const;

export type GetV1UsersMe200SuccessEnum = (typeof getV1UsersMe200SuccessEnum)[keyof typeof getV1UsersMe200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1UsersMe200 = {
    /**
     * @type boolean
    */
    success: GetV1UsersMe200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        email: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type boolean
        */
        emailVerified: boolean;
        /**
         * @type boolean
        */
        isActive: boolean;
        /**
         * @type string
        */
        role: string | null;
        /**
         * @type string
        */
        createdAt: string;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1UsersMe401SuccessEnum = {
    "false": false
} as const;

export type GetV1UsersMe401SuccessEnum = (typeof getV1UsersMe401SuccessEnum)[keyof typeof getV1UsersMe401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1UsersMe401 = {
    /**
     * @type boolean
    */
    success: GetV1UsersMe401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1UsersMeQueryResponse = GetV1UsersMe200;

export type GetV1UsersMeQuery = {
    Response: GetV1UsersMe200;
    Errors: GetV1UsersMe401;
};