/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const getV1ChallengesId200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesId200SuccessEnum = (typeof getV1ChallengesId200SuccessEnum)[keyof typeof getV1ChallengesId200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesId200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        difficulty: string | null;
        /**
         * @type array
        */
        tags: string[] | null;
        supportMaterials?: any;
        /**
         * @type string
        */
        author: string | null;
        /**
         * @type string
        */
        classroomTitle: string | null;
        /**
         * @type string
        */
        createdByUserId: string | null;
        /**
         * @type string
        */
        classroomId: string | null;
        /**
         * @type string
        */
        classroomTeacherUserId: string | null;
        /**
         * @type array
        */
        teachingAssistants: {
            /**
             * @type string
            */
            id: string;
            /**
             * @type string
            */
            alias: string;
            /**
             * @type boolean
            */
            isDefault: boolean;
        }[];
        /**
         * @type string
        */
        createdAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesId401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesId401SuccessEnum = (typeof getV1ChallengesId401SuccessEnum)[keyof typeof getV1ChallengesId401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesId401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesId404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesId404SuccessEnum = (typeof getV1ChallengesId404SuccessEnum)[keyof typeof getV1ChallengesId404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesId404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesIdQueryResponse = GetV1ChallengesId200;

export type GetV1ChallengesIdQuery = {
    Response: GetV1ChallengesId200;
    PathParams: GetV1ChallengesIdPathParams;
    Errors: GetV1ChallengesId401 | GetV1ChallengesId404;
};