/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1InternalSubmissionsExerciseidRecentPathParams = {
    /**
     * @type string
    */
    exerciseId: string;
};

export type GetV1InternalSubmissionsExerciseidRecentQueryParams = {
    /**
     * @default "10"
     * @type string | undefined
    */
    limit?: string;
};

export const getV1InternalSubmissionsExerciseidRecent200SuccessEnum = {
    "true": true
} as const;

export type GetV1InternalSubmissionsExerciseidRecent200SuccessEnum = (typeof getV1InternalSubmissionsExerciseidRecent200SuccessEnum)[keyof typeof getV1InternalSubmissionsExerciseidRecent200SuccessEnum];

export const dataStatusEnum = {
    "PENDING": "PENDING",
    "SUCCESS": "SUCCESS",
    "FAILED": "FAILED"
} as const;

export type DataStatusEnum = (typeof dataStatusEnum)[keyof typeof dataStatusEnum];

/**
 * @description Default Response
*/
export type GetV1InternalSubmissionsExerciseidRecent200 = {
    /**
     * @type boolean
    */
    success: GetV1InternalSubmissionsExerciseidRecent200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type number
        */
        id: number;
        /**
         * @type number
        */
        userId: number;
        /**
         * @type string
        */
        code: string;
        /**
         * @type string
        */
        status: DataStatusEnum;
        /**
         * @type string, date-time
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export type GetV1InternalSubmissionsExerciseidRecentQueryResponse = GetV1InternalSubmissionsExerciseidRecent200;

export type GetV1InternalSubmissionsExerciseidRecentQuery = {
    Response: GetV1InternalSubmissionsExerciseidRecent200;
    PathParams: GetV1InternalSubmissionsExerciseidRecentPathParams;
    QueryParams: GetV1InternalSubmissionsExerciseidRecentQueryParams;
    Errors: any;
};