/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1KnowledgeBasesKbidSearchPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    kbId: string;
};

export type GetV1KnowledgeBasesKbidSearchQueryParams = {
    /**
     * @minLength 1
     * @type string
    */
    q: string;
    /**
     * @minLength 1
     * @maxLength 50
     * @default 10
     * @type number | undefined
    */
    limit?: number;
};

export const getV1KnowledgeBasesKbidSearch200SuccessEnum = {
    "true": true
} as const;

export type GetV1KnowledgeBasesKbidSearch200SuccessEnum = (typeof getV1KnowledgeBasesKbidSearch200SuccessEnum)[keyof typeof getV1KnowledgeBasesKbidSearch200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbidSearch200 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbidSearch200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        content: string;
        /**
         * @type number
        */
        similarity: number;
        /**
         * @type object
        */
        metadata: {
            /**
             * @type array | undefined
            */
            titleHierarchy?: string[];
            /**
             * @type string | undefined
            */
            documentFilename?: string;
        } | null;
        /**
         * @type number
        */
        chunkIndex: number | null;
        /**
         * @type string
        */
        documentId: string | null;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1KnowledgeBasesKbidSearch401SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbidSearch401SuccessEnum = (typeof getV1KnowledgeBasesKbidSearch401SuccessEnum)[keyof typeof getV1KnowledgeBasesKbidSearch401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbidSearch401 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbidSearch401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBasesKbidSearch403SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbidSearch403SuccessEnum = (typeof getV1KnowledgeBasesKbidSearch403SuccessEnum)[keyof typeof getV1KnowledgeBasesKbidSearch403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbidSearch403 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbidSearch403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBasesKbidSearch404SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbidSearch404SuccessEnum = (typeof getV1KnowledgeBasesKbidSearch404SuccessEnum)[keyof typeof getV1KnowledgeBasesKbidSearch404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbidSearch404 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbidSearch404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBasesKbidSearch503SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbidSearch503SuccessEnum = (typeof getV1KnowledgeBasesKbidSearch503SuccessEnum)[keyof typeof getV1KnowledgeBasesKbidSearch503SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbidSearch503 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbidSearch503SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1KnowledgeBasesKbidSearchQueryResponse = GetV1KnowledgeBasesKbidSearch200;

export type GetV1KnowledgeBasesKbidSearchQuery = {
    Response: GetV1KnowledgeBasesKbidSearch200;
    PathParams: GetV1KnowledgeBasesKbidSearchPathParams;
    QueryParams: GetV1KnowledgeBasesKbidSearchQueryParams;
    Errors: GetV1KnowledgeBasesKbidSearch401 | GetV1KnowledgeBasesKbidSearch403 | GetV1KnowledgeBasesKbidSearch404 | GetV1KnowledgeBasesKbidSearch503;
};