/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1KnowledgeBasesQueryParams = {
    /**
     * @type string, uuid
    */
    classroomId: string;
    /**
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type number | undefined
    */
    perPage?: number;
};

export const getV1KnowledgeBases200SuccessEnum = {
    "true": true
} as const;

export type GetV1KnowledgeBases200SuccessEnum = (typeof getV1KnowledgeBases200SuccessEnum)[keyof typeof getV1KnowledgeBases200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBases200 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBases200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        classroomId: string;
        /**
         * @type number
        */
        documentCount: number;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1KnowledgeBases400SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBases400SuccessEnum = (typeof getV1KnowledgeBases400SuccessEnum)[keyof typeof getV1KnowledgeBases400SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBases400 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBases400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBases401SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBases401SuccessEnum = (typeof getV1KnowledgeBases401SuccessEnum)[keyof typeof getV1KnowledgeBases401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBases401 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBases401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1KnowledgeBasesQueryResponse = GetV1KnowledgeBases200;

export type GetV1KnowledgeBasesQuery = {
    Response: GetV1KnowledgeBases200;
    QueryParams: GetV1KnowledgeBasesQueryParams;
    Errors: GetV1KnowledgeBases400 | GetV1KnowledgeBases401;
};