/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChatTeacherHistoryClassroomidPathParams = {
    /**
     * @type string
    */
    classroomId: string;
};

export const getV1ChatTeacherHistoryClassroomid200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChatTeacherHistoryClassroomid200SuccessEnum = (typeof getV1ChatTeacherHistoryClassroomid200SuccessEnum)[keyof typeof getV1ChatTeacherHistoryClassroomid200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChatTeacherHistoryClassroomid200 = {
    /**
     * @type boolean
    */
    success: GetV1ChatTeacherHistoryClassroomid200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: any[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChatTeacherHistoryClassroomid401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChatTeacherHistoryClassroomid401SuccessEnum = (typeof getV1ChatTeacherHistoryClassroomid401SuccessEnum)[keyof typeof getV1ChatTeacherHistoryClassroomid401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChatTeacherHistoryClassroomid401 = {
    /**
     * @type boolean
    */
    success: GetV1ChatTeacherHistoryClassroomid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChatTeacherHistoryClassroomidQueryResponse = GetV1ChatTeacherHistoryClassroomid200;

export type GetV1ChatTeacherHistoryClassroomidQuery = {
    Response: GetV1ChatTeacherHistoryClassroomid200;
    PathParams: GetV1ChatTeacherHistoryClassroomidPathParams;
    Errors: GetV1ChatTeacherHistoryClassroomid401;
};