/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesChallengeidKnowledgeBasesPathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
};

export const getV1ChallengesChallengeidKnowledgeBases200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesChallengeidKnowledgeBases200SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBases200SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBases200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBases200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBases200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        classroomId: string;
        /**
         * @type number
        */
        documentCount: number;
        /**
         * @type string
        */
        linkedAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesChallengeidKnowledgeBases401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBases401SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBases401SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBases401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBases401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBases401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidKnowledgeBases403SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBases403SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBases403SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBases403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBases403 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBases403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidKnowledgeBases404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBases404SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBases404SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBases404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBases404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBases404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesChallengeidKnowledgeBasesQueryResponse = GetV1ChallengesChallengeidKnowledgeBases200;

export type GetV1ChallengesChallengeidKnowledgeBasesQuery = {
    Response: GetV1ChallengesChallengeidKnowledgeBases200;
    PathParams: GetV1ChallengesChallengeidKnowledgeBasesPathParams;
    Errors: GetV1ChallengesChallengeidKnowledgeBases401 | GetV1ChallengesChallengeidKnowledgeBases403 | GetV1ChallengesChallengeidKnowledgeBases404;
};