/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1KnowledgeBasesKbidPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    kbId: string;
};

export const getV1KnowledgeBasesKbid200SuccessEnum = {
    "true": true
} as const;

export type GetV1KnowledgeBasesKbid200SuccessEnum = (typeof getV1KnowledgeBasesKbid200SuccessEnum)[keyof typeof getV1KnowledgeBasesKbid200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbid200 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbid200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        classroomId: string;
        /**
         * @type string
        */
        organizationId: string;
        /**
         * @type string
        */
        createdByUserId: string | null;
        /**
         * @type string
        */
        createdAt: string;
        /**
         * @type string
        */
        updatedAt: string;
        /**
         * @type array
        */
        documents: {
            /**
             * @type string
            */
            id: string;
            /**
             * @type string
            */
            filename: string;
            /**
             * @type string
            */
            mimeType: string;
            /**
             * @type number
            */
            fileSize: number;
            /**
             * @type number
            */
            chunkCount: number;
            /**
             * @type string
            */
            status: string;
            /**
             * @type string
            */
            errorMessage: string | null;
            /**
             * @type string
            */
            errorStage: string | null;
            /**
             * @type string
            */
            createdAt: string;
        }[];
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1KnowledgeBasesKbid401SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbid401SuccessEnum = (typeof getV1KnowledgeBasesKbid401SuccessEnum)[keyof typeof getV1KnowledgeBasesKbid401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbid401 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBasesKbid403SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbid403SuccessEnum = (typeof getV1KnowledgeBasesKbid403SuccessEnum)[keyof typeof getV1KnowledgeBasesKbid403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbid403 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1KnowledgeBasesKbid404SuccessEnum = {
    "false": false
} as const;

export type GetV1KnowledgeBasesKbid404SuccessEnum = (typeof getV1KnowledgeBasesKbid404SuccessEnum)[keyof typeof getV1KnowledgeBasesKbid404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1KnowledgeBasesKbid404 = {
    /**
     * @type boolean
    */
    success: GetV1KnowledgeBasesKbid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1KnowledgeBasesKbidQueryResponse = GetV1KnowledgeBasesKbid200;

export type GetV1KnowledgeBasesKbidQuery = {
    Response: GetV1KnowledgeBasesKbid200;
    PathParams: GetV1KnowledgeBasesKbidPathParams;
    Errors: GetV1KnowledgeBasesKbid401 | GetV1KnowledgeBasesKbid403 | GetV1KnowledgeBasesKbid404;
};