/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getV1ChallengesQueryParamsScopeEnum = {
    "mine": "mine",
    "public": "public",
    "all": "all"
} as const;

export type GetV1ChallengesQueryParamsScopeEnum = (typeof getV1ChallengesQueryParamsScopeEnum)[keyof typeof getV1ChallengesQueryParamsScopeEnum];

export const getV1ChallengesQueryParamsDifficultyEnum = {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
} as const;

export type GetV1ChallengesQueryParamsDifficultyEnum = (typeof getV1ChallengesQueryParamsDifficultyEnum)[keyof typeof getV1ChallengesQueryParamsDifficultyEnum];

export type GetV1ChallengesQueryParams = {
    /**
     * @default "all"
     * @type string | undefined
    */
    scope?: GetV1ChallengesQueryParamsScopeEnum;
    /**
     * @minLength 1
     * @type string | undefined
    */
    classroomId?: string;
    /**
     * @type string | undefined
    */
    difficulty?: GetV1ChallengesQueryParamsDifficultyEnum;
    /**
     * @type string | undefined
    */
    tags?: string;
    /**
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type number | undefined
    */
    perPage?: number;
};

export const getV1Challenges200SuccessEnum = {
    "true": true
} as const;

export type GetV1Challenges200SuccessEnum = (typeof getV1Challenges200SuccessEnum)[keyof typeof getV1Challenges200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1Challenges200 = {
    /**
     * @type boolean
    */
    success: GetV1Challenges200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        difficulty: string | null;
        /**
         * @type array
        */
        tags: string[] | null;
        /**
         * @type string
        */
        author: string | null;
        /**
         * @type string
        */
        classroomTitle: string | null;
        /**
         * @type string
        */
        releaseAt: string | null;
        /**
         * @type string
        */
        dueAt: string | null;
        /**
         * @type string
        */
        latePolicy: string;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1Challenges401SuccessEnum = {
    "false": false
} as const;

export type GetV1Challenges401SuccessEnum = (typeof getV1Challenges401SuccessEnum)[keyof typeof getV1Challenges401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1Challenges401 = {
    /**
     * @type boolean
    */
    success: GetV1Challenges401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesQueryResponse = GetV1Challenges200;

export type GetV1ChallengesQuery = {
    Response: GetV1Challenges200;
    QueryParams: GetV1ChallengesQueryParams;
    Errors: GetV1Challenges401;
};