/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getV1OrganizationsMine200SuccessEnum = {
    "true": true
} as const;

export type GetV1OrganizationsMine200SuccessEnum = (typeof getV1OrganizationsMine200SuccessEnum)[keyof typeof getV1OrganizationsMine200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsMine200 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsMine200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        slug: string;
        /**
         * @type string
        */
        role: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1OrganizationsMine401SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsMine401SuccessEnum = (typeof getV1OrganizationsMine401SuccessEnum)[keyof typeof getV1OrganizationsMine401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsMine401 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsMine401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1OrganizationsMineQueryResponse = GetV1OrganizationsMine200;

export type GetV1OrganizationsMineQuery = {
    Response: GetV1OrganizationsMine200;
    Errors: GetV1OrganizationsMine401;
};