/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1WorkSessionsByChallengeQueryParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
};

export const getV1WorkSessionsByChallenge200SuccessEnum = {
    "true": true
} as const;

export type GetV1WorkSessionsByChallenge200SuccessEnum = (typeof getV1WorkSessionsByChallenge200SuccessEnum)[keyof typeof getV1WorkSessionsByChallenge200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1WorkSessionsByChallenge200 = {
    /**
     * @type boolean
    */
    success: GetV1WorkSessionsByChallenge200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        challengeId: string;
        /**
         * @type string
        */
        teachingAssistantId: string;
        /**
         * @type string
        */
        classroomId: string | null;
        /**
         * @type string
        */
        createdAt: string;
        /**
         * @type string
        */
        lastMessageAt: string | null;
        /**
         * @type string
        */
        endedAt: string | null;
    } | null;
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1WorkSessionsByChallenge401SuccessEnum = {
    "false": false
} as const;

export type GetV1WorkSessionsByChallenge401SuccessEnum = (typeof getV1WorkSessionsByChallenge401SuccessEnum)[keyof typeof getV1WorkSessionsByChallenge401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1WorkSessionsByChallenge401 = {
    /**
     * @type boolean
    */
    success: GetV1WorkSessionsByChallenge401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1WorkSessionsByChallenge404SuccessEnum = {
    "false": false
} as const;

export type GetV1WorkSessionsByChallenge404SuccessEnum = (typeof getV1WorkSessionsByChallenge404SuccessEnum)[keyof typeof getV1WorkSessionsByChallenge404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1WorkSessionsByChallenge404 = {
    /**
     * @type boolean
    */
    success: GetV1WorkSessionsByChallenge404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1WorkSessionsByChallengeQueryResponse = GetV1WorkSessionsByChallenge200;

export type GetV1WorkSessionsByChallengeQuery = {
    Response: GetV1WorkSessionsByChallenge200;
    QueryParams: GetV1WorkSessionsByChallengeQueryParams;
    Errors: GetV1WorkSessionsByChallenge401 | GetV1WorkSessionsByChallenge404;
};