/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1OrganizationsIdEmailDomainsPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const getV1OrganizationsIdEmailDomains200SuccessEnum = {
    "true": true
} as const;

export type GetV1OrganizationsIdEmailDomains200SuccessEnum = (typeof getV1OrganizationsIdEmailDomains200SuccessEnum)[keyof typeof getV1OrganizationsIdEmailDomains200SuccessEnum];

export const dataRoleEnum = {
    "student": "student",
    "teacher": "teacher",
    "coordinator": "coordinator",
    "admin": "admin"
} as const;

export type DataRoleEnum = (typeof dataRoleEnum)[keyof typeof dataRoleEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdEmailDomains200 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdEmailDomains200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        domain: string;
        /**
         * @type string
        */
        role: DataRoleEnum;
        /**
         * @type string, date-time
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1OrganizationsIdEmailDomains401SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdEmailDomains401SuccessEnum = (typeof getV1OrganizationsIdEmailDomains401SuccessEnum)[keyof typeof getV1OrganizationsIdEmailDomains401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdEmailDomains401 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdEmailDomains401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1OrganizationsIdEmailDomains403SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdEmailDomains403SuccessEnum = (typeof getV1OrganizationsIdEmailDomains403SuccessEnum)[keyof typeof getV1OrganizationsIdEmailDomains403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdEmailDomains403 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdEmailDomains403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1OrganizationsIdEmailDomains404SuccessEnum = {
    "false": false
} as const;

export type GetV1OrganizationsIdEmailDomains404SuccessEnum = (typeof getV1OrganizationsIdEmailDomains404SuccessEnum)[keyof typeof getV1OrganizationsIdEmailDomains404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1OrganizationsIdEmailDomains404 = {
    /**
     * @type boolean
    */
    success: GetV1OrganizationsIdEmailDomains404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1OrganizationsIdEmailDomainsQueryResponse = GetV1OrganizationsIdEmailDomains200;

export type GetV1OrganizationsIdEmailDomainsQuery = {
    Response: GetV1OrganizationsIdEmailDomains200;
    PathParams: GetV1OrganizationsIdEmailDomainsPathParams;
    Errors: GetV1OrganizationsIdEmailDomains401 | GetV1OrganizationsIdEmailDomains403 | GetV1OrganizationsIdEmailDomains404;
};