/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
};

export type GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams = {
    /**
     * @minLength 1
     * @type string
    */
    q: string;
    /**
     * @minLength 1
     * @maxLength 50
     * @default 10
     * @type number | undefined
    */
    limit?: number;
};

export const getV1ChallengesChallengeidKnowledgeBasesSearch200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesChallengeidKnowledgeBasesSearch200SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBasesSearch200SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBasesSearch200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBasesSearch200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBasesSearch200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        chunkId: string;
        /**
         * @type string
        */
        content: string;
        /**
         * @type number
        */
        similarity: number;
        /**
         * @type object
        */
        metadata: {
            /**
             * @type array | undefined
            */
            titleHierarchy?: string[];
            /**
             * @type string | undefined
            */
            documentFilename?: string;
        } | null;
        /**
         * @type string
        */
        knowledgeBaseId: string;
        /**
         * @type string
        */
        knowledgeBaseTitle: string;
        /**
         * @type string
        */
        documentId: string | null;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesChallengeidKnowledgeBasesSearch401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBasesSearch401SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBasesSearch401SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBasesSearch401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBasesSearch401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBasesSearch401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidKnowledgeBasesSearch403SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBasesSearch403SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBasesSearch403SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBasesSearch403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBasesSearch403 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBasesSearch403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidKnowledgeBasesSearch404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBasesSearch404SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBasesSearch404SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBasesSearch404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBasesSearch404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBasesSearch404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidKnowledgeBasesSearch503SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidKnowledgeBasesSearch503SuccessEnum = (typeof getV1ChallengesChallengeidKnowledgeBasesSearch503SuccessEnum)[keyof typeof getV1ChallengesChallengeidKnowledgeBasesSearch503SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidKnowledgeBasesSearch503 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidKnowledgeBasesSearch503SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesChallengeidKnowledgeBasesSearchQueryResponse = GetV1ChallengesChallengeidKnowledgeBasesSearch200;

export type GetV1ChallengesChallengeidKnowledgeBasesSearchQuery = {
    Response: GetV1ChallengesChallengeidKnowledgeBasesSearch200;
    PathParams: GetV1ChallengesChallengeidKnowledgeBasesSearchPathParams;
    QueryParams: GetV1ChallengesChallengeidKnowledgeBasesSearchQueryParams;
    Errors: GetV1ChallengesChallengeidKnowledgeBasesSearch401 | GetV1ChallengesChallengeidKnowledgeBasesSearch403 | GetV1ChallengesChallengeidKnowledgeBasesSearch404 | GetV1ChallengesChallengeidKnowledgeBasesSearch503;
};