/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesChallengeidSubmissionsSubmissionidPathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
    /**
     * @minLength 1
     * @type string
    */
    submissionId: string;
};

export const getV1ChallengesChallengeidSubmissionsSubmissionid200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesChallengeidSubmissionsSubmissionid200SuccessEnum = (typeof getV1ChallengesChallengeidSubmissionsSubmissionid200SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissionsSubmissionid200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissionsSubmissionid200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissionsSubmissionid200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        submissionId: string;
        /**
         * @type string
        */
        workSessionId: string;
        /**
         * @type string
        */
        challengeId: string;
        /**
         * @type string
        */
        studentUserId: string;
        /**
         * @type string
        */
        studentName: string;
        /**
         * @type string
        */
        code: string | null;
        /**
         * @type string
        */
        stdin: string | null;
        /**
         * @type string
        */
        stdout: string | null;
        /**
         * @type string
        */
        submittedAt: string;
        /**
         * @type string
        */
        grade: string | null;
        /**
         * @type string
        */
        gradingComment: string | null;
        /**
         * @type string
        */
        gradedByUserId: string | null;
        /**
         * @type string
        */
        gradedAt: string | null;
        /**
         * @type string
        */
        autoReview: string | null;
        /**
         * @type string
        */
        autoReviewAt: string | null;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesChallengeidSubmissionsSubmissionid401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissionsSubmissionid401SuccessEnum = (typeof getV1ChallengesChallengeidSubmissionsSubmissionid401SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissionsSubmissionid401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissionsSubmissionid401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissionsSubmissionid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidSubmissionsSubmissionid403SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissionsSubmissionid403SuccessEnum = (typeof getV1ChallengesChallengeidSubmissionsSubmissionid403SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissionsSubmissionid403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissionsSubmissionid403 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissionsSubmissionid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesChallengeidSubmissionsSubmissionid404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesChallengeidSubmissionsSubmissionid404SuccessEnum = (typeof getV1ChallengesChallengeidSubmissionsSubmissionid404SuccessEnum)[keyof typeof getV1ChallengesChallengeidSubmissionsSubmissionid404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesChallengeidSubmissionsSubmissionid404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesChallengeidSubmissionsSubmissionid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesChallengeidSubmissionsSubmissionidQueryResponse = GetV1ChallengesChallengeidSubmissionsSubmissionid200;

export type GetV1ChallengesChallengeidSubmissionsSubmissionidQuery = {
    Response: GetV1ChallengesChallengeidSubmissionsSubmissionid200;
    PathParams: GetV1ChallengesChallengeidSubmissionsSubmissionidPathParams;
    Errors: GetV1ChallengesChallengeidSubmissionsSubmissionid401 | GetV1ChallengesChallengeidSubmissionsSubmissionid403 | GetV1ChallengesChallengeidSubmissionsSubmissionid404;
};