/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChallengesIdKnowledgeBaseDocumentsPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export type GetV1ChallengesIdKnowledgeBaseDocumentsQueryParams = {
    /**
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type number | undefined
    */
    perPage?: number;
};

export const getV1ChallengesIdKnowledgeBaseDocuments200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChallengesIdKnowledgeBaseDocuments200SuccessEnum = (typeof getV1ChallengesIdKnowledgeBaseDocuments200SuccessEnum)[keyof typeof getV1ChallengesIdKnowledgeBaseDocuments200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesIdKnowledgeBaseDocuments200 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesIdKnowledgeBaseDocuments200SuccessEnum;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        filename: string;
        /**
         * @type string
        */
        mimeType: string;
        /**
         * @type number
        */
        fileSize: number;
        /**
         * @type number
        */
        chunkCount: number;
        /**
         * @type string
        */
        status: string;
        /**
         * @type string
        */
        errorMessage: string | null;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum = (typeof getV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum)[keyof typeof getV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesIdKnowledgeBaseDocuments401 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum = (typeof getV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum)[keyof typeof getV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesIdKnowledgeBaseDocuments403 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum = (typeof getV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum)[keyof typeof getV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChallengesIdKnowledgeBaseDocuments404 = {
    /**
     * @type boolean
    */
    success: GetV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChallengesIdKnowledgeBaseDocumentsQueryResponse = GetV1ChallengesIdKnowledgeBaseDocuments200;

export type GetV1ChallengesIdKnowledgeBaseDocumentsQuery = {
    Response: GetV1ChallengesIdKnowledgeBaseDocuments200;
    PathParams: GetV1ChallengesIdKnowledgeBaseDocumentsPathParams;
    QueryParams: GetV1ChallengesIdKnowledgeBaseDocumentsQueryParams;
    Errors: GetV1ChallengesIdKnowledgeBaseDocuments401 | GetV1ChallengesIdKnowledgeBaseDocuments403 | GetV1ChallengesIdKnowledgeBaseDocuments404;
};