/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ClassroomsIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const getV1ClassroomsId200SuccessEnum = {
    "true": true
} as const;

export type GetV1ClassroomsId200SuccessEnum = (typeof getV1ClassroomsId200SuccessEnum)[keyof typeof getV1ClassroomsId200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ClassroomsId200 = {
    /**
     * @type boolean
    */
    success: GetV1ClassroomsId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        organizationId: string;
        /**
         * @type string
        */
        organizationName: string | null;
        /**
         * @type string
        */
        teacherUserId: string | null;
        /**
         * @type string
        */
        teacherName: string | null;
        /**
         * @type array
        */
        enrollments: {
            /**
             * @type string
            */
            userId: string;
            /**
             * @type string
            */
            name: string;
            /**
             * @type string
            */
            email: string;
            /**
             * @type string
            */
            enrolledAt: string;
        }[];
        /**
         * @type string
        */
        createdAt: string;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ClassroomsId401SuccessEnum = {
    "false": false
} as const;

export type GetV1ClassroomsId401SuccessEnum = (typeof getV1ClassroomsId401SuccessEnum)[keyof typeof getV1ClassroomsId401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ClassroomsId401 = {
    /**
     * @type boolean
    */
    success: GetV1ClassroomsId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ClassroomsId404SuccessEnum = {
    "false": false
} as const;

export type GetV1ClassroomsId404SuccessEnum = (typeof getV1ClassroomsId404SuccessEnum)[keyof typeof getV1ClassroomsId404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ClassroomsId404 = {
    /**
     * @type boolean
    */
    success: GetV1ClassroomsId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ClassroomsIdQueryResponse = GetV1ClassroomsId200;

export type GetV1ClassroomsIdQuery = {
    Response: GetV1ClassroomsId200;
    PathParams: GetV1ClassroomsIdPathParams;
    Errors: GetV1ClassroomsId401 | GetV1ClassroomsId404;
};