/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetV1ChatStudentHistoryWorksessionidPathParams = {
    /**
     * @type string
    */
    workSessionId: string;
};

export const getV1ChatStudentHistoryWorksessionid200SuccessEnum = {
    "true": true
} as const;

export type GetV1ChatStudentHistoryWorksessionid200SuccessEnum = (typeof getV1ChatStudentHistoryWorksessionid200SuccessEnum)[keyof typeof getV1ChatStudentHistoryWorksessionid200SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChatStudentHistoryWorksessionid200 = {
    /**
     * @type boolean
    */
    success: GetV1ChatStudentHistoryWorksessionid200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type array
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        userPrompt: string;
        /**
         * @type string
        */
        modelResponse: string;
        /**
         * @type string
        */
        code: string | null;
        /**
         * @type string
        */
        stdout: string | null;
        /**
         * @type string
        */
        createdAt: string;
    }[];
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const getV1ChatStudentHistoryWorksessionid401SuccessEnum = {
    "false": false
} as const;

export type GetV1ChatStudentHistoryWorksessionid401SuccessEnum = (typeof getV1ChatStudentHistoryWorksessionid401SuccessEnum)[keyof typeof getV1ChatStudentHistoryWorksessionid401SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChatStudentHistoryWorksessionid401 = {
    /**
     * @type boolean
    */
    success: GetV1ChatStudentHistoryWorksessionid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const getV1ChatStudentHistoryWorksessionid404SuccessEnum = {
    "false": false
} as const;

export type GetV1ChatStudentHistoryWorksessionid404SuccessEnum = (typeof getV1ChatStudentHistoryWorksessionid404SuccessEnum)[keyof typeof getV1ChatStudentHistoryWorksessionid404SuccessEnum];

/**
 * @description Default Response
*/
export type GetV1ChatStudentHistoryWorksessionid404 = {
    /**
     * @type boolean
    */
    success: GetV1ChatStudentHistoryWorksessionid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type GetV1ChatStudentHistoryWorksessionidQueryResponse = GetV1ChatStudentHistoryWorksessionid200;

export type GetV1ChatStudentHistoryWorksessionidQuery = {
    Response: GetV1ChatStudentHistoryWorksessionid200;
    PathParams: GetV1ChatStudentHistoryWorksessionidPathParams;
    Errors: GetV1ChatStudentHistoryWorksessionid401 | GetV1ChatStudentHistoryWorksessionid404;
};