/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchV1OrganizationsIdActivePathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const patchV1OrganizationsIdActive200SuccessEnum = {
    "true": true
} as const;

export type PatchV1OrganizationsIdActive200SuccessEnum = (typeof patchV1OrganizationsIdActive200SuccessEnum)[keyof typeof patchV1OrganizationsIdActive200SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1OrganizationsIdActive200 = {
    /**
     * @type boolean
    */
    success: PatchV1OrganizationsIdActive200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type boolean
        */
        isActive: boolean;
        /**
         * @type number
        */
        clearedSessions: number;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const patchV1OrganizationsIdActive400SuccessEnum = {
    "false": false
} as const;

export type PatchV1OrganizationsIdActive400SuccessEnum = (typeof patchV1OrganizationsIdActive400SuccessEnum)[keyof typeof patchV1OrganizationsIdActive400SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1OrganizationsIdActive400 = {
    /**
     * @type boolean
    */
    success: PatchV1OrganizationsIdActive400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1OrganizationsIdActive401SuccessEnum = {
    "false": false
} as const;

export type PatchV1OrganizationsIdActive401SuccessEnum = (typeof patchV1OrganizationsIdActive401SuccessEnum)[keyof typeof patchV1OrganizationsIdActive401SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1OrganizationsIdActive401 = {
    /**
     * @type boolean
    */
    success: PatchV1OrganizationsIdActive401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1OrganizationsIdActive403SuccessEnum = {
    "false": false
} as const;

export type PatchV1OrganizationsIdActive403SuccessEnum = (typeof patchV1OrganizationsIdActive403SuccessEnum)[keyof typeof patchV1OrganizationsIdActive403SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1OrganizationsIdActive403 = {
    /**
     * @type boolean
    */
    success: PatchV1OrganizationsIdActive403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1OrganizationsIdActive404SuccessEnum = {
    "false": false
} as const;

export type PatchV1OrganizationsIdActive404SuccessEnum = (typeof patchV1OrganizationsIdActive404SuccessEnum)[keyof typeof patchV1OrganizationsIdActive404SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1OrganizationsIdActive404 = {
    /**
     * @type boolean
    */
    success: PatchV1OrganizationsIdActive404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PatchV1OrganizationsIdActiveMutationRequest = {
    /**
     * @type boolean
    */
    isActive: boolean;
};

export type PatchV1OrganizationsIdActiveMutationResponse = PatchV1OrganizationsIdActive200;

export type PatchV1OrganizationsIdActiveMutation = {
    Response: PatchV1OrganizationsIdActive200;
    Request: PatchV1OrganizationsIdActiveMutationRequest;
    PathParams: PatchV1OrganizationsIdActivePathParams;
    Errors: PatchV1OrganizationsIdActive400 | PatchV1OrganizationsIdActive401 | PatchV1OrganizationsIdActive403 | PatchV1OrganizationsIdActive404;
};