/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchV1ChallengesIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const patchV1ChallengesId200SuccessEnum = {
    "true": true
} as const;

export type PatchV1ChallengesId200SuccessEnum = (typeof patchV1ChallengesId200SuccessEnum)[keyof typeof patchV1ChallengesId200SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1ChallengesId200 = {
    /**
     * @type boolean
    */
    success: PatchV1ChallengesId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        classroomId: string | null;
        /**
         * @type string
        */
        title: string | null;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        difficulty: string | null;
        /**
         * @type array
        */
        tags: string[] | null;
        /**
         * @type string
        */
        possibleSolutions: string | null;
        /**
         * @type string
        */
        message: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const patchV1ChallengesId400SuccessEnum = {
    "false": false
} as const;

export type PatchV1ChallengesId400SuccessEnum = (typeof patchV1ChallengesId400SuccessEnum)[keyof typeof patchV1ChallengesId400SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1ChallengesId400 = {
    /**
     * @type boolean
    */
    success: PatchV1ChallengesId400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1ChallengesId401SuccessEnum = {
    "false": false
} as const;

export type PatchV1ChallengesId401SuccessEnum = (typeof patchV1ChallengesId401SuccessEnum)[keyof typeof patchV1ChallengesId401SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1ChallengesId401 = {
    /**
     * @type boolean
    */
    success: PatchV1ChallengesId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1ChallengesId403SuccessEnum = {
    "false": false
} as const;

export type PatchV1ChallengesId403SuccessEnum = (typeof patchV1ChallengesId403SuccessEnum)[keyof typeof patchV1ChallengesId403SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1ChallengesId403 = {
    /**
     * @type boolean
    */
    success: PatchV1ChallengesId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1ChallengesId404SuccessEnum = {
    "false": false
} as const;

export type PatchV1ChallengesId404SuccessEnum = (typeof patchV1ChallengesId404SuccessEnum)[keyof typeof patchV1ChallengesId404SuccessEnum];

/**
 * @description Default Response
*/
export type PatchV1ChallengesId404 = {
    /**
     * @type boolean
    */
    success: PatchV1ChallengesId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const patchV1ChallengesIdMutationRequestDifficultyEnum = {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
} as const;

export type PatchV1ChallengesIdMutationRequestDifficultyEnum = (typeof patchV1ChallengesIdMutationRequestDifficultyEnum)[keyof typeof patchV1ChallengesIdMutationRequestDifficultyEnum];

export type PatchV1ChallengesIdMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string
    */
    description?: string | null;
    /**
     * @type string
    */
    difficulty?: PatchV1ChallengesIdMutationRequestDifficultyEnum | null;
    /**
     * @type array
    */
    tags?: string[] | null;
    /**
     * @type string
    */
    possibleSolutions?: string | null;
    /**
     * @minLength 1
     * @type string
    */
    classroomId?: string | null;
    /**
     * @type boolean | undefined
    */
    generateReferenceSolutions?: boolean;
};

export type PatchV1ChallengesIdMutationResponse = PatchV1ChallengesId200;

export type PatchV1ChallengesIdMutation = {
    Response: PatchV1ChallengesId200;
    Request: PatchV1ChallengesIdMutationRequest;
    PathParams: PatchV1ChallengesIdPathParams;
    Errors: PatchV1ChallengesId400 | PatchV1ChallengesId401 | PatchV1ChallengesId403 | PatchV1ChallengesId404;
};