/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postV1ChatStudentMessage401SuccessEnum = {
    "false": false
} as const;

export type PostV1ChatStudentMessage401SuccessEnum = (typeof postV1ChatStudentMessage401SuccessEnum)[keyof typeof postV1ChatStudentMessage401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChatStudentMessage401 = {
    /**
     * @type boolean
    */
    success: PostV1ChatStudentMessage401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChatStudentMessage404SuccessEnum = {
    "false": false
} as const;

export type PostV1ChatStudentMessage404SuccessEnum = (typeof postV1ChatStudentMessage404SuccessEnum)[keyof typeof postV1ChatStudentMessage404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChatStudentMessage404 = {
    /**
     * @type boolean
    */
    success: PostV1ChatStudentMessage404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChatStudentMessage500SuccessEnum = {
    "false": false
} as const;

export type PostV1ChatStudentMessage500SuccessEnum = (typeof postV1ChatStudentMessage500SuccessEnum)[keyof typeof postV1ChatStudentMessage500SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChatStudentMessage500 = {
    /**
     * @type boolean
    */
    success: PostV1ChatStudentMessage500SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1ChatStudentMessageMutationRequest = {
    /**
     * @type string
    */
    workSessionId: string;
    /**
     * @minLength 1
     * @type string
    */
    message: string;
    /**
     * @type string | undefined
    */
    currentCode?: string;
    /**
     * @type string | undefined
    */
    stdout?: string;
};

export type PostV1ChatStudentMessageMutationResponse = any;

export type PostV1ChatStudentMessageMutation = {
    Response: any;
    Request: PostV1ChatStudentMessageMutationRequest;
    Errors: PostV1ChatStudentMessage401 | PostV1ChatStudentMessage404 | PostV1ChatStudentMessage500;
};