/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1KnowledgeBasesKbidEntriesPathParams = {
    /**
     * @type string, uuid
    */
    kbId: string;
};

export const postV1KnowledgeBasesKbidEntries201SuccessEnum = {
    "true": true
} as const;

export type PostV1KnowledgeBasesKbidEntries201SuccessEnum = (typeof postV1KnowledgeBasesKbidEntries201SuccessEnum)[keyof typeof postV1KnowledgeBasesKbidEntries201SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBasesKbidEntries201 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBasesKbidEntries201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        content: string;
        /**
         * @type string
        */
        createdAt: string;
    };
};

export const postV1KnowledgeBasesKbidEntries401SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBasesKbidEntries401SuccessEnum = (typeof postV1KnowledgeBasesKbidEntries401SuccessEnum)[keyof typeof postV1KnowledgeBasesKbidEntries401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBasesKbidEntries401 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBasesKbidEntries401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1KnowledgeBasesKbidEntries403SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBasesKbidEntries403SuccessEnum = (typeof postV1KnowledgeBasesKbidEntries403SuccessEnum)[keyof typeof postV1KnowledgeBasesKbidEntries403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBasesKbidEntries403 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBasesKbidEntries403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1KnowledgeBasesKbidEntries404SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBasesKbidEntries404SuccessEnum = (typeof postV1KnowledgeBasesKbidEntries404SuccessEnum)[keyof typeof postV1KnowledgeBasesKbidEntries404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBasesKbidEntries404 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBasesKbidEntries404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1KnowledgeBasesKbidEntriesMutationRequest = {
    /**
     * @minLength 1
     * @type string
    */
    content: string;
};

export type PostV1KnowledgeBasesKbidEntriesMutationResponse = PostV1KnowledgeBasesKbidEntries201;

export type PostV1KnowledgeBasesKbidEntriesMutation = {
    Response: PostV1KnowledgeBasesKbidEntries201;
    Request: PostV1KnowledgeBasesKbidEntriesMutationRequest;
    PathParams: PostV1KnowledgeBasesKbidEntriesPathParams;
    Errors: PostV1KnowledgeBasesKbidEntries401 | PostV1KnowledgeBasesKbidEntries403 | PostV1KnowledgeBasesKbidEntries404;
};