/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1OrganizationsIdMembersUseridMovePathParams = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @type string, uuid
    */
    userId: string;
};

export const postV1OrganizationsIdMembersUseridMove200SuccessEnum = {
    "true": true
} as const;

export type PostV1OrganizationsIdMembersUseridMove200SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove200SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove200SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove200 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        userId: string;
        /**
         * @type string
        */
        organizationId: string;
        /**
         * @type string
        */
        role: string;
        /**
         * @type string
        */
        createdAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1OrganizationsIdMembersUseridMove400SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersUseridMove400SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove400SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove400 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersUseridMove401SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersUseridMove401SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove401SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove401 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersUseridMove403SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersUseridMove403SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove403SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove403 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersUseridMove404SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersUseridMove404SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove404SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove404 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersUseridMove409SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersUseridMove409SuccessEnum = (typeof postV1OrganizationsIdMembersUseridMove409SuccessEnum)[keyof typeof postV1OrganizationsIdMembersUseridMove409SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersUseridMove409 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersUseridMove409SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersUseridMoveMutationRequestNewRoleEnum = {
    "student": "student",
    "teacher": "teacher",
    "coordinator": "coordinator",
    "admin": "admin"
} as const;

export type PostV1OrganizationsIdMembersUseridMoveMutationRequestNewRoleEnum = (typeof postV1OrganizationsIdMembersUseridMoveMutationRequestNewRoleEnum)[keyof typeof postV1OrganizationsIdMembersUseridMoveMutationRequestNewRoleEnum];

export type PostV1OrganizationsIdMembersUseridMoveMutationRequest = {
    /**
     * @type string, uuid
    */
    toOrganizationId: string;
    /**
     * @type string
    */
    newRole: PostV1OrganizationsIdMembersUseridMoveMutationRequestNewRoleEnum;
};

export type PostV1OrganizationsIdMembersUseridMoveMutationResponse = PostV1OrganizationsIdMembersUseridMove200;

export type PostV1OrganizationsIdMembersUseridMoveMutation = {
    Response: PostV1OrganizationsIdMembersUseridMove200;
    Request: PostV1OrganizationsIdMembersUseridMoveMutationRequest;
    PathParams: PostV1OrganizationsIdMembersUseridMovePathParams;
    Errors: PostV1OrganizationsIdMembersUseridMove400 | PostV1OrganizationsIdMembersUseridMove401 | PostV1OrganizationsIdMembersUseridMove403 | PostV1OrganizationsIdMembersUseridMove404 | PostV1OrganizationsIdMembersUseridMove409;
};