/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postV1Challenges201SuccessEnum = {
    "true": true
} as const;

export type PostV1Challenges201SuccessEnum = (typeof postV1Challenges201SuccessEnum)[keyof typeof postV1Challenges201SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1Challenges201 = {
    /**
     * @type boolean
    */
    success: PostV1Challenges201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        difficulty: string | null;
        /**
         * @type array
        */
        tags: string[] | null;
        /**
         * @type string
        */
        classroomId: string | null;
        /**
         * @type string
        */
        createdAt: string;
    };
};

export const postV1Challenges400SuccessEnum = {
    "false": false
} as const;

export type PostV1Challenges400SuccessEnum = (typeof postV1Challenges400SuccessEnum)[keyof typeof postV1Challenges400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1Challenges400 = {
    /**
     * @type boolean
    */
    success: PostV1Challenges400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1Challenges401SuccessEnum = {
    "false": false
} as const;

export type PostV1Challenges401SuccessEnum = (typeof postV1Challenges401SuccessEnum)[keyof typeof postV1Challenges401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1Challenges401 = {
    /**
     * @type boolean
    */
    success: PostV1Challenges401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1Challenges403SuccessEnum = {
    "false": false
} as const;

export type PostV1Challenges403SuccessEnum = (typeof postV1Challenges403SuccessEnum)[keyof typeof postV1Challenges403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1Challenges403 = {
    /**
     * @type boolean
    */
    success: PostV1Challenges403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1Challenges404SuccessEnum = {
    "false": false
} as const;

export type PostV1Challenges404SuccessEnum = (typeof postV1Challenges404SuccessEnum)[keyof typeof postV1Challenges404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1Challenges404 = {
    /**
     * @type boolean
    */
    success: PostV1Challenges404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesMutationRequestDifficultyEnum = {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
} as const;

export type PostV1ChallengesMutationRequestDifficultyEnum = (typeof postV1ChallengesMutationRequestDifficultyEnum)[keyof typeof postV1ChallengesMutationRequestDifficultyEnum];

export type PostV1ChallengesMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string
    */
    difficulty: PostV1ChallengesMutationRequestDifficultyEnum;
    /**
     * @minLength 1
     * @type string
    */
    classroomId: string;
    /**
     * @type array | undefined
    */
    tags?: string[];
    supportMaterials?: any;
    possibleSolutions?: any;
};

export type PostV1ChallengesMutationResponse = PostV1Challenges201;

export type PostV1ChallengesMutation = {
    Response: PostV1Challenges201;
    Request: PostV1ChallengesMutationRequest;
    Errors: PostV1Challenges400 | PostV1Challenges401 | PostV1Challenges403 | PostV1Challenges404;
};