/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1OrganizationsIdInvitationsPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1OrganizationsIdInvitations201SuccessEnum = {
    "true": true
} as const;

export type PostV1OrganizationsIdInvitations201SuccessEnum = (typeof postV1OrganizationsIdInvitations201SuccessEnum)[keyof typeof postV1OrganizationsIdInvitations201SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdInvitations201 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdInvitations201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        email: string;
        /**
         * @type string
        */
        role: string;
        /**
         * @type string
        */
        status: string;
        /**
         * @type string
        */
        expiresAt: string;
    };
};

export const postV1OrganizationsIdInvitations400SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdInvitations400SuccessEnum = (typeof postV1OrganizationsIdInvitations400SuccessEnum)[keyof typeof postV1OrganizationsIdInvitations400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdInvitations400 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdInvitations400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdInvitations401SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdInvitations401SuccessEnum = (typeof postV1OrganizationsIdInvitations401SuccessEnum)[keyof typeof postV1OrganizationsIdInvitations401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdInvitations401 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdInvitations401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdInvitations403SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdInvitations403SuccessEnum = (typeof postV1OrganizationsIdInvitations403SuccessEnum)[keyof typeof postV1OrganizationsIdInvitations403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdInvitations403 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdInvitations403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdInvitationsMutationRequestRoleEnum = {
    "student": "student",
    "teacher": "teacher",
    "coordinator": "coordinator",
    "admin": "admin"
} as const;

export type PostV1OrganizationsIdInvitationsMutationRequestRoleEnum = (typeof postV1OrganizationsIdInvitationsMutationRequestRoleEnum)[keyof typeof postV1OrganizationsIdInvitationsMutationRequestRoleEnum];

export type PostV1OrganizationsIdInvitationsMutationRequest = {
    /**
     * @type string, email
    */
    email: string;
    /**
     * @type string
    */
    role: PostV1OrganizationsIdInvitationsMutationRequestRoleEnum;
};

export type PostV1OrganizationsIdInvitationsMutationResponse = PostV1OrganizationsIdInvitations201;

export type PostV1OrganizationsIdInvitationsMutation = {
    Response: PostV1OrganizationsIdInvitations201;
    Request: PostV1OrganizationsIdInvitationsMutationRequest;
    PathParams: PostV1OrganizationsIdInvitationsPathParams;
    Errors: PostV1OrganizationsIdInvitations400 | PostV1OrganizationsIdInvitations401 | PostV1OrganizationsIdInvitations403;
};