/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1WorkSessionsIdInteractionsPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1WorkSessionsIdInteractions201SuccessEnum = {
    "true": true
} as const;

export type PostV1WorkSessionsIdInteractions201SuccessEnum = (typeof postV1WorkSessionsIdInteractions201SuccessEnum)[keyof typeof postV1WorkSessionsIdInteractions201SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdInteractions201 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdInteractions201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        interactionType: string;
        /**
         * @type string
        */
        userPrompt: string;
        /**
         * @type string
        */
        modelResponse: string;
        /**
         * @type string
        */
        code: string | null;
        /**
         * @type string
        */
        stdin: string | null;
        /**
         * @type string
        */
        stdout: string | null;
        /**
         * @type string
        */
        createdAt: string;
    };
};

export const postV1WorkSessionsIdInteractions400SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdInteractions400SuccessEnum = (typeof postV1WorkSessionsIdInteractions400SuccessEnum)[keyof typeof postV1WorkSessionsIdInteractions400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdInteractions400 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdInteractions400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdInteractions401SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdInteractions401SuccessEnum = (typeof postV1WorkSessionsIdInteractions401SuccessEnum)[keyof typeof postV1WorkSessionsIdInteractions401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdInteractions401 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdInteractions401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdInteractions403SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdInteractions403SuccessEnum = (typeof postV1WorkSessionsIdInteractions403SuccessEnum)[keyof typeof postV1WorkSessionsIdInteractions403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdInteractions403 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdInteractions403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdInteractions404SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdInteractions404SuccessEnum = (typeof postV1WorkSessionsIdInteractions404SuccessEnum)[keyof typeof postV1WorkSessionsIdInteractions404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdInteractions404 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdInteractions404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdInteractionsMutationRequestInteractionTypeEnum = {
    "chat": "chat",
    "code_run": "code_run"
} as const;

export type PostV1WorkSessionsIdInteractionsMutationRequestInteractionTypeEnum = (typeof postV1WorkSessionsIdInteractionsMutationRequestInteractionTypeEnum)[keyof typeof postV1WorkSessionsIdInteractionsMutationRequestInteractionTypeEnum];

export type PostV1WorkSessionsIdInteractionsMutationRequest = {
    /**
     * @type string
    */
    interactionType: PostV1WorkSessionsIdInteractionsMutationRequestInteractionTypeEnum;
    /**
     * @default ""
     * @type string | undefined
    */
    userPrompt?: string;
    /**
     * @default ""
     * @type string | undefined
    */
    modelResponse?: string;
    /**
     * @type string | undefined
    */
    code?: string;
    /**
     * @type string | undefined
    */
    stdin?: string;
    /**
     * @type string | undefined
    */
    stdout?: string;
};

export type PostV1WorkSessionsIdInteractionsMutationResponse = PostV1WorkSessionsIdInteractions201;

export type PostV1WorkSessionsIdInteractionsMutation = {
    Response: PostV1WorkSessionsIdInteractions201;
    Request: PostV1WorkSessionsIdInteractionsMutationRequest;
    PathParams: PostV1WorkSessionsIdInteractionsPathParams;
    Errors: PostV1WorkSessionsIdInteractions400 | PostV1WorkSessionsIdInteractions401 | PostV1WorkSessionsIdInteractions403 | PostV1WorkSessionsIdInteractions404;
};