/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postV1KnowledgeBases201SuccessEnum = {
    "true": true
} as const;

export type PostV1KnowledgeBases201SuccessEnum = (typeof postV1KnowledgeBases201SuccessEnum)[keyof typeof postV1KnowledgeBases201SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBases201 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBases201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        classroomId: string;
        /**
         * @type string
        */
        organizationId: string;
        /**
         * @type string
        */
        createdByUserId: string | null;
        /**
         * @type string
        */
        createdAt: string;
    };
};

export const postV1KnowledgeBases400SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBases400SuccessEnum = (typeof postV1KnowledgeBases400SuccessEnum)[keyof typeof postV1KnowledgeBases400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBases400 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBases400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1KnowledgeBases401SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBases401SuccessEnum = (typeof postV1KnowledgeBases401SuccessEnum)[keyof typeof postV1KnowledgeBases401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBases401 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBases401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1KnowledgeBases403SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBases403SuccessEnum = (typeof postV1KnowledgeBases403SuccessEnum)[keyof typeof postV1KnowledgeBases403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBases403 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBases403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1KnowledgeBases404SuccessEnum = {
    "false": false
} as const;

export type PostV1KnowledgeBases404SuccessEnum = (typeof postV1KnowledgeBases404SuccessEnum)[keyof typeof postV1KnowledgeBases404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1KnowledgeBases404 = {
    /**
     * @type boolean
    */
    success: PostV1KnowledgeBases404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1KnowledgeBasesMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string, uuid
    */
    classroomId: string;
};

export type PostV1KnowledgeBasesMutationResponse = PostV1KnowledgeBases201;

export type PostV1KnowledgeBasesMutation = {
    Response: PostV1KnowledgeBases201;
    Request: PostV1KnowledgeBasesMutationRequest;
    Errors: PostV1KnowledgeBases400 | PostV1KnowledgeBases401 | PostV1KnowledgeBases403 | PostV1KnowledgeBases404;
};