/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1WorkSessionsIdReopenPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const postV1WorkSessionsIdReopen200SuccessEnum = {
    "true": true
} as const;

export type PostV1WorkSessionsIdReopen200SuccessEnum = (typeof postV1WorkSessionsIdReopen200SuccessEnum)[keyof typeof postV1WorkSessionsIdReopen200SuccessEnum];

export const dataEndedAtEnum = {
    "null": "null"
} as const;

export type DataEndedAtEnum = (typeof dataEndedAtEnum)[keyof typeof dataEndedAtEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdReopen200 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdReopen200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        endedAt: DataEndedAtEnum | null;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1WorkSessionsIdReopen400SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdReopen400SuccessEnum = (typeof postV1WorkSessionsIdReopen400SuccessEnum)[keyof typeof postV1WorkSessionsIdReopen400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdReopen400 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdReopen400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdReopen401SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdReopen401SuccessEnum = (typeof postV1WorkSessionsIdReopen401SuccessEnum)[keyof typeof postV1WorkSessionsIdReopen401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdReopen401 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdReopen401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdReopen403SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdReopen403SuccessEnum = (typeof postV1WorkSessionsIdReopen403SuccessEnum)[keyof typeof postV1WorkSessionsIdReopen403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdReopen403 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdReopen403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdReopen404SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdReopen404SuccessEnum = (typeof postV1WorkSessionsIdReopen404SuccessEnum)[keyof typeof postV1WorkSessionsIdReopen404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdReopen404 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdReopen404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1WorkSessionsIdReopenMutationResponse = PostV1WorkSessionsIdReopen200;

export type PostV1WorkSessionsIdReopenMutation = {
    Response: PostV1WorkSessionsIdReopen200;
    PathParams: PostV1WorkSessionsIdReopenPathParams;
    Errors: PostV1WorkSessionsIdReopen400 | PostV1WorkSessionsIdReopen401 | PostV1WorkSessionsIdReopen403 | PostV1WorkSessionsIdReopen404;
};