/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1WorkSessionsIdChatPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const postV1WorkSessionsIdChat200SuccessEnum = {
    "true": true
} as const;

export type PostV1WorkSessionsIdChat200SuccessEnum = (typeof postV1WorkSessionsIdChat200SuccessEnum)[keyof typeof postV1WorkSessionsIdChat200SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat200 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        modelResponse: string;
        /**
         * @type string
        */
        interactionId: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1WorkSessionsIdChat400SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdChat400SuccessEnum = (typeof postV1WorkSessionsIdChat400SuccessEnum)[keyof typeof postV1WorkSessionsIdChat400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat400 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdChat401SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdChat401SuccessEnum = (typeof postV1WorkSessionsIdChat401SuccessEnum)[keyof typeof postV1WorkSessionsIdChat401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat401 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdChat403SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdChat403SuccessEnum = (typeof postV1WorkSessionsIdChat403SuccessEnum)[keyof typeof postV1WorkSessionsIdChat403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat403 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdChat404SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdChat404SuccessEnum = (typeof postV1WorkSessionsIdChat404SuccessEnum)[keyof typeof postV1WorkSessionsIdChat404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat404 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1WorkSessionsIdChat503SuccessEnum = {
    "false": false
} as const;

export type PostV1WorkSessionsIdChat503SuccessEnum = (typeof postV1WorkSessionsIdChat503SuccessEnum)[keyof typeof postV1WorkSessionsIdChat503SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1WorkSessionsIdChat503 = {
    /**
     * @type boolean
    */
    success: PostV1WorkSessionsIdChat503SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1WorkSessionsIdChatMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 10000
     * @type string
    */
    message: string;
    /**
     * @type string | undefined
    */
    code?: string;
    /**
     * @type string | undefined
    */
    stdin?: string;
    /**
     * @type string | undefined
    */
    stdout?: string;
};

export type PostV1WorkSessionsIdChatMutationResponse = PostV1WorkSessionsIdChat200;

export type PostV1WorkSessionsIdChatMutation = {
    Response: PostV1WorkSessionsIdChat200;
    Request: PostV1WorkSessionsIdChatMutationRequest;
    PathParams: PostV1WorkSessionsIdChatPathParams;
    Errors: PostV1WorkSessionsIdChat400 | PostV1WorkSessionsIdChat401 | PostV1WorkSessionsIdChat403 | PostV1WorkSessionsIdChat404 | PostV1WorkSessionsIdChat503;
};