/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1ClassroomsIdEnrollPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1ClassroomsIdEnroll200SuccessEnum = {
    "true": true
} as const;

export type PostV1ClassroomsIdEnroll200SuccessEnum = (typeof postV1ClassroomsIdEnroll200SuccessEnum)[keyof typeof postV1ClassroomsIdEnroll200SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ClassroomsIdEnroll200 = {
    /**
     * @type boolean
    */
    success: PostV1ClassroomsIdEnroll200SuccessEnum;
    /**
     * @type string
    */
    message: string;
};

export const postV1ClassroomsIdEnroll400SuccessEnum = {
    "false": false
} as const;

export type PostV1ClassroomsIdEnroll400SuccessEnum = (typeof postV1ClassroomsIdEnroll400SuccessEnum)[keyof typeof postV1ClassroomsIdEnroll400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ClassroomsIdEnroll400 = {
    /**
     * @type boolean
    */
    success: PostV1ClassroomsIdEnroll400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ClassroomsIdEnroll401SuccessEnum = {
    "false": false
} as const;

export type PostV1ClassroomsIdEnroll401SuccessEnum = (typeof postV1ClassroomsIdEnroll401SuccessEnum)[keyof typeof postV1ClassroomsIdEnroll401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ClassroomsIdEnroll401 = {
    /**
     * @type boolean
    */
    success: PostV1ClassroomsIdEnroll401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ClassroomsIdEnroll403SuccessEnum = {
    "false": false
} as const;

export type PostV1ClassroomsIdEnroll403SuccessEnum = (typeof postV1ClassroomsIdEnroll403SuccessEnum)[keyof typeof postV1ClassroomsIdEnroll403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ClassroomsIdEnroll403 = {
    /**
     * @type boolean
    */
    success: PostV1ClassroomsIdEnroll403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ClassroomsIdEnroll404SuccessEnum = {
    "false": false
} as const;

export type PostV1ClassroomsIdEnroll404SuccessEnum = (typeof postV1ClassroomsIdEnroll404SuccessEnum)[keyof typeof postV1ClassroomsIdEnroll404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ClassroomsIdEnroll404 = {
    /**
     * @type boolean
    */
    success: PostV1ClassroomsIdEnroll404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1ClassroomsIdEnrollMutationRequest = (any | {
    /**
     * @minLength 1
     * @type string | undefined
    */
    userId?: string;
});

export type PostV1ClassroomsIdEnrollMutationResponse = PostV1ClassroomsIdEnroll200;

export type PostV1ClassroomsIdEnrollMutation = {
    Response: PostV1ClassroomsIdEnroll200;
    Request: PostV1ClassroomsIdEnrollMutationRequest;
    PathParams: PostV1ClassroomsIdEnrollPathParams;
    Errors: PostV1ClassroomsIdEnroll400 | PostV1ClassroomsIdEnroll401 | PostV1ClassroomsIdEnroll403 | PostV1ClassroomsIdEnroll404;
};