/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1OrganizationsIdMembersImportCsvPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1OrganizationsIdMembersImportCsvQueryParamsDryRunEnum = {
    "true": "true",
    "false": "false"
} as const;

export type PostV1OrganizationsIdMembersImportCsvQueryParamsDryRunEnum = (typeof postV1OrganizationsIdMembersImportCsvQueryParamsDryRunEnum)[keyof typeof postV1OrganizationsIdMembersImportCsvQueryParamsDryRunEnum];

export type PostV1OrganizationsIdMembersImportCsvQueryParams = {
    /**
     * @type string | undefined
    */
    dryRun?: PostV1OrganizationsIdMembersImportCsvQueryParamsDryRunEnum;
};

export const postV1OrganizationsIdMembersImportCsv200SuccessEnum = {
    "true": true
} as const;

export type PostV1OrganizationsIdMembersImportCsv200SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv200SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv200SuccessEnum];

export const rowsStatusEnum = {
    "created": "created",
    "linked": "linked",
    "skipped": "skipped",
    "error": "error"
} as const;

export type RowsStatusEnum = (typeof rowsStatusEnum)[keyof typeof rowsStatusEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv200 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type boolean
        */
        dryRun: boolean;
        /**
         * @type object
        */
        summary: {
            /**
             * @type number
            */
            total: number;
            /**
             * @type number
            */
            created: number;
            /**
             * @type number
            */
            linked: number;
            /**
             * @type number
            */
            skipped: number;
            /**
             * @type number
            */
            errors: number;
        };
        /**
         * @type array
        */
        rows: {
            /**
             * @type number
            */
            line: number;
            /**
             * @type string
            */
            email: string;
            /**
             * @type string
            */
            status: RowsStatusEnum;
            /**
             * @type string | undefined
            */
            message?: string;
            /**
             * @type string | undefined
            */
            generatedPassword?: string;
        }[];
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1OrganizationsIdMembersImportCsv400SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersImportCsv400SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv400SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv400 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersImportCsv401SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersImportCsv401SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv401SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv401 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersImportCsv403SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersImportCsv403SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv403SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv403 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersImportCsv404SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersImportCsv404SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv404SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv404 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdMembersImportCsv413SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdMembersImportCsv413SuccessEnum = (typeof postV1OrganizationsIdMembersImportCsv413SuccessEnum)[keyof typeof postV1OrganizationsIdMembersImportCsv413SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdMembersImportCsv413 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdMembersImportCsv413SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1OrganizationsIdMembersImportCsvMutationResponse = PostV1OrganizationsIdMembersImportCsv200;

export type PostV1OrganizationsIdMembersImportCsvMutation = {
    Response: PostV1OrganizationsIdMembersImportCsv200;
    PathParams: PostV1OrganizationsIdMembersImportCsvPathParams;
    QueryParams: PostV1OrganizationsIdMembersImportCsvQueryParams;
    Errors: PostV1OrganizationsIdMembersImportCsv400 | PostV1OrganizationsIdMembersImportCsv401 | PostV1OrganizationsIdMembersImportCsv403 | PostV1OrganizationsIdMembersImportCsv404 | PostV1OrganizationsIdMembersImportCsv413;
};