/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1ChallengesIdKnowledgeBaseDocumentsPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const postV1ChallengesIdKnowledgeBaseDocuments202SuccessEnum = {
    "true": true
} as const;

export type PostV1ChallengesIdKnowledgeBaseDocuments202SuccessEnum = (typeof postV1ChallengesIdKnowledgeBaseDocuments202SuccessEnum)[keyof typeof postV1ChallengesIdKnowledgeBaseDocuments202SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesIdKnowledgeBaseDocuments202 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesIdKnowledgeBaseDocuments202SuccessEnum;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        challengeId: string;
        /**
         * @type string
        */
        filename: string;
        /**
         * @type string
        */
        mimeType: string;
        /**
         * @type number
        */
        fileSize: number;
        /**
         * @type number
        */
        chunkCount: number;
        /**
         * @type string
        */
        status: string;
        /**
         * @type string
        */
        createdAt: string;
    };
};

export const postV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum = (typeof postV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum)[keyof typeof postV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesIdKnowledgeBaseDocuments401 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesIdKnowledgeBaseDocuments401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum = (typeof postV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum)[keyof typeof postV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesIdKnowledgeBaseDocuments403 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesIdKnowledgeBaseDocuments403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum = (typeof postV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum)[keyof typeof postV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesIdKnowledgeBaseDocuments404 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesIdKnowledgeBaseDocuments404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1ChallengesIdKnowledgeBaseDocumentsMutationResponse = PostV1ChallengesIdKnowledgeBaseDocuments202;

export type PostV1ChallengesIdKnowledgeBaseDocumentsMutation = {
    Response: PostV1ChallengesIdKnowledgeBaseDocuments202;
    PathParams: PostV1ChallengesIdKnowledgeBaseDocumentsPathParams;
    Errors: PostV1ChallengesIdKnowledgeBaseDocuments401 | PostV1ChallengesIdKnowledgeBaseDocuments403 | PostV1ChallengesIdKnowledgeBaseDocuments404;
};