/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParamsKindEnum = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParamsKindEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParamsKindEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParamsKindEnum];

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParams = {
    /**
     * @minLength 1
     * @type string
    */
    challengeId: string;
    /**
     * @type string
    */
    kind: PostV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParamsKindEnum;
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate200SuccessEnum = {
    "true": true
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate200SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate200SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate200SuccessEnum];

export const dataKindEnum4 = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type DataKindEnum4 = (typeof dataKindEnum4)[keyof typeof dataKindEnum4];

export const dataStatusEnum3 = {
    "pending": "pending",
    "running": "running",
    "complete": "complete",
    "failed": "failed"
} as const;

export type DataStatusEnum3 = (typeof dataStatusEnum3)[keyof typeof dataStatusEnum3];

export const dataCreatedByEnum3 = {
    "ai": "ai",
    "manual": "manual"
} as const;

export type DataCreatedByEnum3 = (typeof dataCreatedByEnum3)[keyof typeof dataCreatedByEnum3];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate200 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        kind: DataKindEnum4;
        /**
         * @type string
        */
        language: string;
        /**
         * @type string
        */
        code: string | null;
        /**
         * @type string
        */
        status: DataStatusEnum3;
        /**
         * @type string
        */
        error: string | null;
        /**
         * @type string
        */
        createdBy: DataCreatedByEnum3;
        /**
         * @type string
        */
        generatedAt: string | null;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate401SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate401SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate401SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate401 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate403SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate403SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate403SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate403 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate404SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate404SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate404SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate404 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate409SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate409SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate409SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate409SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate409 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate409SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidReferenceSolutionsKindRegenerate429SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate429SuccessEnum = (typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate429SuccessEnum)[keyof typeof postV1ChallengesChallengeidReferenceSolutionsKindRegenerate429SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate429 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate429SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerateMutationResponse = PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate200;

export type PostV1ChallengesChallengeidReferenceSolutionsKindRegenerateMutation = {
    Response: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate200;
    PathParams: PostV1ChallengesChallengeidReferenceSolutionsKindRegeneratePathParams;
    Errors: PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate401 | PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate403 | PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate404 | PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate409 | PostV1ChallengesChallengeidReferenceSolutionsKindRegenerate429;
};