/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postV1AiChat200SuccessEnum = {
    "true": true
} as const;

export type PostV1AiChat200SuccessEnum = (typeof postV1AiChat200SuccessEnum)[keyof typeof postV1AiChat200SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1AiChat200 = {
    /**
     * @type boolean
    */
    success: PostV1AiChat200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        response: string;
        /**
         * @type array
        */
        suggestions: string[];
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1AiChat400SuccessEnum = {
    "false": false
} as const;

export type PostV1AiChat400SuccessEnum = (typeof postV1AiChat400SuccessEnum)[keyof typeof postV1AiChat400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1AiChat400 = {
    /**
     * @type boolean
    */
    success: PostV1AiChat400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1AiChatMutationRequest = {
    /**
     * @minLength 0
     * @type integer
    */
    exerciseId: number;
    /**
     * @type string
    */
    code: string;
    /**
     * @type string
    */
    language: string;
    /**
     * @minLength 1
     * @type string
    */
    message: string;
};

export type PostV1AiChatMutationResponse = PostV1AiChat200;

export type PostV1AiChatMutation = {
    Response: PostV1AiChat200;
    Request: PostV1AiChatMutationRequest;
    Errors: PostV1AiChat400;
};