/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
    /**
     * @minLength 1
     * @type string
    */
    submissionId: string;
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200SuccessEnum = {
    "true": true
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200SuccessEnum];

export const dataAutoReviewStatusEnum2 = {
    "pending": "pending",
    "running": "running",
    "complete": "complete",
    "failed": "failed"
} as const;

export type DataAutoReviewStatusEnum2 = (typeof dataAutoReviewStatusEnum2)[keyof typeof dataAutoReviewStatusEnum2];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        submissionId: string;
        /**
         * @type string
        */
        autoReview: string | null;
        /**
         * @type string
        */
        autoReviewAt: string | null;
        /**
         * @type string
        */
        autoReviewStatus: DataAutoReviewStatusEnum2;
        /**
         * @type string
        */
        autoReviewError: string | null;
        /**
         * @type boolean
        */
        generated: boolean;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500SuccessEnum = {
    "false": false
} as const;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500SuccessEnum = (typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500SuccessEnum)[keyof typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500 = {
    /**
     * @type boolean
    */
    success: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationResponse = PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200;

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutation = {
    Response: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview200;
    PathParams: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams;
    Errors: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500;
};