/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostV1OrganizationsIdEmailDomainsPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const postV1OrganizationsIdEmailDomains201SuccessEnum = {
    "true": true
} as const;

export type PostV1OrganizationsIdEmailDomains201SuccessEnum = (typeof postV1OrganizationsIdEmailDomains201SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains201SuccessEnum];

export const dataRoleEnum2 = {
    "student": "student",
    "teacher": "teacher",
    "coordinator": "coordinator"
} as const;

export type DataRoleEnum2 = (typeof dataRoleEnum2)[keyof typeof dataRoleEnum2];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains201 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains201SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        domain: string;
        /**
         * @type string
        */
        role: DataRoleEnum2;
        /**
         * @type string, date-time
        */
        createdAt: string;
    };
};

export const postV1OrganizationsIdEmailDomains400SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdEmailDomains400SuccessEnum = (typeof postV1OrganizationsIdEmailDomains400SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains400SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains400 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdEmailDomains401SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdEmailDomains401SuccessEnum = (typeof postV1OrganizationsIdEmailDomains401SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains401SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains401 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdEmailDomains403SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdEmailDomains403SuccessEnum = (typeof postV1OrganizationsIdEmailDomains403SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains403SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains403 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdEmailDomains404SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdEmailDomains404SuccessEnum = (typeof postV1OrganizationsIdEmailDomains404SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains404SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains404 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdEmailDomains409SuccessEnum = {
    "false": false
} as const;

export type PostV1OrganizationsIdEmailDomains409SuccessEnum = (typeof postV1OrganizationsIdEmailDomains409SuccessEnum)[keyof typeof postV1OrganizationsIdEmailDomains409SuccessEnum];

/**
 * @description Default Response
*/
export type PostV1OrganizationsIdEmailDomains409 = {
    /**
     * @type boolean
    */
    success: PostV1OrganizationsIdEmailDomains409SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const postV1OrganizationsIdEmailDomainsMutationRequestRoleEnum = {
    "student": "student",
    "teacher": "teacher",
    "coordinator": "coordinator"
} as const;

export type PostV1OrganizationsIdEmailDomainsMutationRequestRoleEnum = (typeof postV1OrganizationsIdEmailDomainsMutationRequestRoleEnum)[keyof typeof postV1OrganizationsIdEmailDomainsMutationRequestRoleEnum];

export type PostV1OrganizationsIdEmailDomainsMutationRequest = {
    /**
     * @minLength 3
     * @maxLength 253
     * @type string
    */
    domain: string;
    /**
     * @type string
    */
    role: PostV1OrganizationsIdEmailDomainsMutationRequestRoleEnum;
};

export type PostV1OrganizationsIdEmailDomainsMutationResponse = PostV1OrganizationsIdEmailDomains201;

export type PostV1OrganizationsIdEmailDomainsMutation = {
    Response: PostV1OrganizationsIdEmailDomains201;
    Request: PostV1OrganizationsIdEmailDomainsMutationRequest;
    PathParams: PostV1OrganizationsIdEmailDomainsPathParams;
    Errors: PostV1OrganizationsIdEmailDomains400 | PostV1OrganizationsIdEmailDomains401 | PostV1OrganizationsIdEmailDomains403 | PostV1OrganizationsIdEmailDomains404 | PostV1OrganizationsIdEmailDomains409;
};