/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutV1ChallengesChallengeidSubmissionsSubmissionidGradePathParams = {
    /**
     * @type string, uuid
    */
    challengeId: string;
    /**
     * @minLength 1
     * @type string
    */
    submissionId: string;
};

export const putV1ChallengesChallengeidSubmissionsSubmissionidGrade200SuccessEnum = {
    "true": true
} as const;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade200SuccessEnum = (typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade200SuccessEnum)[keyof typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade200SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade200 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        submissionId: string;
        /**
         * @type string
        */
        grade: string | null;
        /**
         * @type string
        */
        gradingComment: string | null;
        /**
         * @type string
        */
        gradedByUserId: string | null;
        /**
         * @type string
        */
        gradedAt: string | null;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1ChallengesChallengeidSubmissionsSubmissionidGrade400SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade400SuccessEnum = (typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade400SuccessEnum)[keyof typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade400SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade400 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidSubmissionsSubmissionidGrade401SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade401SuccessEnum = (typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade401SuccessEnum)[keyof typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade401 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidSubmissionsSubmissionidGrade403SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade403SuccessEnum = (typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade403SuccessEnum)[keyof typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade403 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidSubmissionsSubmissionidGrade404SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade404SuccessEnum = (typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade404SuccessEnum)[keyof typeof putV1ChallengesChallengeidSubmissionsSubmissionidGrade404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidSubmissionsSubmissionidGrade404 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGradeMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 10
     * @type string
    */
    grade: string;
    /**
     * @type string
    */
    comment?: string | null;
};

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGradeMutationResponse = PutV1ChallengesChallengeidSubmissionsSubmissionidGrade200;

export type PutV1ChallengesChallengeidSubmissionsSubmissionidGradeMutation = {
    Response: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade200;
    Request: PutV1ChallengesChallengeidSubmissionsSubmissionidGradeMutationRequest;
    PathParams: PutV1ChallengesChallengeidSubmissionsSubmissionidGradePathParams;
    Errors: PutV1ChallengesChallengeidSubmissionsSubmissionidGrade400 | PutV1ChallengesChallengeidSubmissionsSubmissionidGrade401 | PutV1ChallengesChallengeidSubmissionsSubmissionidGrade403 | PutV1ChallengesChallengeidSubmissionsSubmissionidGrade404;
};