/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutV1KnowledgeBasesKbidPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    kbId: string;
};

export const putV1KnowledgeBasesKbid200SuccessEnum = {
    "true": true
} as const;

export type PutV1KnowledgeBasesKbid200SuccessEnum = (typeof putV1KnowledgeBasesKbid200SuccessEnum)[keyof typeof putV1KnowledgeBasesKbid200SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1KnowledgeBasesKbid200 = {
    /**
     * @type boolean
    */
    success: PutV1KnowledgeBasesKbid200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1KnowledgeBasesKbid401SuccessEnum = {
    "false": false
} as const;

export type PutV1KnowledgeBasesKbid401SuccessEnum = (typeof putV1KnowledgeBasesKbid401SuccessEnum)[keyof typeof putV1KnowledgeBasesKbid401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1KnowledgeBasesKbid401 = {
    /**
     * @type boolean
    */
    success: PutV1KnowledgeBasesKbid401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1KnowledgeBasesKbid403SuccessEnum = {
    "false": false
} as const;

export type PutV1KnowledgeBasesKbid403SuccessEnum = (typeof putV1KnowledgeBasesKbid403SuccessEnum)[keyof typeof putV1KnowledgeBasesKbid403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1KnowledgeBasesKbid403 = {
    /**
     * @type boolean
    */
    success: PutV1KnowledgeBasesKbid403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1KnowledgeBasesKbid404SuccessEnum = {
    "false": false
} as const;

export type PutV1KnowledgeBasesKbid404SuccessEnum = (typeof putV1KnowledgeBasesKbid404SuccessEnum)[keyof typeof putV1KnowledgeBasesKbid404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1KnowledgeBasesKbid404 = {
    /**
     * @type boolean
    */
    success: PutV1KnowledgeBasesKbid404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PutV1KnowledgeBasesKbidMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
};

export type PutV1KnowledgeBasesKbidMutationResponse = PutV1KnowledgeBasesKbid200;

export type PutV1KnowledgeBasesKbidMutation = {
    Response: PutV1KnowledgeBasesKbid200;
    Request: PutV1KnowledgeBasesKbidMutationRequest;
    PathParams: PutV1KnowledgeBasesKbidPathParams;
    Errors: PutV1KnowledgeBasesKbid401 | PutV1KnowledgeBasesKbid403 | PutV1KnowledgeBasesKbid404;
};