/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutV1OrganizationsIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const putV1OrganizationsId200SuccessEnum = {
    "true": true
} as const;

export type PutV1OrganizationsId200SuccessEnum = (typeof putV1OrganizationsId200SuccessEnum)[keyof typeof putV1OrganizationsId200SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId200 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        slug: string;
        /**
         * @type string
        */
        logo: string | null;
        /**
         * @type string
        */
        metadata: string | null;
        /**
         * @type boolean
        */
        isActive: boolean;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1OrganizationsId400SuccessEnum = {
    "false": false
} as const;

export type PutV1OrganizationsId400SuccessEnum = (typeof putV1OrganizationsId400SuccessEnum)[keyof typeof putV1OrganizationsId400SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId400 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1OrganizationsId401SuccessEnum = {
    "false": false
} as const;

export type PutV1OrganizationsId401SuccessEnum = (typeof putV1OrganizationsId401SuccessEnum)[keyof typeof putV1OrganizationsId401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId401 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1OrganizationsId403SuccessEnum = {
    "false": false
} as const;

export type PutV1OrganizationsId403SuccessEnum = (typeof putV1OrganizationsId403SuccessEnum)[keyof typeof putV1OrganizationsId403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId403 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1OrganizationsId404SuccessEnum = {
    "false": false
} as const;

export type PutV1OrganizationsId404SuccessEnum = (typeof putV1OrganizationsId404SuccessEnum)[keyof typeof putV1OrganizationsId404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId404 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1OrganizationsId409SuccessEnum = {
    "false": false
} as const;

export type PutV1OrganizationsId409SuccessEnum = (typeof putV1OrganizationsId409SuccessEnum)[keyof typeof putV1OrganizationsId409SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1OrganizationsId409 = {
    /**
     * @type boolean
    */
    success: PutV1OrganizationsId409SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PutV1OrganizationsIdMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 120
     * @type string | undefined
    */
    name?: string;
    /**
     * @minLength 1
     * @maxLength 60
     * @pattern ^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$
     * @type string | undefined
    */
    slug?: string;
    /**
     * @type string, uri
    */
    logo?: string | null;
    /**
     * @type string
    */
    metadata?: string | null;
};

export type PutV1OrganizationsIdMutationResponse = PutV1OrganizationsId200;

export type PutV1OrganizationsIdMutation = {
    Response: PutV1OrganizationsId200;
    Request: PutV1OrganizationsIdMutationRequest;
    PathParams: PutV1OrganizationsIdPathParams;
    Errors: PutV1OrganizationsId400 | PutV1OrganizationsId401 | PutV1OrganizationsId403 | PutV1OrganizationsId404 | PutV1OrganizationsId409;
};