/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutV1ChallengesIdPathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

export const putV1ChallengesId200SuccessEnum = {
    "true": true
} as const;

export type PutV1ChallengesId200SuccessEnum = (typeof putV1ChallengesId200SuccessEnum)[keyof typeof putV1ChallengesId200SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesId200 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        difficulty: string | null;
        /**
         * @type array
        */
        tags: string[] | null;
        /**
         * @type string
        */
        classroomId: string | null;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1ChallengesId401SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesId401SuccessEnum = (typeof putV1ChallengesId401SuccessEnum)[keyof typeof putV1ChallengesId401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesId401 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesId403SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesId403SuccessEnum = (typeof putV1ChallengesId403SuccessEnum)[keyof typeof putV1ChallengesId403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesId403 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesId404SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesId404SuccessEnum = (typeof putV1ChallengesId404SuccessEnum)[keyof typeof putV1ChallengesId404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesId404 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesIdMutationRequestDifficultyEnum = {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
} as const;

export type PutV1ChallengesIdMutationRequestDifficultyEnum = (typeof putV1ChallengesIdMutationRequestDifficultyEnum)[keyof typeof putV1ChallengesIdMutationRequestDifficultyEnum];

export type PutV1ChallengesIdMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    difficulty?: PutV1ChallengesIdMutationRequestDifficultyEnum;
    /**
     * @type string, uuid
    */
    classroomId?: string | null;
    /**
     * @type array | undefined
    */
    tags?: string[];
    supportMaterials?: any;
    possibleSolutions?: any;
};

export type PutV1ChallengesIdMutationResponse = PutV1ChallengesId200;

export type PutV1ChallengesIdMutation = {
    Response: PutV1ChallengesId200;
    Request: PutV1ChallengesIdMutationRequest;
    PathParams: PutV1ChallengesIdPathParams;
    Errors: PutV1ChallengesId401 | PutV1ChallengesId403 | PutV1ChallengesId404;
};