/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutV1ClassroomsIdPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    id: string;
};

export const putV1ClassroomsId200SuccessEnum = {
    "true": true
} as const;

export type PutV1ClassroomsId200SuccessEnum = (typeof putV1ClassroomsId200SuccessEnum)[keyof typeof putV1ClassroomsId200SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ClassroomsId200 = {
    /**
     * @type boolean
    */
    success: PutV1ClassroomsId200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        id: string;
        /**
         * @type string
        */
        title: string;
        /**
         * @type string
        */
        description: string | null;
        /**
         * @type string
        */
        organizationId: string;
        /**
         * @type string
        */
        teacherUserId: string | null;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1ClassroomsId401SuccessEnum = {
    "false": false
} as const;

export type PutV1ClassroomsId401SuccessEnum = (typeof putV1ClassroomsId401SuccessEnum)[keyof typeof putV1ClassroomsId401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ClassroomsId401 = {
    /**
     * @type boolean
    */
    success: PutV1ClassroomsId401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ClassroomsId403SuccessEnum = {
    "false": false
} as const;

export type PutV1ClassroomsId403SuccessEnum = (typeof putV1ClassroomsId403SuccessEnum)[keyof typeof putV1ClassroomsId403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ClassroomsId403 = {
    /**
     * @type boolean
    */
    success: PutV1ClassroomsId403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ClassroomsId404SuccessEnum = {
    "false": false
} as const;

export type PutV1ClassroomsId404SuccessEnum = (typeof putV1ClassroomsId404SuccessEnum)[keyof typeof putV1ClassroomsId404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ClassroomsId404 = {
    /**
     * @type boolean
    */
    success: PutV1ClassroomsId404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export type PutV1ClassroomsIdMutationRequest = {
    /**
     * @minLength 1
     * @maxLength 200
     * @type string | undefined
    */
    title?: string;
    /**
     * @maxLength 2000
     * @type string
    */
    description?: string | null;
    /**
     * @minLength 1
     * @type string
    */
    teacherUserId?: string | null;
};

export type PutV1ClassroomsIdMutationResponse = PutV1ClassroomsId200;

export type PutV1ClassroomsIdMutation = {
    Response: PutV1ClassroomsId200;
    Request: PutV1ClassroomsIdMutationRequest;
    PathParams: PutV1ClassroomsIdPathParams;
    Errors: PutV1ClassroomsId401 | PutV1ClassroomsId403 | PutV1ClassroomsId404;
};