/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const putV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum];

export type PutV1ChallengesChallengeidReferenceSolutionsKindPathParams = {
    /**
     * @minLength 1
     * @type string
    */
    challengeId: string;
    /**
     * @type string
    */
    kind: PutV1ChallengesChallengeidReferenceSolutionsKindPathParamsKindEnum;
};

export const putV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum = {
    "true": true
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum];

export const dataKindEnum2 = {
    "brute_force": "brute_force",
    "refined": "refined"
} as const;

export type DataKindEnum2 = (typeof dataKindEnum2)[keyof typeof dataKindEnum2];

export const dataStatusEnum2 = {
    "pending": "pending",
    "running": "running",
    "complete": "complete",
    "failed": "failed"
} as const;

export type DataStatusEnum2 = (typeof dataStatusEnum2)[keyof typeof dataStatusEnum2];

export const dataCreatedByEnum2 = {
    "ai": "ai",
    "manual": "manual"
} as const;

export type DataCreatedByEnum2 = (typeof dataCreatedByEnum2)[keyof typeof dataCreatedByEnum2];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidReferenceSolutionsKind200 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidReferenceSolutionsKind200SuccessEnum;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type object
    */
    data: {
        /**
         * @type string
        */
        kind: DataKindEnum2;
        /**
         * @type string
        */
        language: string;
        /**
         * @type string
        */
        code: string | null;
        /**
         * @type string
        */
        status: DataStatusEnum2;
        /**
         * @type string
        */
        error: string | null;
        /**
         * @type string
        */
        createdBy: DataCreatedByEnum2;
        /**
         * @type string
        */
        generatedAt: string | null;
        /**
         * @type string
        */
        updatedAt: string;
    };
    /**
     * @type object | undefined
    */
    pagination?: {
        /**
         * @type number
        */
        total: number;
        /**
         * @type number
        */
        page: number;
        /**
         * @type number
        */
        perPage: number;
        /**
         * @type number
        */
        totalPages: number;
    };
};

export const putV1ChallengesChallengeidReferenceSolutionsKind400SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKind400SuccessEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKind400SuccessEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKind400SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidReferenceSolutionsKind400 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidReferenceSolutionsKind400SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidReferenceSolutionsKind401 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidReferenceSolutionsKind401SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidReferenceSolutionsKind403 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidReferenceSolutionsKind403SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum = {
    "false": false
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum];

/**
 * @description Default Response
*/
export type PutV1ChallengesChallengeidReferenceSolutionsKind404 = {
    /**
     * @type boolean
    */
    success: PutV1ChallengesChallengeidReferenceSolutionsKind404SuccessEnum;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    errors?: {
        [key: string]: (string[] | string);
    };
};

export const putV1ChallengesChallengeidReferenceSolutionsKindMutationRequestLanguageEnum = {
    "python": "python"
} as const;

export type PutV1ChallengesChallengeidReferenceSolutionsKindMutationRequestLanguageEnum = (typeof putV1ChallengesChallengeidReferenceSolutionsKindMutationRequestLanguageEnum)[keyof typeof putV1ChallengesChallengeidReferenceSolutionsKindMutationRequestLanguageEnum];

export type PutV1ChallengesChallengeidReferenceSolutionsKindMutationRequest = {
    /**
     * @minLength 1
     * @type string
    */
    code: string;
    /**
     * @type string | undefined
    */
    language?: PutV1ChallengesChallengeidReferenceSolutionsKindMutationRequestLanguageEnum;
};

export type PutV1ChallengesChallengeidReferenceSolutionsKindMutationResponse = PutV1ChallengesChallengeidReferenceSolutionsKind200;

export type PutV1ChallengesChallengeidReferenceSolutionsKindMutation = {
    Response: PutV1ChallengesChallengeidReferenceSolutionsKind200;
    Request: PutV1ChallengesChallengeidReferenceSolutionsKindMutationRequest;
    PathParams: PutV1ChallengesChallengeidReferenceSolutionsKindPathParams;
    Errors: PutV1ChallengesChallengeidReferenceSolutionsKind400 | PutV1ChallengesChallengeidReferenceSolutionsKind401 | PutV1ChallengesChallengeidReferenceSolutionsKind403 | PutV1ChallengesChallengeidReferenceSolutionsKind404;
};