/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1OrganizationsIdMembersUseridMutationResponse, DeleteV1OrganizationsIdMembersUseridPathParams, DeleteV1OrganizationsIdMembersUserid401, DeleteV1OrganizationsIdMembersUserid403, DeleteV1OrganizationsIdMembersUserid404, DeleteV1OrganizationsIdMembersUserid409 } from "../../../../../../packages/types/kubb/DeleteV1OrganizationsIdMembersUserid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1OrganizationsIdMembersUseridMutationKey = () => [{ url: '/v1/organizations/:id/members/:userId' }] as const

export type DeleteV1OrganizationsIdMembersUseridMutationKey = ReturnType<typeof deleteV1OrganizationsIdMembersUseridMutationKey>

/**
 * @description Removes a user from an organization. Blocks removal of the last admin so the org never ends up unmanageable.
 * @summary Remove member from organization (admin)
 * {@link /v1/organizations/:id/members/:userId}
 */
export async function deleteV1OrganizationsIdMembersUserid(id: DeleteV1OrganizationsIdMembersUseridPathParams["id"], userId: DeleteV1OrganizationsIdMembersUseridPathParams["userId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdMembersUserid401 | DeleteV1OrganizationsIdMembersUserid403 | DeleteV1OrganizationsIdMembersUserid404 | DeleteV1OrganizationsIdMembersUserid409>, unknown>({ method : "DELETE", url : `/v1/organizations/${id}/members/${userId}`, ... requestConfig })  
  return res.data
}

/**
 * @description Removes a user from an organization. Blocks removal of the last admin so the org never ends up unmanageable.
 * @summary Remove member from organization (admin)
 * {@link /v1/organizations/:id/members/:userId}
 */
export function useDeleteV1OrganizationsIdMembersUserid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdMembersUserid401 | DeleteV1OrganizationsIdMembersUserid403 | DeleteV1OrganizationsIdMembersUserid404 | DeleteV1OrganizationsIdMembersUserid409>, {id: DeleteV1OrganizationsIdMembersUseridPathParams["id"], userId: DeleteV1OrganizationsIdMembersUseridPathParams["userId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1OrganizationsIdMembersUseridMutationKey()

  return useMutation<DeleteV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdMembersUserid401 | DeleteV1OrganizationsIdMembersUserid403 | DeleteV1OrganizationsIdMembersUserid404 | DeleteV1OrganizationsIdMembersUserid409>, {id: DeleteV1OrganizationsIdMembersUseridPathParams["id"], userId: DeleteV1OrganizationsIdMembersUseridPathParams["userId"]}, TContext>({
    mutationFn: async({ id, userId }) => {
      return deleteV1OrganizationsIdMembersUserid(id, userId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}