/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1OrganizationsIdInvitationsInvitationidMutationResponse, DeleteV1OrganizationsIdInvitationsInvitationidPathParams, DeleteV1OrganizationsIdInvitationsInvitationid401, DeleteV1OrganizationsIdInvitationsInvitationid403, DeleteV1OrganizationsIdInvitationsInvitationid404 } from "../../../../../../packages/types/kubb/DeleteV1OrganizationsIdInvitationsInvitationid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1OrganizationsIdInvitationsInvitationidMutationKey = () => [{ url: '/v1/organizations/:id/invitations/:invitationId' }] as const

export type DeleteV1OrganizationsIdInvitationsInvitationidMutationKey = ReturnType<typeof deleteV1OrganizationsIdInvitationsInvitationidMutationKey>

/**
 * @description Cancel a pending invitation. Requires coordinator+ role.
 * @summary Cancel invitation
 * {@link /v1/organizations/:id/invitations/:invitationId}
 */
export async function deleteV1OrganizationsIdInvitationsInvitationid(id: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["id"], invitationId: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["invitationId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1OrganizationsIdInvitationsInvitationidMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdInvitationsInvitationid401 | DeleteV1OrganizationsIdInvitationsInvitationid403 | DeleteV1OrganizationsIdInvitationsInvitationid404>, unknown>({ method : "DELETE", url : `/v1/organizations/${id}/invitations/${invitationId}`, ... requestConfig })  
  return res.data
}

/**
 * @description Cancel a pending invitation. Requires coordinator+ role.
 * @summary Cancel invitation
 * {@link /v1/organizations/:id/invitations/:invitationId}
 */
export function useDeleteV1OrganizationsIdInvitationsInvitationid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1OrganizationsIdInvitationsInvitationidMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdInvitationsInvitationid401 | DeleteV1OrganizationsIdInvitationsInvitationid403 | DeleteV1OrganizationsIdInvitationsInvitationid404>, {id: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["id"], invitationId: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["invitationId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1OrganizationsIdInvitationsInvitationidMutationKey()

  return useMutation<DeleteV1OrganizationsIdInvitationsInvitationidMutationResponse, ResponseErrorConfig<DeleteV1OrganizationsIdInvitationsInvitationid401 | DeleteV1OrganizationsIdInvitationsInvitationid403 | DeleteV1OrganizationsIdInvitationsInvitationid404>, {id: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["id"], invitationId: DeleteV1OrganizationsIdInvitationsInvitationidPathParams["invitationId"]}, TContext>({
    mutationFn: async({ id, invitationId }) => {
      return deleteV1OrganizationsIdInvitationsInvitationid(id, invitationId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}