/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetV1OrganizationsIdQueryResponse, GetV1OrganizationsIdPathParams, GetV1OrganizationsId401, GetV1OrganizationsId403, GetV1OrganizationsId404 } from "../../../../../../packages/types/kubb/GetV1OrganizationsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1OrganizationsIdSuspenseQueryKey = (id: GetV1OrganizationsIdPathParams["id"]) => [{ url: '/v1/organizations/:id', params: {id:id} }] as const

export type GetV1OrganizationsIdSuspenseQueryKey = ReturnType<typeof getV1OrganizationsIdSuspenseQueryKey>

/**
 * @description Returns a single organization with member and domain counts. Platform admin can fetch any org; otherwise requires membership.
 * @summary Get organization by ID
 * {@link /v1/organizations/:id}
 */
export async function getV1OrganizationsIdSuspense(id: GetV1OrganizationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1OrganizationsIdQueryResponse, ResponseErrorConfig<GetV1OrganizationsId401 | GetV1OrganizationsId403 | GetV1OrganizationsId404>, unknown>({ method : "GET", url : `/v1/organizations/${id}`, ... requestConfig })  
  return res.data
}

export function getV1OrganizationsIdSuspenseQueryOptions(id: GetV1OrganizationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1OrganizationsIdSuspenseQueryKey(id)
  return queryOptions<GetV1OrganizationsIdQueryResponse, ResponseErrorConfig<GetV1OrganizationsId401 | GetV1OrganizationsId403 | GetV1OrganizationsId404>, GetV1OrganizationsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1OrganizationsIdSuspense(id, config)
   },
  })
}

/**
 * @description Returns a single organization with member and domain counts. Platform admin can fetch any org; otherwise requires membership.
 * @summary Get organization by ID
 * {@link /v1/organizations/:id}
 */
export function useGetV1OrganizationsIdSuspense<TData = GetV1OrganizationsIdQueryResponse, TQueryKey extends QueryKey = GetV1OrganizationsIdSuspenseQueryKey>(id: GetV1OrganizationsIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1OrganizationsIdQueryResponse, ResponseErrorConfig<GetV1OrganizationsId401 | GetV1OrganizationsId403 | GetV1OrganizationsId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1OrganizationsIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getV1OrganizationsIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1OrganizationsId401 | GetV1OrganizationsId403 | GetV1OrganizationsId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}