/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetV1OrganizationsQueryResponse, GetV1OrganizationsQueryParams, GetV1Organizations401, GetV1Organizations403 } from "../../../../../../packages/types/kubb/GetV1Organizations.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1OrganizationsSuspenseQueryKey = (params?: GetV1OrganizationsQueryParams) => [{ url: '/v1/organizations/' }, ...(params ? [params] : [])] as const

export type GetV1OrganizationsSuspenseQueryKey = ReturnType<typeof getV1OrganizationsSuspenseQueryKey>

/**
 * @description Paginated list of organizations with member counts. Requires platform admin. Inactive orgs hidden by default.
 * @summary List organizations (platform admin)
 * {@link /v1/organizations/}
 */
export async function getV1OrganizationsSuspense(params?: GetV1OrganizationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1OrganizationsQueryResponse, ResponseErrorConfig<GetV1Organizations401 | GetV1Organizations403>, unknown>({ method : "GET", url : `/v1/organizations/`, params, ... requestConfig })  
  return res.data
}

export function getV1OrganizationsSuspenseQueryOptions(params?: GetV1OrganizationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1OrganizationsSuspenseQueryKey(params)
  return queryOptions<GetV1OrganizationsQueryResponse, ResponseErrorConfig<GetV1Organizations401 | GetV1Organizations403>, GetV1OrganizationsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1OrganizationsSuspense(params, config)
   },
  })
}

/**
 * @description Paginated list of organizations with member counts. Requires platform admin. Inactive orgs hidden by default.
 * @summary List organizations (platform admin)
 * {@link /v1/organizations/}
 */
export function useGetV1OrganizationsSuspense<TData = GetV1OrganizationsQueryResponse, TQueryKey extends QueryKey = GetV1OrganizationsSuspenseQueryKey>(params?: GetV1OrganizationsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1OrganizationsQueryResponse, ResponseErrorConfig<GetV1Organizations401 | GetV1Organizations403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1OrganizationsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1OrganizationsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1Organizations401 | GetV1Organizations403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}