/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1OrganizationsIdEmailDomainsQueryResponse, GetV1OrganizationsIdEmailDomainsPathParams, GetV1OrganizationsIdEmailDomains401, GetV1OrganizationsIdEmailDomains403, GetV1OrganizationsIdEmailDomains404 } from "../../../../../../packages/types/kubb/GetV1OrganizationsIdEmailDomains.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1OrganizationsIdEmailDomainsQueryKey = (id: GetV1OrganizationsIdEmailDomainsPathParams["id"]) => [{ url: '/v1/organizations/:id/email-domains', params: {id:id} }] as const

export type GetV1OrganizationsIdEmailDomainsQueryKey = ReturnType<typeof getV1OrganizationsIdEmailDomainsQueryKey>

/**
 * @description List the email domain auto-assignment rules for the organization. Allowed for platform admins or coordinators of the organization.
 * @summary List email domain rules
 * {@link /v1/organizations/:id/email-domains}
 */
export async function getV1OrganizationsIdEmailDomains(id: GetV1OrganizationsIdEmailDomainsPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1OrganizationsIdEmailDomainsQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdEmailDomains401 | GetV1OrganizationsIdEmailDomains403 | GetV1OrganizationsIdEmailDomains404>, unknown>({ method : "GET", url : `/v1/organizations/${id}/email-domains`, ... requestConfig })  
  return res.data
}

export function getV1OrganizationsIdEmailDomainsQueryOptions(id: GetV1OrganizationsIdEmailDomainsPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1OrganizationsIdEmailDomainsQueryKey(id)
  return queryOptions<GetV1OrganizationsIdEmailDomainsQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdEmailDomains401 | GetV1OrganizationsIdEmailDomains403 | GetV1OrganizationsIdEmailDomains404>, GetV1OrganizationsIdEmailDomainsQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1OrganizationsIdEmailDomains(id, config)
   },
  })
}

/**
 * @description List the email domain auto-assignment rules for the organization. Allowed for platform admins or coordinators of the organization.
 * @summary List email domain rules
 * {@link /v1/organizations/:id/email-domains}
 */
export function useGetV1OrganizationsIdEmailDomains<TData = GetV1OrganizationsIdEmailDomainsQueryResponse, TQueryData = GetV1OrganizationsIdEmailDomainsQueryResponse, TQueryKey extends QueryKey = GetV1OrganizationsIdEmailDomainsQueryKey>(id: GetV1OrganizationsIdEmailDomainsPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetV1OrganizationsIdEmailDomainsQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdEmailDomains401 | GetV1OrganizationsIdEmailDomains403 | GetV1OrganizationsIdEmailDomains404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1OrganizationsIdEmailDomainsQueryKey(id)

  const query = useQuery({
   ...getV1OrganizationsIdEmailDomainsQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1OrganizationsIdEmailDomains401 | GetV1OrganizationsIdEmailDomains403 | GetV1OrganizationsIdEmailDomains404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}