/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1OrganizationsIdMembersQueryResponse, GetV1OrganizationsIdMembersPathParams, GetV1OrganizationsIdMembers401, GetV1OrganizationsIdMembers403, GetV1OrganizationsIdMembers404 } from "../../../../../../packages/types/kubb/GetV1OrganizationsIdMembers.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1OrganizationsIdMembersQueryKey = (id: GetV1OrganizationsIdMembersPathParams["id"]) => [{ url: '/v1/organizations/:id/members', params: {id:id} }] as const

export type GetV1OrganizationsIdMembersQueryKey = ReturnType<typeof getV1OrganizationsIdMembersQueryKey>

/**
 * @description List members of an organization. Requires teacher+ role. Organization ID must match active organization.
 * @summary List organization members
 * {@link /v1/organizations/:id/members}
 */
export async function getV1OrganizationsIdMembers(id: GetV1OrganizationsIdMembersPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1OrganizationsIdMembersQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdMembers401 | GetV1OrganizationsIdMembers403 | GetV1OrganizationsIdMembers404>, unknown>({ method : "GET", url : `/v1/organizations/${id}/members`, ... requestConfig })  
  return res.data
}

export function getV1OrganizationsIdMembersQueryOptions(id: GetV1OrganizationsIdMembersPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1OrganizationsIdMembersQueryKey(id)
  return queryOptions<GetV1OrganizationsIdMembersQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdMembers401 | GetV1OrganizationsIdMembers403 | GetV1OrganizationsIdMembers404>, GetV1OrganizationsIdMembersQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1OrganizationsIdMembers(id, config)
   },
  })
}

/**
 * @description List members of an organization. Requires teacher+ role. Organization ID must match active organization.
 * @summary List organization members
 * {@link /v1/organizations/:id/members}
 */
export function useGetV1OrganizationsIdMembers<TData = GetV1OrganizationsIdMembersQueryResponse, TQueryData = GetV1OrganizationsIdMembersQueryResponse, TQueryKey extends QueryKey = GetV1OrganizationsIdMembersQueryKey>(id: GetV1OrganizationsIdMembersPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetV1OrganizationsIdMembersQueryResponse, ResponseErrorConfig<GetV1OrganizationsIdMembers401 | GetV1OrganizationsIdMembers403 | GetV1OrganizationsIdMembers404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1OrganizationsIdMembersQueryKey(id)

  const query = useQuery({
   ...getV1OrganizationsIdMembersQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1OrganizationsIdMembers401 | GetV1OrganizationsIdMembers403 | GetV1OrganizationsIdMembers404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}