/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1OrganizationsIdInvitationsInvitationidResendMutationResponse, PostV1OrganizationsIdInvitationsInvitationidResendPathParams, PostV1OrganizationsIdInvitationsInvitationidResend401, PostV1OrganizationsIdInvitationsInvitationidResend403, PostV1OrganizationsIdInvitationsInvitationidResend404, PostV1OrganizationsIdInvitationsInvitationidResend409, PostV1OrganizationsIdInvitationsInvitationidResend500 } from "../../../../../../packages/types/kubb/PostV1OrganizationsIdInvitationsInvitationidResend.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1OrganizationsIdInvitationsInvitationidResendMutationKey = () => [{ url: '/v1/organizations/:id/invitations/:invitationId/resend' }] as const

export type PostV1OrganizationsIdInvitationsInvitationidResendMutationKey = ReturnType<typeof postV1OrganizationsIdInvitationsInvitationidResendMutationKey>

/**
 * @description Resend a pending invitation email. Renews expiresAt to NOW() + 7 days and re-dispatches the email. Idempotent: re-calling on a pending invitation simply re-extends the TTL and re-sends the email. Non-pending invitations (accepted/canceled/expired/rejected) return 409.
 * @summary Resend invitation
 * {@link /v1/organizations/:id/invitations/:invitationId/resend}
 */
export async function postV1OrganizationsIdInvitationsInvitationidResend(id: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["id"], invitationId: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["invitationId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1OrganizationsIdInvitationsInvitationidResendMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitationsInvitationidResend401 | PostV1OrganizationsIdInvitationsInvitationidResend403 | PostV1OrganizationsIdInvitationsInvitationidResend404 | PostV1OrganizationsIdInvitationsInvitationidResend409 | PostV1OrganizationsIdInvitationsInvitationidResend500>, unknown>({ method : "POST", url : `/v1/organizations/${id}/invitations/${invitationId}/resend`, ... requestConfig })  
  return res.data
}

/**
 * @description Resend a pending invitation email. Renews expiresAt to NOW() + 7 days and re-dispatches the email. Idempotent: re-calling on a pending invitation simply re-extends the TTL and re-sends the email. Non-pending invitations (accepted/canceled/expired/rejected) return 409.
 * @summary Resend invitation
 * {@link /v1/organizations/:id/invitations/:invitationId/resend}
 */
export function usePostV1OrganizationsIdInvitationsInvitationidResend<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1OrganizationsIdInvitationsInvitationidResendMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitationsInvitationidResend401 | PostV1OrganizationsIdInvitationsInvitationidResend403 | PostV1OrganizationsIdInvitationsInvitationidResend404 | PostV1OrganizationsIdInvitationsInvitationidResend409 | PostV1OrganizationsIdInvitationsInvitationidResend500>, {id: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["id"], invitationId: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["invitationId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1OrganizationsIdInvitationsInvitationidResendMutationKey()

  return useMutation<PostV1OrganizationsIdInvitationsInvitationidResendMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitationsInvitationidResend401 | PostV1OrganizationsIdInvitationsInvitationidResend403 | PostV1OrganizationsIdInvitationsInvitationidResend404 | PostV1OrganizationsIdInvitationsInvitationidResend409 | PostV1OrganizationsIdInvitationsInvitationidResend500>, {id: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["id"], invitationId: PostV1OrganizationsIdInvitationsInvitationidResendPathParams["invitationId"]}, TContext>({
    mutationFn: async({ id, invitationId }) => {
      return postV1OrganizationsIdInvitationsInvitationidResend(id, invitationId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}