/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1OrganizationsIdEmailDomainsMutationRequest, PostV1OrganizationsIdEmailDomainsMutationResponse, PostV1OrganizationsIdEmailDomainsPathParams, PostV1OrganizationsIdEmailDomains400, PostV1OrganizationsIdEmailDomains401, PostV1OrganizationsIdEmailDomains403, PostV1OrganizationsIdEmailDomains404, PostV1OrganizationsIdEmailDomains409 } from "../../../../../../packages/types/kubb/PostV1OrganizationsIdEmailDomains.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1OrganizationsIdEmailDomainsMutationKey = () => [{ url: '/v1/organizations/:id/email-domains' }] as const

export type PostV1OrganizationsIdEmailDomainsMutationKey = ReturnType<typeof postV1OrganizationsIdEmailDomainsMutationKey>

/**
 * @description Create an email domain auto-assignment rule for the organization. UNIQUE(domain, role) is global across all organizations. Allowed for platform admins or coordinators of the organization.
 * @summary Create email domain rule
 * {@link /v1/organizations/:id/email-domains}
 */
export async function postV1OrganizationsIdEmailDomains(id: PostV1OrganizationsIdEmailDomainsPathParams["id"], data: PostV1OrganizationsIdEmailDomainsMutationRequest, config: Partial<RequestConfig<PostV1OrganizationsIdEmailDomainsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1OrganizationsIdEmailDomainsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdEmailDomains400 | PostV1OrganizationsIdEmailDomains401 | PostV1OrganizationsIdEmailDomains403 | PostV1OrganizationsIdEmailDomains404 | PostV1OrganizationsIdEmailDomains409>, PostV1OrganizationsIdEmailDomainsMutationRequest>({ method : "POST", url : `/v1/organizations/${id}/email-domains`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Create an email domain auto-assignment rule for the organization. UNIQUE(domain, role) is global across all organizations. Allowed for platform admins or coordinators of the organization.
 * @summary Create email domain rule
 * {@link /v1/organizations/:id/email-domains}
 */
export function usePostV1OrganizationsIdEmailDomains<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1OrganizationsIdEmailDomainsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdEmailDomains400 | PostV1OrganizationsIdEmailDomains401 | PostV1OrganizationsIdEmailDomains403 | PostV1OrganizationsIdEmailDomains404 | PostV1OrganizationsIdEmailDomains409>, {id: PostV1OrganizationsIdEmailDomainsPathParams["id"], data: PostV1OrganizationsIdEmailDomainsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1OrganizationsIdEmailDomainsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1OrganizationsIdEmailDomainsMutationKey()

  return useMutation<PostV1OrganizationsIdEmailDomainsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdEmailDomains400 | PostV1OrganizationsIdEmailDomains401 | PostV1OrganizationsIdEmailDomains403 | PostV1OrganizationsIdEmailDomains404 | PostV1OrganizationsIdEmailDomains409>, {id: PostV1OrganizationsIdEmailDomainsPathParams["id"], data: PostV1OrganizationsIdEmailDomainsMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1OrganizationsIdEmailDomains(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}