/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PutV1OrganizationsIdMutationRequest, PutV1OrganizationsIdMutationResponse, PutV1OrganizationsIdPathParams, PutV1OrganizationsId400, PutV1OrganizationsId401, PutV1OrganizationsId403, PutV1OrganizationsId404, PutV1OrganizationsId409 } from "../../../../../../packages/types/kubb/PutV1OrganizationsId.ts";
import { useMutation } from "@tanstack/react-query";

export const putV1OrganizationsIdMutationKey = () => [{ url: '/v1/organizations/:id' }] as const

export type PutV1OrganizationsIdMutationKey = ReturnType<typeof putV1OrganizationsIdMutationKey>

/**
 * @description Updates name, slug, logo and/or metadata. Slug uniqueness is enforced.
 * @summary Update organization (platform admin)
 * {@link /v1/organizations/:id}
 */
export async function putV1OrganizationsId(id: PutV1OrganizationsIdPathParams["id"], data?: PutV1OrganizationsIdMutationRequest, config: Partial<RequestConfig<PutV1OrganizationsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutV1OrganizationsIdMutationResponse, ResponseErrorConfig<PutV1OrganizationsId400 | PutV1OrganizationsId401 | PutV1OrganizationsId403 | PutV1OrganizationsId404 | PutV1OrganizationsId409>, PutV1OrganizationsIdMutationRequest>({ method : "PUT", url : `/v1/organizations/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Updates name, slug, logo and/or metadata. Slug uniqueness is enforced.
 * @summary Update organization (platform admin)
 * {@link /v1/organizations/:id}
 */
export function usePutV1OrganizationsId<TContext>(options: 
{
  mutation?: UseMutationOptions<PutV1OrganizationsIdMutationResponse, ResponseErrorConfig<PutV1OrganizationsId400 | PutV1OrganizationsId401 | PutV1OrganizationsId403 | PutV1OrganizationsId404 | PutV1OrganizationsId409>, {id: PutV1OrganizationsIdPathParams["id"], data?: PutV1OrganizationsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutV1OrganizationsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putV1OrganizationsIdMutationKey()

  return useMutation<PutV1OrganizationsIdMutationResponse, ResponseErrorConfig<PutV1OrganizationsId400 | PutV1OrganizationsId401 | PutV1OrganizationsId403 | PutV1OrganizationsId404 | PutV1OrganizationsId409>, {id: PutV1OrganizationsIdPathParams["id"], data?: PutV1OrganizationsIdMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return putV1OrganizationsId(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}