/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1OrganizationsIdInvitationsMutationRequest, PostV1OrganizationsIdInvitationsMutationResponse, PostV1OrganizationsIdInvitationsPathParams, PostV1OrganizationsIdInvitations400, PostV1OrganizationsIdInvitations401, PostV1OrganizationsIdInvitations403 } from "../../../../../../packages/types/kubb/PostV1OrganizationsIdInvitations.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1OrganizationsIdInvitationsMutationKey = () => [{ url: '/v1/organizations/:id/invitations' }] as const

export type PostV1OrganizationsIdInvitationsMutationKey = ReturnType<typeof postV1OrganizationsIdInvitationsMutationKey>

/**
 * @description Invite a user to the organization by email. Requires coordinator+ role.
 * @summary Create invitation
 * {@link /v1/organizations/:id/invitations}
 */
export async function postV1OrganizationsIdInvitations(id: PostV1OrganizationsIdInvitationsPathParams["id"], data: PostV1OrganizationsIdInvitationsMutationRequest, config: Partial<RequestConfig<PostV1OrganizationsIdInvitationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1OrganizationsIdInvitationsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitations400 | PostV1OrganizationsIdInvitations401 | PostV1OrganizationsIdInvitations403 | PostV1OrganizationsIdInvitations409>, PostV1OrganizationsIdInvitationsMutationRequest>({ method : "POST", url : `/v1/organizations/${id}/invitations`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Invite a user to the organization by email. Requires coordinator+ role.
 * @summary Create invitation
 * {@link /v1/organizations/:id/invitations}
 */
export function usePostV1OrganizationsIdInvitations<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1OrganizationsIdInvitationsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitations400 | PostV1OrganizationsIdInvitations401 | PostV1OrganizationsIdInvitations403 | PostV1OrganizationsIdInvitations409>, {id: PostV1OrganizationsIdInvitationsPathParams["id"], data: PostV1OrganizationsIdInvitationsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1OrganizationsIdInvitationsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1OrganizationsIdInvitationsMutationKey()

  return useMutation<PostV1OrganizationsIdInvitationsMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdInvitations400 | PostV1OrganizationsIdInvitations401 | PostV1OrganizationsIdInvitations403 | PostV1OrganizationsIdInvitations409>, {id: PostV1OrganizationsIdInvitationsPathParams["id"], data: PostV1OrganizationsIdInvitationsMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1OrganizationsIdInvitations(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}