/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1OrganizationsIdMembersMutationRequest, PostV1OrganizationsIdMembersMutationResponse, PostV1OrganizationsIdMembersPathParams, PostV1OrganizationsIdMembers400, PostV1OrganizationsIdMembers401, PostV1OrganizationsIdMembers403, PostV1OrganizationsIdMembers404, PostV1OrganizationsIdMembers409 } from "../../../../../../packages/types/kubb/PostV1OrganizationsIdMembers.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1OrganizationsIdMembersMutationKey = () => [{ url: '/v1/organizations/:id/members' }] as const

export type PostV1OrganizationsIdMembersMutationKey = ReturnType<typeof postV1OrganizationsIdMembersMutationKey>

/**
 * @description Adds an existing user as a member of the target organization. Looks up the user by email and inserts a member row directly, bypassing Better Auth's membership limit. Returns 404 when the user does not exist and 409 when already a member.
 * @summary Link existing user to organization (admin)
 * {@link /v1/organizations/:id/members}
 */
export async function postV1OrganizationsIdMembers(id: PostV1OrganizationsIdMembersPathParams["id"], data: PostV1OrganizationsIdMembersMutationRequest, config: Partial<RequestConfig<PostV1OrganizationsIdMembersMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1OrganizationsIdMembersMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdMembers400 | PostV1OrganizationsIdMembers401 | PostV1OrganizationsIdMembers403 | PostV1OrganizationsIdMembers404 | PostV1OrganizationsIdMembers409>, PostV1OrganizationsIdMembersMutationRequest>({ method : "POST", url : `/v1/organizations/${id}/members`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Adds an existing user as a member of the target organization. Looks up the user by email and inserts a member row directly, bypassing Better Auth's membership limit. Returns 404 when the user does not exist and 409 when already a member.
 * @summary Link existing user to organization (admin)
 * {@link /v1/organizations/:id/members}
 */
export function usePostV1OrganizationsIdMembers<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1OrganizationsIdMembersMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdMembers400 | PostV1OrganizationsIdMembers401 | PostV1OrganizationsIdMembers403 | PostV1OrganizationsIdMembers404 | PostV1OrganizationsIdMembers409>, {id: PostV1OrganizationsIdMembersPathParams["id"], data: PostV1OrganizationsIdMembersMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1OrganizationsIdMembersMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1OrganizationsIdMembersMutationKey()

  return useMutation<PostV1OrganizationsIdMembersMutationResponse, ResponseErrorConfig<PostV1OrganizationsIdMembers400 | PostV1OrganizationsIdMembers401 | PostV1OrganizationsIdMembers403 | PostV1OrganizationsIdMembers404 | PostV1OrganizationsIdMembers409>, {id: PostV1OrganizationsIdMembersPathParams["id"], data: PostV1OrganizationsIdMembersMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1OrganizationsIdMembers(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}