/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PutV1OrganizationsIdMembersUseridMutationRequest, PutV1OrganizationsIdMembersUseridMutationResponse, PutV1OrganizationsIdMembersUseridPathParams, PutV1OrganizationsIdMembersUserid400, PutV1OrganizationsIdMembersUserid401, PutV1OrganizationsIdMembersUserid403, PutV1OrganizationsIdMembersUserid404 } from "../../../../../../packages/types/kubb/PutV1OrganizationsIdMembersUserid.ts";
import { useMutation } from "@tanstack/react-query";

export const putV1OrganizationsIdMembersUseridMutationKey = () => [{ url: '/v1/organizations/:id/members/:userId' }] as const

export type PutV1OrganizationsIdMembersUseridMutationKey = ReturnType<typeof putV1OrganizationsIdMembersUseridMutationKey>

/**
 * @description Update a member's role in the organization. Requires coordinator+ role.
 * @summary Update member role
 * {@link /v1/organizations/:id/members/:userId}
 */
export async function putV1OrganizationsIdMembersUserid(id: PutV1OrganizationsIdMembersUseridPathParams["id"], userId: PutV1OrganizationsIdMembersUseridPathParams["userId"], data: PutV1OrganizationsIdMembersUseridMutationRequest, config: Partial<RequestConfig<PutV1OrganizationsIdMembersUseridMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<PutV1OrganizationsIdMembersUserid400 | PutV1OrganizationsIdMembersUserid401 | PutV1OrganizationsIdMembersUserid403 | PutV1OrganizationsIdMembersUserid404>, PutV1OrganizationsIdMembersUseridMutationRequest>({ method : "PUT", url : `/v1/organizations/${id}/members/${userId}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Update a member's role in the organization. Requires coordinator+ role.
 * @summary Update member role
 * {@link /v1/organizations/:id/members/:userId}
 */
export function usePutV1OrganizationsIdMembersUserid<TContext>(options: 
{
  mutation?: UseMutationOptions<PutV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<PutV1OrganizationsIdMembersUserid400 | PutV1OrganizationsIdMembersUserid401 | PutV1OrganizationsIdMembersUserid403 | PutV1OrganizationsIdMembersUserid404>, {id: PutV1OrganizationsIdMembersUseridPathParams["id"], userId: PutV1OrganizationsIdMembersUseridPathParams["userId"], data: PutV1OrganizationsIdMembersUseridMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutV1OrganizationsIdMembersUseridMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putV1OrganizationsIdMembersUseridMutationKey()

  return useMutation<PutV1OrganizationsIdMembersUseridMutationResponse, ResponseErrorConfig<PutV1OrganizationsIdMembersUserid400 | PutV1OrganizationsIdMembersUserid401 | PutV1OrganizationsIdMembersUserid403 | PutV1OrganizationsIdMembersUserid404>, {id: PutV1OrganizationsIdMembersUseridPathParams["id"], userId: PutV1OrganizationsIdMembersUseridPathParams["userId"], data: PutV1OrganizationsIdMembersUseridMutationRequest}, TContext>({
    mutationFn: async({ id, userId, data }) => {
      return putV1OrganizationsIdMembersUserid(id, userId, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}