/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1OrganizationsMutationRequest, PostV1OrganizationsMutationResponse, PostV1Organizations400, PostV1Organizations401, PostV1Organizations403, PostV1Organizations409 } from "../../../../../../packages/types/kubb/PostV1Organizations.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1OrganizationsMutationKey = () => [{ url: '/v1/organizations/' }] as const

export type PostV1OrganizationsMutationKey = ReturnType<typeof postV1OrganizationsMutationKey>

/**
 * @description Creates a new organization via Better Auth. The platform admin who calls this endpoint becomes the org's first admin (creatorRole=admin).
 * @summary Create organization (platform admin)
 * {@link /v1/organizations/}
 */
export async function postV1Organizations(data: PostV1OrganizationsMutationRequest, config: Partial<RequestConfig<PostV1OrganizationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1OrganizationsMutationResponse, ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations401 | PostV1Organizations403 | PostV1Organizations409>, PostV1OrganizationsMutationRequest>({ method : "POST", url : `/v1/organizations/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Creates a new organization via Better Auth. The platform admin who calls this endpoint becomes the org's first admin (creatorRole=admin).
 * @summary Create organization (platform admin)
 * {@link /v1/organizations/}
 */
export function usePostV1Organizations<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1OrganizationsMutationResponse, ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations401 | PostV1Organizations403 | PostV1Organizations409>, {data: PostV1OrganizationsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1OrganizationsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1OrganizationsMutationKey()

  return useMutation<PostV1OrganizationsMutationResponse, ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations401 | PostV1Organizations403 | PostV1Organizations409>, {data: PostV1OrganizationsMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1Organizations(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}