/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1ChallengesChallengeidSubmissionsQueryResponse, GetV1ChallengesChallengeidSubmissionsPathParams, GetV1ChallengesChallengeidSubmissionsQueryParams, GetV1ChallengesChallengeidSubmissions401, GetV1ChallengesChallengeidSubmissions403, GetV1ChallengesChallengeidSubmissions404 } from "../../../../../../packages/types/kubb/GetV1ChallengesChallengeidSubmissions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ChallengesChallengeidSubmissionsQueryKey = (challengeId: GetV1ChallengesChallengeidSubmissionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidSubmissionsQueryParams) => [{ url: '/v1/challenges/:challengeId/submissions/', params: {challengeId:challengeId} }, ...(params ? [params] : [])] as const

export type GetV1ChallengesChallengeidSubmissionsQueryKey = ReturnType<typeof getV1ChallengesChallengeidSubmissionsQueryKey>

/**
 * @description Paginated list of student submissions for a challenge. Same access rules as work-session list: teacher (creator or classroom lead), coordinator+ in org.
 * @summary List submissions for a challenge (staff)
 * {@link /v1/challenges/:challengeId/submissions/}
 */
export async function getV1ChallengesChallengeidSubmissions(challengeId: GetV1ChallengesChallengeidSubmissionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidSubmissionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesChallengeidSubmissionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidSubmissions401 | GetV1ChallengesChallengeidSubmissions403 | GetV1ChallengesChallengeidSubmissions404>, unknown>({ method : "GET", url : `/v1/challenges/${challengeId}/submissions/`, params, ... requestConfig })  
  return res.data
}

export function getV1ChallengesChallengeidSubmissionsQueryOptions(challengeId: GetV1ChallengesChallengeidSubmissionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidSubmissionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesChallengeidSubmissionsQueryKey(challengeId, params)
  return queryOptions<GetV1ChallengesChallengeidSubmissionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidSubmissions401 | GetV1ChallengesChallengeidSubmissions403 | GetV1ChallengesChallengeidSubmissions404>, GetV1ChallengesChallengeidSubmissionsQueryResponse, typeof queryKey>({
   enabled: !!(challengeId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesChallengeidSubmissions(challengeId, params, config)
   },
  })
}

/**
 * @description Paginated list of student submissions for a challenge. Same access rules as work-session list: teacher (creator or classroom lead), coordinator+ in org.
 * @summary List submissions for a challenge (staff)
 * {@link /v1/challenges/:challengeId/submissions/}
 */
export function useGetV1ChallengesChallengeidSubmissions<TData = GetV1ChallengesChallengeidSubmissionsQueryResponse, TQueryData = GetV1ChallengesChallengeidSubmissionsQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesChallengeidSubmissionsQueryKey>(challengeId: GetV1ChallengesChallengeidSubmissionsPathParams["challengeId"], params?: GetV1ChallengesChallengeidSubmissionsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetV1ChallengesChallengeidSubmissionsQueryResponse, ResponseErrorConfig<GetV1ChallengesChallengeidSubmissions401 | GetV1ChallengesChallengeidSubmissions403 | GetV1ChallengesChallengeidSubmissions404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesChallengeidSubmissionsQueryKey(challengeId, params)

  const query = useQuery({
   ...getV1ChallengesChallengeidSubmissionsQueryOptions(challengeId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesChallengeidSubmissions401 | GetV1ChallengesChallengeidSubmissions403 | GetV1ChallengesChallengeidSubmissions404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}