/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationResponse, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429, PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500 } from "../../../../../../packages/types/kubb/PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationKey = () => [{ url: '/v1/challenges/:challengeId/submissions/:submissionId/auto-review' }] as const

export type PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationKey = ReturnType<typeof postV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationKey>

/**
 * @description Triggers the teacher's-companion auto-review for an existing submission and waits for it to finish. Overwrites any previous auto_review/auto_review_at. Staff-only.
 * @summary Re-run auto review
 * {@link /v1/challenges/:challengeId/submissions/:submissionId/auto-review}
 */
export async function postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview(challengeId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["challengeId"], submissionId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["submissionId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500>, unknown>({ method : "POST", url : `/v1/challenges/${challengeId}/submissions/${submissionId}/auto-review`, ... requestConfig })  
  return res.data
}

/**
 * @description Triggers the teacher's-companion auto-review for an existing submission and waits for it to finish. Overwrites any previous auto_review/auto_review_at. Staff-only.
 * @summary Re-run auto review
 * {@link /v1/challenges/:challengeId/submissions/:submissionId/auto-review}
 */
export function usePostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500>, {challengeId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["challengeId"], submissionId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["submissionId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationKey()

  return useMutation<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewMutationResponse, ResponseErrorConfig<PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview401 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview403 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview404 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview409 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview429 | PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReview500>, {challengeId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["challengeId"], submissionId: PostV1ChallengesChallengeidSubmissionsSubmissionidAutoReviewPathParams["submissionId"]}, TContext>({
    mutationFn: async({ challengeId, submissionId }) => {
      return postV1ChallengesChallengeidSubmissionsSubmissionidAutoReview(challengeId, submissionId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}