/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationResponse, DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams, DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401, DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403, DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404 } from "../../../../../../packages/types/kubb/DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationKey = () => [{ url: '/v1/challenges/:id/knowledge-base/documents/:docId' }] as const

export type DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationKey = ReturnType<typeof deleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationKey>

/**
 * @description Soft delete a document and its chunks from the challenge knowledge base
 * @summary Delete knowledge base document
 * {@link /v1/challenges/:id/knowledge-base/documents/:docId}
 */
export async function deleteV1ChallengesIdKnowledgeBaseDocumentsDocid(id: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["id"], docId: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["docId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404>, unknown>({ method : "DELETE", url : `/v1/challenges/${id}/knowledge-base/documents/${docId}`, ... requestConfig })  
  return res.data
}

/**
 * @description Soft delete a document and its chunks from the challenge knowledge base
 * @summary Delete knowledge base document
 * {@link /v1/challenges/:id/knowledge-base/documents/:docId}
 */
export function useDeleteV1ChallengesIdKnowledgeBaseDocumentsDocid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404>, {id: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["id"], docId: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["docId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationKey()

  return useMutation<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid401 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid403 | DeleteV1ChallengesIdKnowledgeBaseDocumentsDocid404>, {id: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["id"], docId: DeleteV1ChallengesIdKnowledgeBaseDocumentsDocidPathParams["docId"]}, TContext>({
    mutationFn: async({ id, docId }) => {
      return deleteV1ChallengesIdKnowledgeBaseDocumentsDocid(id, docId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}