/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { DeleteV1ChallengesIdKnowledgeBaseKbidMutationResponse, DeleteV1ChallengesIdKnowledgeBaseKbidPathParams, DeleteV1ChallengesIdKnowledgeBaseKbid401, DeleteV1ChallengesIdKnowledgeBaseKbid403, DeleteV1ChallengesIdKnowledgeBaseKbid404 } from "../../../../../../packages/types/kubb/DeleteV1ChallengesIdKnowledgeBaseKbid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const deleteV1ChallengesIdKnowledgeBaseKbidMutationKey = () => [{ url: '/v1/challenges/:id/knowledge-base/:kbId' }] as const

export type DeleteV1ChallengesIdKnowledgeBaseKbidMutationKey = ReturnType<typeof deleteV1ChallengesIdKnowledgeBaseKbidMutationKey>

/**
 * @description Soft delete a knowledge base entry for a challenge
 * @summary Delete knowledge base entry
 * {@link /v1/challenges/:id/knowledge-base/:kbId}
 */
export async function deleteV1ChallengesIdKnowledgeBaseKbid(id: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["id"], kbId: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["kbId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteV1ChallengesIdKnowledgeBaseKbidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseKbid401 | DeleteV1ChallengesIdKnowledgeBaseKbid403 | DeleteV1ChallengesIdKnowledgeBaseKbid404>, unknown>({ method : "DELETE", url : `/v1/challenges/${id}/knowledge-base/${kbId}`, ... requestConfig })  
  return res.data
}

/**
 * @description Soft delete a knowledge base entry for a challenge
 * @summary Delete knowledge base entry
 * {@link /v1/challenges/:id/knowledge-base/:kbId}
 */
export function useDeleteV1ChallengesIdKnowledgeBaseKbid<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteV1ChallengesIdKnowledgeBaseKbidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseKbid401 | DeleteV1ChallengesIdKnowledgeBaseKbid403 | DeleteV1ChallengesIdKnowledgeBaseKbid404>, {id: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["id"], kbId: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["kbId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteV1ChallengesIdKnowledgeBaseKbidMutationKey()

  return useMutation<DeleteV1ChallengesIdKnowledgeBaseKbidMutationResponse, ResponseErrorConfig<DeleteV1ChallengesIdKnowledgeBaseKbid401 | DeleteV1ChallengesIdKnowledgeBaseKbid403 | DeleteV1ChallengesIdKnowledgeBaseKbid404>, {id: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["id"], kbId: DeleteV1ChallengesIdKnowledgeBaseKbidPathParams["kbId"]}, TContext>({
    mutationFn: async({ id, kbId }) => {
      return deleteV1ChallengesIdKnowledgeBaseKbid(id, kbId, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}