/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1ChallengesIdKnowledgeBaseQueryResponse, GetV1ChallengesIdKnowledgeBasePathParams, GetV1ChallengesIdKnowledgeBaseQueryParams, GetV1ChallengesIdKnowledgeBase401, GetV1ChallengesIdKnowledgeBase403, GetV1ChallengesIdKnowledgeBase404 } from "../../../../../../packages/types/kubb/GetV1ChallengesIdKnowledgeBase.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ChallengesIdKnowledgeBaseSuspenseQueryKey = (id: GetV1ChallengesIdKnowledgeBasePathParams["id"], params?: GetV1ChallengesIdKnowledgeBaseQueryParams) => [{ url: '/v1/challenges/:id/knowledge-base/', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetV1ChallengesIdKnowledgeBaseSuspenseQueryKey = ReturnType<typeof getV1ChallengesIdKnowledgeBaseSuspenseQueryKey>

/**
 * @description List knowledge base entries for a challenge with pagination
 * @summary List knowledge base entries
 * {@link /v1/challenges/:id/knowledge-base/}
 */
export async function getV1ChallengesIdKnowledgeBaseSuspense(id: GetV1ChallengesIdKnowledgeBasePathParams["id"], params?: GetV1ChallengesIdKnowledgeBaseQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesIdKnowledgeBaseQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBase401 | GetV1ChallengesIdKnowledgeBase403 | GetV1ChallengesIdKnowledgeBase404>, unknown>({ method : "GET", url : `/v1/challenges/${id}/knowledge-base/`, params, ... requestConfig })  
  return res.data
}

export function getV1ChallengesIdKnowledgeBaseSuspenseQueryOptions(id: GetV1ChallengesIdKnowledgeBasePathParams["id"], params?: GetV1ChallengesIdKnowledgeBaseQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesIdKnowledgeBaseSuspenseQueryKey(id, params)
  return queryOptions<GetV1ChallengesIdKnowledgeBaseQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBase401 | GetV1ChallengesIdKnowledgeBase403 | GetV1ChallengesIdKnowledgeBase404>, GetV1ChallengesIdKnowledgeBaseQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesIdKnowledgeBaseSuspense(id, params, config)
   },
  })
}

/**
 * @description List knowledge base entries for a challenge with pagination
 * @summary List knowledge base entries
 * {@link /v1/challenges/:id/knowledge-base/}
 */
export function useGetV1ChallengesIdKnowledgeBaseSuspense<TData = GetV1ChallengesIdKnowledgeBaseQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesIdKnowledgeBaseSuspenseQueryKey>(id: GetV1ChallengesIdKnowledgeBasePathParams["id"], params?: GetV1ChallengesIdKnowledgeBaseQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1ChallengesIdKnowledgeBaseQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBase401 | GetV1ChallengesIdKnowledgeBase403 | GetV1ChallengesIdKnowledgeBase404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesIdKnowledgeBaseSuspenseQueryKey(id, params)

  const query = useSuspenseQuery({
   ...getV1ChallengesIdKnowledgeBaseSuspenseQueryOptions(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBase401 | GetV1ChallengesIdKnowledgeBase403 | GetV1ChallengesIdKnowledgeBase404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}