/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, GetV1ChallengesIdKnowledgeBaseSearchPathParams, GetV1ChallengesIdKnowledgeBaseSearchQueryParams, GetV1ChallengesIdKnowledgeBaseSearch401, GetV1ChallengesIdKnowledgeBaseSearch404, GetV1ChallengesIdKnowledgeBaseSearch503 } from "../../../../../../packages/types/kubb/GetV1ChallengesIdKnowledgeBaseSearch.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey = (id: GetV1ChallengesIdKnowledgeBaseSearchPathParams["id"], params: GetV1ChallengesIdKnowledgeBaseSearchQueryParams) => [{ url: '/v1/challenges/:id/knowledge-base/search', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey = ReturnType<typeof getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey>

/**
 * @description Search knowledge base entries for a challenge using semantic similarity
 * @summary Semantic search knowledge base
 * {@link /v1/challenges/:id/knowledge-base/search}
 */
export async function getV1ChallengesIdKnowledgeBaseSearchSuspense(id: GetV1ChallengesIdKnowledgeBaseSearchPathParams["id"], params: GetV1ChallengesIdKnowledgeBaseSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBaseSearch401 | GetV1ChallengesIdKnowledgeBaseSearch404 | GetV1ChallengesIdKnowledgeBaseSearch503>, unknown>({ method : "GET", url : `/v1/challenges/${id}/knowledge-base/search`, params, ... requestConfig })  
  return res.data
}

export function getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryOptions(id: GetV1ChallengesIdKnowledgeBaseSearchPathParams["id"], params: GetV1ChallengesIdKnowledgeBaseSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey(id, params)
  return queryOptions<GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBaseSearch401 | GetV1ChallengesIdKnowledgeBaseSearch404 | GetV1ChallengesIdKnowledgeBaseSearch503>, GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, typeof queryKey>({
   enabled: !!(id&& params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChallengesIdKnowledgeBaseSearchSuspense(id, params, config)
   },
  })
}

/**
 * @description Search knowledge base entries for a challenge using semantic similarity
 * @summary Semantic search knowledge base
 * {@link /v1/challenges/:id/knowledge-base/search}
 */
export function useGetV1ChallengesIdKnowledgeBaseSearchSuspense<TData = GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, TQueryKey extends QueryKey = GetV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey>(id: GetV1ChallengesIdKnowledgeBaseSearchPathParams["id"], params: GetV1ChallengesIdKnowledgeBaseSearchQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1ChallengesIdKnowledgeBaseSearchQueryResponse, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBaseSearch401 | GetV1ChallengesIdKnowledgeBaseSearch404 | GetV1ChallengesIdKnowledgeBaseSearch503>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryKey(id, params)

  const query = useSuspenseQuery({
   ...getV1ChallengesIdKnowledgeBaseSearchSuspenseQueryOptions(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1ChallengesIdKnowledgeBaseSearch401 | GetV1ChallengesIdKnowledgeBaseSearch404 | GetV1ChallengesIdKnowledgeBaseSearch503>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}