/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1ChallengesIdKnowledgeBaseMutationRequest, PostV1ChallengesIdKnowledgeBaseMutationResponse, PostV1ChallengesIdKnowledgeBasePathParams, PostV1ChallengesIdKnowledgeBase401, PostV1ChallengesIdKnowledgeBase403, PostV1ChallengesIdKnowledgeBase404 } from "../../../../../../packages/types/kubb/PostV1ChallengesIdKnowledgeBase.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1ChallengesIdKnowledgeBaseMutationKey = () => [{ url: '/v1/challenges/:id/knowledge-base/' }] as const

export type PostV1ChallengesIdKnowledgeBaseMutationKey = ReturnType<typeof postV1ChallengesIdKnowledgeBaseMutationKey>

/**
 * @description Create a new knowledge base entry for a challenge
 * @summary Create knowledge base entry
 * {@link /v1/challenges/:id/knowledge-base/}
 */
export async function postV1ChallengesIdKnowledgeBase(id: PostV1ChallengesIdKnowledgeBasePathParams["id"], data: PostV1ChallengesIdKnowledgeBaseMutationRequest, config: Partial<RequestConfig<PostV1ChallengesIdKnowledgeBaseMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1ChallengesIdKnowledgeBaseMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBase401 | PostV1ChallengesIdKnowledgeBase403 | PostV1ChallengesIdKnowledgeBase404>, PostV1ChallengesIdKnowledgeBaseMutationRequest>({ method : "POST", url : `/v1/challenges/${id}/knowledge-base/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Create a new knowledge base entry for a challenge
 * @summary Create knowledge base entry
 * {@link /v1/challenges/:id/knowledge-base/}
 */
export function usePostV1ChallengesIdKnowledgeBase<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ChallengesIdKnowledgeBaseMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBase401 | PostV1ChallengesIdKnowledgeBase403 | PostV1ChallengesIdKnowledgeBase404>, {id: PostV1ChallengesIdKnowledgeBasePathParams["id"], data: PostV1ChallengesIdKnowledgeBaseMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1ChallengesIdKnowledgeBaseMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ChallengesIdKnowledgeBaseMutationKey()

  return useMutation<PostV1ChallengesIdKnowledgeBaseMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBase401 | PostV1ChallengesIdKnowledgeBase403 | PostV1ChallengesIdKnowledgeBase404>, {id: PostV1ChallengesIdKnowledgeBasePathParams["id"], data: PostV1ChallengesIdKnowledgeBaseMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1ChallengesIdKnowledgeBase(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}