/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1ChallengesIdKnowledgeBaseDocumentsMutationResponse, PostV1ChallengesIdKnowledgeBaseDocumentsPathParams, PostV1ChallengesIdKnowledgeBaseDocuments401, PostV1ChallengesIdKnowledgeBaseDocuments403, PostV1ChallengesIdKnowledgeBaseDocuments404 } from "../../../../../../packages/types/kubb/PostV1ChallengesIdKnowledgeBaseDocuments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1ChallengesIdKnowledgeBaseDocumentsMutationKey = () => [{ url: '/v1/challenges/:id/knowledge-base/documents/' }] as const

export type PostV1ChallengesIdKnowledgeBaseDocumentsMutationKey = ReturnType<typeof postV1ChallengesIdKnowledgeBaseDocumentsMutationKey>

/**
 * @description Upload a document (PDF, TXT, MD) to be parsed and added to the challenge knowledge base
 * @summary Upload document to knowledge base
 * {@link /v1/challenges/:id/knowledge-base/documents/}
 */
export async function postV1ChallengesIdKnowledgeBaseDocuments(id: PostV1ChallengesIdKnowledgeBaseDocumentsPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1ChallengesIdKnowledgeBaseDocumentsMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBaseDocuments401 | PostV1ChallengesIdKnowledgeBaseDocuments403 | PostV1ChallengesIdKnowledgeBaseDocuments404>, unknown>({ method : "POST", url : `/v1/challenges/${id}/knowledge-base/documents/`, ... requestConfig })  
  return res.data
}

/**
 * @description Upload a document (PDF, TXT, MD) to be parsed and added to the challenge knowledge base
 * @summary Upload document to knowledge base
 * {@link /v1/challenges/:id/knowledge-base/documents/}
 */
export function usePostV1ChallengesIdKnowledgeBaseDocuments<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ChallengesIdKnowledgeBaseDocumentsMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBaseDocuments401 | PostV1ChallengesIdKnowledgeBaseDocuments403 | PostV1ChallengesIdKnowledgeBaseDocuments404>, {id: PostV1ChallengesIdKnowledgeBaseDocumentsPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ChallengesIdKnowledgeBaseDocumentsMutationKey()

  return useMutation<PostV1ChallengesIdKnowledgeBaseDocumentsMutationResponse, ResponseErrorConfig<PostV1ChallengesIdKnowledgeBaseDocuments401 | PostV1ChallengesIdKnowledgeBaseDocuments403 | PostV1ChallengesIdKnowledgeBaseDocuments404>, {id: PostV1ChallengesIdKnowledgeBaseDocumentsPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return postV1ChallengesIdKnowledgeBaseDocuments(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}