/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1WorkSessionsIdChatMutationRequest, PostV1WorkSessionsIdChatMutationResponse, PostV1WorkSessionsIdChatPathParams, PostV1WorkSessionsIdChat400, PostV1WorkSessionsIdChat401, PostV1WorkSessionsIdChat403, PostV1WorkSessionsIdChat404, PostV1WorkSessionsIdChat429, PostV1WorkSessionsIdChat500, PostV1WorkSessionsIdChat503 } from "../../../../../../packages/types/kubb/PostV1WorkSessionsIdChat.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1WorkSessionsIdChatMutationKey = () => [{ url: '/v1/work-sessions/:id/chat' }] as const

export type PostV1WorkSessionsIdChatMutationKey = ReturnType<typeof postV1WorkSessionsIdChatMutationKey>

/**
 * @description Sends a user message to the Teaching Assistant agent, saves the interaction, and returns the AI response
 * @summary Send chat message and get TA response
 * {@link /v1/work-sessions/:id/chat}
 */
export async function postV1WorkSessionsIdChat(id: PostV1WorkSessionsIdChatPathParams["id"], data: PostV1WorkSessionsIdChatMutationRequest, config: Partial<RequestConfig<PostV1WorkSessionsIdChatMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1WorkSessionsIdChatMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdChat400 | PostV1WorkSessionsIdChat401 | PostV1WorkSessionsIdChat403 | PostV1WorkSessionsIdChat404 | PostV1WorkSessionsIdChat429 | PostV1WorkSessionsIdChat500 | PostV1WorkSessionsIdChat503>, PostV1WorkSessionsIdChatMutationRequest>({ method : "POST", url : `/v1/work-sessions/${id}/chat`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Sends a user message to the Teaching Assistant agent, saves the interaction, and returns the AI response
 * @summary Send chat message and get TA response
 * {@link /v1/work-sessions/:id/chat}
 */
export function usePostV1WorkSessionsIdChat<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1WorkSessionsIdChatMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdChat400 | PostV1WorkSessionsIdChat401 | PostV1WorkSessionsIdChat403 | PostV1WorkSessionsIdChat404 | PostV1WorkSessionsIdChat429 | PostV1WorkSessionsIdChat500 | PostV1WorkSessionsIdChat503>, {id: PostV1WorkSessionsIdChatPathParams["id"], data: PostV1WorkSessionsIdChatMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1WorkSessionsIdChatMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1WorkSessionsIdChatMutationKey()

  return useMutation<PostV1WorkSessionsIdChatMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdChat400 | PostV1WorkSessionsIdChat401 | PostV1WorkSessionsIdChat403 | PostV1WorkSessionsIdChat404 | PostV1WorkSessionsIdChat429 | PostV1WorkSessionsIdChat500 | PostV1WorkSessionsIdChat503>, {id: PostV1WorkSessionsIdChatPathParams["id"], data: PostV1WorkSessionsIdChatMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return postV1WorkSessionsIdChat(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}