/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1WorkSessionsIdSubmitMutationResponse, PostV1WorkSessionsIdSubmitPathParams, PostV1WorkSessionsIdSubmit400, PostV1WorkSessionsIdSubmit401, PostV1WorkSessionsIdSubmit403, PostV1WorkSessionsIdSubmit404 } from "../../../../../../packages/types/kubb/PostV1WorkSessionsIdSubmit.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1WorkSessionsIdSubmitMutationKey = () => [{ url: '/v1/work-sessions/:id/submit' }] as const

export type PostV1WorkSessionsIdSubmitMutationKey = ReturnType<typeof postV1WorkSessionsIdSubmitMutationKey>

/**
 * @description Marks the work session as submitted (sets endedAt). Only the session owner can submit.
 * @summary Submit work session
 * {@link /v1/work-sessions/:id/submit}
 */
export async function postV1WorkSessionsIdSubmit(id: PostV1WorkSessionsIdSubmitPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1WorkSessionsIdSubmitMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdSubmit400 | PostV1WorkSessionsIdSubmit401 | PostV1WorkSessionsIdSubmit403 | PostV1WorkSessionsIdSubmit404>, unknown>({ method : "POST", url : `/v1/work-sessions/${id}/submit`, ... requestConfig })  
  return res.data
}

/**
 * @description Marks the work session as submitted (sets endedAt). Only the session owner can submit.
 * @summary Submit work session
 * {@link /v1/work-sessions/:id/submit}
 */
export function usePostV1WorkSessionsIdSubmit<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1WorkSessionsIdSubmitMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdSubmit400 | PostV1WorkSessionsIdSubmit401 | PostV1WorkSessionsIdSubmit403 | PostV1WorkSessionsIdSubmit404>, {id: PostV1WorkSessionsIdSubmitPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1WorkSessionsIdSubmitMutationKey()

  return useMutation<PostV1WorkSessionsIdSubmitMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdSubmit400 | PostV1WorkSessionsIdSubmit401 | PostV1WorkSessionsIdSubmit403 | PostV1WorkSessionsIdSubmit404>, {id: PostV1WorkSessionsIdSubmitPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return postV1WorkSessionsIdSubmit(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}