/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1WorkSessionsMutationRequest, PostV1WorkSessionsMutationResponse, PostV1WorkSessions400, PostV1WorkSessions401, PostV1WorkSessions403, PostV1WorkSessions404 } from "../../../../../../packages/types/kubb/PostV1WorkSessions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1WorkSessionsMutationKey = () => [{ url: '/v1/work-sessions/' }] as const

export type PostV1WorkSessionsMutationKey = ReturnType<typeof postV1WorkSessionsMutationKey>

/**
 * @description Start a new work session on a challenge. Optionally pass teachingAssistantId; if omitted, the server picks the default TA linked to the challenge, or an active TA from the classroom/user organization when the challenge has no M2M row.
 * @summary Create work session
 * {@link /v1/work-sessions/}
 */
export async function postV1WorkSessions(data: PostV1WorkSessionsMutationRequest, config: Partial<RequestConfig<PostV1WorkSessionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1WorkSessionsMutationResponse, ResponseErrorConfig<PostV1WorkSessions400 | PostV1WorkSessions401 | PostV1WorkSessions403 | PostV1WorkSessions404>, PostV1WorkSessionsMutationRequest>({ method : "POST", url : `/v1/work-sessions/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Start a new work session on a challenge. Optionally pass teachingAssistantId; if omitted, the server picks the default TA linked to the challenge, or an active TA from the classroom/user organization when the challenge has no M2M row.
 * @summary Create work session
 * {@link /v1/work-sessions/}
 */
export function usePostV1WorkSessions<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1WorkSessionsMutationResponse, ResponseErrorConfig<PostV1WorkSessions400 | PostV1WorkSessions401 | PostV1WorkSessions403 | PostV1WorkSessions404>, {data: PostV1WorkSessionsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1WorkSessionsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1WorkSessionsMutationKey()

  return useMutation<PostV1WorkSessionsMutationResponse, ResponseErrorConfig<PostV1WorkSessions400 | PostV1WorkSessions401 | PostV1WorkSessions403 | PostV1WorkSessions404>, {data: PostV1WorkSessionsMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1WorkSessions(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}