/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { PostV1WorkSessionsIdReopenMutationResponse, PostV1WorkSessionsIdReopenPathParams, PostV1WorkSessionsIdReopen400, PostV1WorkSessionsIdReopen401, PostV1WorkSessionsIdReopen403, PostV1WorkSessionsIdReopen404 } from "../../../../../../packages/types/kubb/PostV1WorkSessionsIdReopen.ts";
import { useMutation } from "@tanstack/react-query";

export const postV1WorkSessionsIdReopenMutationKey = () => [{ url: '/v1/work-sessions/:id/reopen' }] as const

export type PostV1WorkSessionsIdReopenMutationKey = ReturnType<typeof postV1WorkSessionsIdReopenMutationKey>

/**
 * @description Clears endedAt on a submitted work session. Teacher, coordinator, or admin only.
 * @summary Reopen work session
 * {@link /v1/work-sessions/:id/reopen}
 */
export async function postV1WorkSessionsIdReopen(id: PostV1WorkSessionsIdReopenPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostV1WorkSessionsIdReopenMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdReopen400 | PostV1WorkSessionsIdReopen401 | PostV1WorkSessionsIdReopen403 | PostV1WorkSessionsIdReopen404>, unknown>({ method : "POST", url : `/v1/work-sessions/${id}/reopen`, ... requestConfig })  
  return res.data
}

/**
 * @description Clears endedAt on a submitted work session. Teacher, coordinator, or admin only.
 * @summary Reopen work session
 * {@link /v1/work-sessions/:id/reopen}
 */
export function usePostV1WorkSessionsIdReopen<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1WorkSessionsIdReopenMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdReopen400 | PostV1WorkSessionsIdReopen401 | PostV1WorkSessionsIdReopen403 | PostV1WorkSessionsIdReopen404>, {id: PostV1WorkSessionsIdReopenPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1WorkSessionsIdReopenMutationKey()

  return useMutation<PostV1WorkSessionsIdReopenMutationResponse, ResponseErrorConfig<PostV1WorkSessionsIdReopen400 | PostV1WorkSessionsIdReopen401 | PostV1WorkSessionsIdReopen403 | PostV1WorkSessionsIdReopen404>, {id: PostV1WorkSessionsIdReopenPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return postV1WorkSessionsIdReopen(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}