/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1StatusQueryResponse } from "../../../../../../packages/types/kubb/GetV1Status.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1StatusSuspenseQueryKey = () => [{ url: '/v1/status' }] as const

export type GetV1StatusSuspenseQueryKey = ReturnType<typeof getV1StatusSuspenseQueryKey>

/**
 * @description Returns the API health status and uptime
 * @summary Health check endpoint
 * {@link /v1/status}
 */
export async function getV1StatusSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1StatusQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/status`, ... requestConfig })  
  return res.data
}

export function getV1StatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1StatusSuspenseQueryKey()
  return queryOptions<GetV1StatusQueryResponse, ResponseErrorConfig<Error>, GetV1StatusQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1StatusSuspense(config)
   },
  })
}

/**
 * @description Returns the API health status and uptime
 * @summary Health check endpoint
 * {@link /v1/status}
 */
export function useGetV1StatusSuspense<TData = GetV1StatusQueryResponse, TQueryKey extends QueryKey = GetV1StatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1StatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1StatusSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1StatusSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}