/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { GetV1UsersMeQueryResponse, GetV1UsersMe401 } from "../../../../../../packages/types/kubb/GetV1UsersMe.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1UsersMeSuspenseQueryKey = () => [{ url: '/v1/users/me' }] as const

export type GetV1UsersMeSuspenseQueryKey = ReturnType<typeof getV1UsersMeSuspenseQueryKey>

/**
 * @description Returns the profile of the currently authenticated user
 * @summary Get current authenticated user data
 * {@link /v1/users/me}
 */
export async function getV1UsersMeSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, unknown>({ method : "GET", url : `/v1/users/me`, ... requestConfig })  
  return res.data
}

export function getV1UsersMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1UsersMeSuspenseQueryKey()
  return queryOptions<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, GetV1UsersMeQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1UsersMeSuspense(config)
   },
  })
}

/**
 * @description Returns the profile of the currently authenticated user
 * @summary Get current authenticated user data
 * {@link /v1/users/me}
 */
export function useGetV1UsersMeSuspense<TData = GetV1UsersMeQueryResponse, TQueryKey extends QueryKey = GetV1UsersMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1UsersMeSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getV1UsersMeSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1UsersMe401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}