/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetV1UsersQueryResponse, GetV1UsersQueryParams, GetV1Users401, GetV1Users403 } from "../../../../../../packages/types/kubb/GetV1Users.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1UsersSuspenseQueryKey = (params: GetV1UsersQueryParams) => [{ url: '/v1/users/' }, ...(params ? [params] : [])] as const

export type GetV1UsersSuspenseQueryKey = ReturnType<typeof getV1UsersSuspenseQueryKey>

/**
 * @description Global, paginated user search by name or email (ilike). Each item includes the user's organization memberships. Platform admin only.
 * @summary Search users (admin)
 * {@link /v1/users/}
 */
export async function getV1UsersSuspense(params: GetV1UsersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1UsersQueryResponse, ResponseErrorConfig<GetV1Users401 | GetV1Users403>, unknown>({ method : "GET", url : `/v1/users/`, params, ... requestConfig })  
  return res.data
}

export function getV1UsersSuspenseQueryOptions(params: GetV1UsersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1UsersSuspenseQueryKey(params)
  return queryOptions<GetV1UsersQueryResponse, ResponseErrorConfig<GetV1Users401 | GetV1Users403>, GetV1UsersQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1UsersSuspense(params, config)
   },
  })
}

/**
 * @description Global, paginated user search by name or email (ilike). Each item includes the user's organization memberships. Platform admin only.
 * @summary Search users (admin)
 * {@link /v1/users/}
 */
export function useGetV1UsersSuspense<TData = GetV1UsersQueryResponse, TQueryKey extends QueryKey = GetV1UsersSuspenseQueryKey>(params: GetV1UsersQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetV1UsersQueryResponse, ResponseErrorConfig<GetV1Users401 | GetV1Users403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1UsersSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getV1UsersSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1Users401 | GetV1Users403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}