/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1UsersMeQueryResponse, GetV1UsersMe401 } from "../../../../../../packages/types/kubb/GetV1UsersMe.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1UsersMeQueryKey = () => [{ url: '/v1/users/me' }] as const

export type GetV1UsersMeQueryKey = ReturnType<typeof getV1UsersMeQueryKey>

/**
 * @description Returns the profile of the currently authenticated user
 * @summary Get current authenticated user data
 * {@link /v1/users/me}
 */
export async function getV1UsersMe(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, unknown>({ method : "GET", url : `/v1/users/me`, ... requestConfig })  
  return res.data
}

export function getV1UsersMeQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1UsersMeQueryKey()
  return queryOptions<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, GetV1UsersMeQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1UsersMe(config)
   },
  })
}

/**
 * @description Returns the profile of the currently authenticated user
 * @summary Get current authenticated user data
 * {@link /v1/users/me}
 */
export function useGetV1UsersMe<TData = GetV1UsersMeQueryResponse, TQueryData = GetV1UsersMeQueryResponse, TQueryKey extends QueryKey = GetV1UsersMeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetV1UsersMeQueryResponse, ResponseErrorConfig<GetV1UsersMe401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1UsersMeQueryKey()

  const query = useQuery({
   ...getV1UsersMeQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1UsersMe401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}