/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetV1ChatStudentHistoryWorksessionidQueryResponse, GetV1ChatStudentHistoryWorksessionidPathParams, GetV1ChatStudentHistoryWorksessionid401, GetV1ChatStudentHistoryWorksessionid404 } from "../../../../../../packages/types/kubb/GetV1ChatStudentHistoryWorksessionid.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ChatStudentHistoryWorksessionidQueryKey = (workSessionId: GetV1ChatStudentHistoryWorksessionidPathParams["workSessionId"]) => [{ url: '/v1/chat/student/history/:workSessionId', params: {workSessionId:workSessionId} }] as const

export type GetV1ChatStudentHistoryWorksessionidQueryKey = ReturnType<typeof getV1ChatStudentHistoryWorksessionidQueryKey>

/**
 * @description Returns all user interactions (prompts and model responses) for the given work session.
 * @summary Get student chat history for a work session
 * {@link /v1/chat/student/history/:workSessionId}
 */
export async function getV1ChatStudentHistoryWorksessionid(workSessionId: GetV1ChatStudentHistoryWorksessionidPathParams["workSessionId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetV1ChatStudentHistoryWorksessionidQueryResponse, ResponseErrorConfig<GetV1ChatStudentHistoryWorksessionid401 | GetV1ChatStudentHistoryWorksessionid404>, unknown>({ method : "GET", url : `/v1/chat/student/history/${workSessionId}`, ... requestConfig })  
  return res.data
}

export function getV1ChatStudentHistoryWorksessionidQueryOptions(workSessionId: GetV1ChatStudentHistoryWorksessionidPathParams["workSessionId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getV1ChatStudentHistoryWorksessionidQueryKey(workSessionId)
  return queryOptions<GetV1ChatStudentHistoryWorksessionidQueryResponse, ResponseErrorConfig<GetV1ChatStudentHistoryWorksessionid401 | GetV1ChatStudentHistoryWorksessionid404>, GetV1ChatStudentHistoryWorksessionidQueryResponse, typeof queryKey>({
   enabled: !!(workSessionId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1ChatStudentHistoryWorksessionid(workSessionId, config)
   },
  })
}

/**
 * @description Returns all user interactions (prompts and model responses) for the given work session.
 * @summary Get student chat history for a work session
 * {@link /v1/chat/student/history/:workSessionId}
 */
export function useGetV1ChatStudentHistoryWorksessionid<TData = GetV1ChatStudentHistoryWorksessionidQueryResponse, TQueryData = GetV1ChatStudentHistoryWorksessionidQueryResponse, TQueryKey extends QueryKey = GetV1ChatStudentHistoryWorksessionidQueryKey>(workSessionId: GetV1ChatStudentHistoryWorksessionidPathParams["workSessionId"], options: 
{
  query?: Partial<QueryObserverOptions<GetV1ChatStudentHistoryWorksessionidQueryResponse, ResponseErrorConfig<GetV1ChatStudentHistoryWorksessionid401 | GetV1ChatStudentHistoryWorksessionid404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getV1ChatStudentHistoryWorksessionidQueryKey(workSessionId)

  const query = useQuery({
   ...getV1ChatStudentHistoryWorksessionidQueryOptions(workSessionId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetV1ChatStudentHistoryWorksessionid401 | GetV1ChatStudentHistoryWorksessionid404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}