/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/apiClient";
import type { PostV1ChatTeacherMessageMutationRequest, PostV1ChatTeacherMessageMutationResponse, PostV1ChatTeacherMessage401, PostV1ChatTeacherMessage404, PostV1ChatTeacherMessage500 } from "../../../../../../packages/types/kubb/PostV1ChatTeacherMessage.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/apiClient";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postV1ChatTeacherMessageMutationKey = () => [{ url: '/v1/chat/teacher/message' }] as const

export type PostV1ChatTeacherMessageMutationKey = ReturnType<typeof postV1ChatTeacherMessageMutationKey>

/**
 * @description Invokes the LangGraph teacher's companion agent in-process and streams the response as SSE events. Teacher chat is ephemeral for MVP (no DB persistence).
 * @summary Send a message to the teacher's companion agent (SSE)
 * {@link /v1/chat/teacher/message}
 */
export async function postV1ChatTeacherMessage(data: PostV1ChatTeacherMessageMutationRequest, config: Partial<RequestConfig<PostV1ChatTeacherMessageMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostV1ChatTeacherMessageMutationResponse, ResponseErrorConfig<PostV1ChatTeacherMessage401 | PostV1ChatTeacherMessage404 | PostV1ChatTeacherMessage500>, PostV1ChatTeacherMessageMutationRequest>({ method : "POST", url : `/v1/chat/teacher/message`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Invokes the LangGraph teacher's companion agent in-process and streams the response as SSE events. Teacher chat is ephemeral for MVP (no DB persistence).
 * @summary Send a message to the teacher's companion agent (SSE)
 * {@link /v1/chat/teacher/message}
 */
export function usePostV1ChatTeacherMessage<TContext>(options: 
{
  mutation?: UseMutationOptions<PostV1ChatTeacherMessageMutationResponse, ResponseErrorConfig<PostV1ChatTeacherMessage401 | PostV1ChatTeacherMessage404 | PostV1ChatTeacherMessage500>, {data: PostV1ChatTeacherMessageMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostV1ChatTeacherMessageMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postV1ChatTeacherMessageMutationKey()

  return useMutation<PostV1ChatTeacherMessageMutationResponse, ResponseErrorConfig<PostV1ChatTeacherMessage401 | PostV1ChatTeacherMessage404 | PostV1ChatTeacherMessage500>, {data: PostV1ChatTeacherMessageMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return postV1ChatTeacherMessage(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}